### ISSUE TITLE
Use HTTP/2 for connections.

### ISSUE THREAD

**Issue by KempfCreative** [vercel/next.js#12159]
# Feature request

We should be using HTTP/2 by default without needing to use a custom server.

---

I would like NextJS to use HTTP2 for connections and serving the actual pages generated by NextJS.

---

A basic HTTP/2 implementation should be implemented in NextJS without having to use a custom server, which disables automatic static optimization.

**Comment by timneutkens** [comment]
Happy to review a PR to add a flag to opt-in to using the http2 server.

**Comment by finleygn** [comment]
Gonna have a go a this

**Comment by finleygn** [comment]
Okay so got some time to do some digging.

As far as I can tell this would require a rewrite of a good portion of the NextServer class and its utils because of differences between nodes http and http2 modules when using the [compatibility API](https://nodejs.org/api/http2.html#http2_compatibility_api). 

My plan is to have a BaseServer which is extended by NextHttp1Server and NextHttp2Server with their own implementations for any methods that interact with req, res. 

A decent amount of complexity is going to be added because of this, @timneutkens it's gonna be a pretty hefty PR :)

**Comment by timneutkens** [comment]
If it's too complex it might not be worth adding at this point so it might be good if you could write a RFC for it

**Comment by finleygn** [comment]
yea okay, is there an existing place to make a PR to for RFCs?

**Comment by TodorTotev** [comment]
@finleygn let me know if you need a hand

**Comment by sagar-gavhane** [comment]
@finleygn I'm ready to contribute for `HTTP2` support.

**Comment by finleygn** [comment]
@TodorTotev @sagar-gavhane 

I'll get something written down when I have some time, getting your thoughts on it would be really helpful, thanks

**Comment by timneutkens** [comment]
@finleygn generally we post them on discussions: github.com/vercel/next.js/discussions

**Comment by finleygn** [comment]
Posted a base RFC #13689 

not as much would need to be rewritten now I've done some more looking into it :flushed:, the main problem is the read-only req, but got ideas for that.

will put together a draft PR in the next few days & build on it with any discussion on the RFC

**Comment by finleygn** [comment]
busy atm so won't be able to make progress on this for a while
if anyone else wants to tackle this then go ahead but ill be back on it next month

**Comment by estin8** [comment]
> busy atm so won't be able to make progress on this for a while if anyone else wants to tackle this then go ahead but ill be back on it next month

Hi there! Any chance you ever got around to this?

**Comment by wouter-deen** [comment]
Am I wrong, or is HTTP/2 still not supported? It seems like it'd be a pretty big deal to support it, partly because of the multiplex capabilities and a major speed difference. I tried setting my Google Cloud Run service to use HTTP2, but it resulted in a `upstream connect error or disconnect/reset before headers` error.

**Comment by balazsorban44** [comment]
Let's follow the RFC on this. AFAIK there is no active PR around this either.
