### ISSUE TITLE
Add support for deno

### ISSUE THREAD

**Issue by Evian-Zhang** [vercel/next.js#12334]
# Feature request

## Is your feature request related to a problem? Please describe.

As deno is going to [have its 1.0 release at May 13](https://github.com/denoland/deno/issues/2473), will next.js add support for deno?

**Comment by gustavocastrov** [comment]
Urge!

**Comment by tsujp** [comment]
Any progress on this?

**Comment by timneutkens** [comment]
@tsujp feel free to contribute to making it work.

**Comment by tsujp** [comment]
Planned to have a gander, wanted to chime in here just in-case there are parallel efforts going on.

**Comment by lemarier** [comment]
Hi @timneutkens, I would love to help on this. Something have been planned? 

Did you guys have an idea of what need to be done exactly?

Thanks

**Comment by timneutkens** [comment]
In this case it’ll be entirely up to the people that want to land it. I assume you’ll have to figure out how to run webpack/Babel in deno first though.

**Comment by tsujp** [comment]
I was a bit naive in my "progress on this" above. All the dependencies of Next, and their dependencies' dependencies etc will need to work with deno before Next could -- so I suppose "progress on this" is more of a "progress on deno for production?". I have also heard various people are trying to get dependency auditing (e.g., [deno_udd](https://github.com/hayd/deno-udd)). So these kinds of tools have to be more mature also.

Whoops.

**Comment by webdeb** [comment]
Just created a simple webservice with deno to handle webhooks.
At the end I was able to `deno bundle` the whole application into a **~432 kb** bundle.js file 🎉

**Comment by kachkaev** [comment]
There is a new project called [Aleph.js](https://alephjs.org), which is

> The React Framework in Deno, inspired by Next.js. 

GitHub: https://github.com/alephjs/aleph.js

Could be worth watching the space to cross-pollinate some ideas 🙂

**Comment by baer** [comment]
At the time of writing, the babel team does not have any plans to support Deno. 

https://github.com/babel/babel/issues/11543#issuecomment-724959695

**Comment by shadowtime2000** [comment]
I think adding support for Deno to NextJS would be a very time consuming task and would make it harder to maintain the codebase, though I haven't actually looked at the codebase so idk. I think its a better idea to keep NextJS in the Node ecosystem and to have tools like AlephJS in the Deno ecosystem, though that may be a bias opinion because I am a maintainer of AlephJS.

**Comment by michailVestnik** [comment]
now on Deno there is everything that is so loved in Node.js
next.js - [](https://deno.land/x/aleph@v0.3.0-alpha.8)
express - [](https://deno.land/x/opine@1.1.0)
koa - [](https://deno.land/x/oak@v6.5.0)
SQLite - [](https://deno.land/x/sqlite@v2.3.2) extreme fast? because in wasm
MongoDB - [](https://deno.land/x/mongo@v0.21.2)
NeDB - [](https://deno.land/x/dndb@0.3.1)
Electron.js - [](https://github.com/tauri-apps/tauri), [](https://deno.land/x/webview@0.5.6)
And more... 
but more modern, faster and minimalistic.

**Comment by JerryGreen** [comment]
I love how this issue has <kbd>good first issue</kbd> tag, while it’s nearly impossible for NextJS to support Deno. Maybe they can just morally support and say: “Hey guys, gl in whatever you’re doing!” and be done with it, but everyone will consider this 126% rude, so silence is better 😂

Honestly the last time I checked Deno when v1 came out, it was quite poorly working for Windows, and all the feedback I got from their somewhat-core team was almost like: “windows? hah we’re having some kid here not knowing that you have to use Linux to develop things... use WSL” (well, he said somewhat like this), but WSL is almost like little virtual Linux machine, so mehhh... While NodeJS is working without any virtual machine layer completely fine, it’s a shame Deno can’t be run that easily too. So despite Deno v1 came out, they still have a lot of work to do to improve their fundamental things like cross-platform support (at the very least)

Their core-core member Ryan Dahl sympathizes me actually: he has good vision, good ideas, so maybe some Deno v2 will be much better and more production-ready, who knows... _💕waves tons of support 💕_

**Comment by shadowtime2000** [comment]
@JerryGreen It seems your points about Deno needing to improve cross-platform support is based on Deno v1 which was released around a year ago. I have been using Deno and plain old Windows without WSL for AlephJS and other projects, and it has been working great. You can't really base it's flaws around the v1 release which was around a year ago. I recommend you download the latest Deno, v1.8.2, and try it out because those "fundamental things" have been worked on.

**Comment by JerryGreen** [comment]
@shadowtime2000 time flows fast 😅 Thank you for saying all that, I’ll keep in mind Deno deserves another try.

I saw AlephJS back in the days too, and yeah: if you wanna use Deno and want NextJS then AlephJS is definitely your choice, despite having some differences it fits the most.

For some other things, like Electron, people do have equivalent questions though:

https://github.com/electron/electron/issues/23613

Unfortunately there’s no such thing as Denotron or something 😞 I think if Deno had it, I might have started using Deno for whatever projects I’m building already
