### ISSUE TITLE
Add new Router method to replace url hash without scrolling

### ISSUE THREAD

**Issue by monae** [vercel/next.js#13804]
# Feature request

## Is your feature request related to a problem? Please describe.

I want to use url hash (e.g. `/page#something`) to show a user-shareable state in a page.
However, `Router.replace` causes scrolling to the anchor element.
https://github.com/vercel/next.js/blob/v9.4.4/packages/next/next-server/lib/router/router.ts#L408

To avoid this behavior and other side effects, we can call History API manually:
```javascript
window.history.replaceState({ url, as, options }, '', '#something')
```
Although it works correctly, it is very fragile as it depends on internal implementation of Next.js.

There is a similar issue (https://github.com/vercel/next.js/issues/6862) but `shallow` option does not help in this case.

## Describe the solution you'd like

Add new method to Router to call `history.replaceState` above in a consistent manner.
What I really want is just to replace hash, so the replacement can be limited to hash only rather than whole url.

**Comment by joggienl** [comment]
I guess this boils down to being able to pass something like `scroll: false` to `router.push` and `router.replace`. Is that what you imply?

```js
router.push('#dont-go-here', undefined, { scroll: false };
```

I am facing a similar issue where I want to apply smooth scrolling to links (to anchor links on the same page). On links to a new page, the smooth scroll is "weird" UX.

So in complement another option to add to this request would be adding a `behaviour` option as well, because that can be added to the `scrollIntoView` method on https://github.com/vercel/next.js/blob/v9.4.4/packages/next/next-server/lib/router/router.ts#L719 and https://github.com/vercel/next.js/blob/v9.4.4/packages/next/next-server/lib/router/router.ts#L726.

```js
router.push('#dont-go-here', undefined, { scroll: false, behaviour: 'smooth' };
```
