### ISSUE TITLE
Edge 18 (Object.fromEntries) not supported even with correct polyfills

### ISSUE THREAD

**Issue by FBosler** [vercel/next.js#16715]
# Bug report

using the following `.babel.rc` leads to a build that should in theory support edge 18. 
```
{
    "presets": [
        [
            "next/babel",
            {
                "preset-env": {
                    "targets": "> 0.25%"
                }
            }
        ]
    ],
    "plugins": [
        ["styled-components", { "ssr": true }],
        [
            "module-resolver",
            {
                "root": ["."],
                "alias": {
                    "@/Components": "components",
                   ...
                    "@/Functions": "components/Concepts/Functions"
                }
            }
        ]
    ]
}
```
This can be confirmed by running  `npx browserslist "> 0.25%"`. However, when testing live via browserstack (as its pretty hard to actually install edge 18), it seems like this is not the case, as the following bug pops up:
```
TypeError
Object doesn't support property or method 'fromEntries'
```

## To Reproduce
Unfortunately, it's pretty hard for me to reliably reproduce the bug in a minimal example as I can't even run edge 18 locally. However, navigating to https://staging-viteach.com/concepts/rational%20numbers with edge 18 AND logging in - no validation required - will produce the bug.

## Expected behavior
Would think that the config creates the correct polyfill.

## Screenshots
![image](https://user-images.githubusercontent.com/14016698/91705861-d8dca680-eb7d-11ea-8a19-b80fb8a18d45.png)

## System information

- OS: Windows 10 (runtime)
- Browser (if applies) edge 18 (runtime)
- Version of Next.js: 9.4.4 (buildtime)
- Version of Node.js: 13.13 (buildtime)

**Comment by eezing** [comment]
@FBosler stacktrace available?

**Comment by FBosler** [comment]
> @FBosler stacktrace available?

Sorry, browserstack won't let me copy stuff, seems like its sandboxed. Not sure if the screenshot helps though. Thanks for looking into this.

![image](https://user-images.githubusercontent.com/14016698/91953148-64327500-ed01-11ea-84a1-6180c2cdcd18.png)

**Comment by FBosler** [comment]
Any news on this? Or is there a way to monkey patch this? I am encountering a surprising large number of errors for this.

**Comment by samovertonjr** [comment]
@FBosler the fix might be to `npm install object.fromentries`this is a polyfill. I'll try and do a fix in next but idk how polyfills are handled yet. This link might help explain it more [https://github.com/microsoft/TypeScript/issues/32803](https://github.com/microsoft/TypeScript/issues/32803)

**Comment by FBosler** [comment]
@samovertonjr makes sense! Thx, I'll have a look.

**Comment by eezing** [comment]
@FBosler It could be caused by a non-transpiled NPM module. I'm using a few NPM modules that aren't transpiled, [next-transpile-modules](https://github.com/kutlugsahin/next-transpile-modules) solved my problem.

**Comment by tkrotoff** [comment]
Check https://nextjs.org/docs/basic-features/supported-browsers-features#custom-polyfills

Create `src/polyfills.js`:

```JS
// https://github.com/vercel/next.js/pull/15772#discussion_r463984612
import 'core-js/features/object/from-entries';
```

and import it inside your [custom `src/pages/_app.js`](https://nextjs.org/docs/advanced-features/custom-app):

```JS
// https://nextjs.org/docs/basic-features/supported-browsers-features#custom-polyfills
import '../polyfills';

function App({ Component, pageProps }) {
  return (
    <Component {...pageProps} />
  );
}

export default App;
```

Why do you have to do this? Because Next.js does not include all polyfills. Instead @timneutkens decided to include only the most common ones (https://github.com/vercel/next.js/pull/15772#discussion_r463984612, https://github.com/vercel/next.js/issues/11714) to avoid increasing the bundle.

Be ready for hours of IE/old Edge debugging in a [VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) to understand what fails (can be pretty hard considering how basic and slow IE dev tools are).

In a regular React app without Next.js, you would simply [`import 'core-js'`](https://github.com/zloirock/core-js) and be done: no worries about a npm dependency update that might introduce the use of a basic JS feature not polyfilled by Next.js.

FYI Object.fromEntries() core-js polyfill is [5 lines of code](https://github.com/zloirock/core-js/blob/v3.8.3/packages/core-js/modules/es.object.from-entries.js).
