### ISSUE TITLE
Clearer Custom Error Page documentation page

### ISSUE THREAD

**Issue by creativiii** [vercel/next.js#17778]
# Bug report

## Describe the bug

I'm unsure if this can be counted as a bug, but I think the documentation page is missing information, or the example isn't actually working properly. I'm more than happy to submit a PR for changing the documentation page, but I wanted to make sure if I'm wrong before doing so.

The problem lies with the [Custom Error Page](https://nextjs.org/docs/advanced-features/custom-error-page) specifically with the third example.

The docs are telling people that to display the error page yourself you simply need to return it from main component:
```
export default function Page({ errorCode, stars }) {
  if (errorCode) {
    return <Error statusCode={errorCode} />
  }

  return <div>Next stars: {stars}</div>
}
```

And while this will render the error page, it actually won't set the correct status code, you can check this in the network tab of the your browser's dev tools, the response will always be **200**.

To return the correct error code I need to do so in `getServerSideProps`:
```
export async function getServerSideProps({response}) {
  const res = await fetch('https://api.github.com/repos/vercel/next.js')
  const errorCode = res.ok ? false : res.statusCode
  const json = await res.json()

  // This line is missing from the example
  response.statusCode = errorCode 

  return {
    props: { errorCode, stars: json.stargazers_count },
  }
}
```

I was very confused why Google kept indexing pages that were returning 404 for me before I realised this was the problem so I think it's worth adding to the documentation to avoid any further confusion. Especially since this is so important for SEO.

Let me know if this is worth changing, maybe I'm the only one that thinks this is useful 😂

**Comment by ajgrover** [comment]
I don't think there's an error in the documentation. You shouldn't be able to see a network request in your dev tools because the `fetch` is only happening on the server. What you're doing is causing the next server to think that an exception happened when it actually didn't.

The confusion might be happening because the `fetch('https://api.github.com/repos/vercel/next.js')` will likely 200 - that's a valid API call, unless Github is having an outage. So no `errorCode` is actually being passed to your page component. If you change the fetch to point to a URL that returns a 4xx or 5xx you'll see the correct error page rendered.

You can simulate this and verify that the right thing is actually happening by adding a `return { errorCode: 400/422/500 }` in the gSSP function.
