### ISSUE TITLE
getStaticProps SerializableError: Error serializing ... returned from `getStaticProps` 

### ISSUE THREAD

**Issue by cezarneaga** [vercel/next.js#18897]
# Bug report

## Describe the bug

https://codesandbox.io/s/great-hooks-rxi1d?file=/pages/index.js

i reproduced the issue here. i produce correct data (you can see the logs from the function) but the staticProps fail to read them.

## To Reproduce

https://codesandbox.io/s/great-hooks-rxi1d?file=/pages/index.js

## Expected behavior

i expect it to give correct data to components. not sure if i am doing something wrong or is it an issue with the graphql server

## System information

- OS:  macOS,

- Version of Next.js: [e.g. 10.0.1]
- Version of Node.js: [e.g. 15.0.1]

**Comment by olivertilk** [comment]
I got this same error when I was trying to pass an object to a new external function for processing and then trying to use the return value as the new object. The error resolved when I got rid of the external function and moved the code back to the original function.

I see a similar pattern here. You are using an external function (fetchContent) to process an object (result) and then trying to use the return value as the new object (const { items } = ...).

I would try making the fetch call inside of getStaticProps instead of through fetchContent.
