### ISSUE TITLE
Nextjs: Next/image transiction using dynamic src

### ISSUE THREAD

**Issue by rafaeleduardoteixeira** [vercel/next.js#20220]
I'm using next/image, the src is updated every 8 seconds (variable backgroudImg). I needed to make a transition effect when it changes, could anyone help?

I tried to use transiction on styled components didn't work.

Code JSX:

```
<section className="bgWrap">
  <Image
    alt="Banner"
    src={backgroudImg}
    quality={100}
    layout="fill"
    objectFit="inherit"
  />
</section>
```

Styled:

  .```
bgWrap {
    position: absolute;
    overflow: hidden;
    height: 110vh;
    width: 100%;
    z-index: -1;

    transition: all 1s;
  }
```

**Comment by daichi-ranguru** [comment]
Hey, I'm also trying to figure this one out. I have read the source code and looked at the basic css that Image component has. Only thing that could be transitionable is visibility css property, because it switches itself from hidden to visible based on image loading state. As we all know that visibility property cannot be animated since it cant be calculated by the browser.

We cant animate it whatsoever, or atleast by the info I know, since we cannot even use ref at this state.

I will try find some time and help as much as I can on this matter
