### ISSUE TITLE
Image component - Avoid an excessive DOM size on Google speed test

### ISSUE THREAD

**Issue by IRediTOTO** [vercel/next.js#20452]
# Bug report
Image component 
## Describe the bug
This is not a bug i think, but can we do something with that to improve soccer?
![image](https://user-images.githubusercontent.com/15695252/103084269-2be8d680-4611-11eb-8776-114f0cde18d7.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 10.0.1]
- Version of Node.js: [e.g. 12.0.0]
- Deployment: [e.g. next start, next export, Vercel, other platform]

**Comment by awareness481** [comment]
From the Lighthouse report, this seems to not be related to `next/image` although I'm not sure why it shows a DOM depth of 17, that could be a bug with lighthouse?

In any case, per [web.dev](https://web.dev/dom-size/#how-the-lighthouse-dom-size-audit-fails) a DOM depth smaller than 32 shouldn't trigger a warning. This seems to be because of  the `Avoid excessive DOM` warning.

Might be related to https://github.com/GoogleChrome/lighthouse/issues/11631
