### ISSUE TITLE
Integrate Better Support For Wildcard Domains

### ISSUE THREAD

**Issue by sampoder** [vercel/next.js#20775]
**Describe the feature you'd like to request**

Vercel has support for wildcard domains. I think that it would be awesome if similar to the setup with [slug].js we could get [wildcard].yourdomain.com.

**Describe the solution you'd like**

I believe that a good solution would be something like this:

```javascript
import getWildcard from "next/wildcard";

// Access it in your default function

export default function Home(props) {
  return <div>The wildcard is: {getWildcard()}</div>;
}

// If you went to sampoder.yourdomain.com, this code sample would output a page saying "The wildcard is: sampoder"

// Or when using getServerSideProps()

export async function getServerSideProps() {
   let wildcard = getWildcard()
   return { props: { wildcard  } };
}

// If you went to sampoder.yourdomain.com, props.wildcard would equal sampoder
```

Obviously you couldn't do this with getStaticProps(), that would be a separate feature and more complex.

**Describe alternatives you've considered**

I have considered making a custom function for this in my project, and likely will be doing this. But, I think for the future this would be great.

I'm not sure what to write here. Thanks for considering my idea and apologies if I made a typo or an inaccuracy :)

**Comment by sampoder** [comment]
If anyone is like me and wants a quick solution I used:

```javascript

export async function getServerSideProps(context) {
  let wildcard = context.req.headers.host.split(".")[0];
  wildcard =
    wildcard != "wildcardtest"
      ? wildcard != "localhost:3000"
        ? wildcard
        : process.env.TEST_WILDCARD
      : "this is the base URL!";
  return { props: { wildcard } };
}

```

to make https://hi-there.wildcardtest.innovweek.co / https://wildcardtest.innovweek.co

**Comment by SleepWalker** [comment]
There are also many requests in Discussions for such a feature. Looks like [this one](https://github.com/vercel/next.js/discussions/20116) has the best description.

As for now the only option to implement custom domains is to use SSR instead of ISR or event implement [custom server](https://nextjs.org/docs/advanced-features/custom-server) (the last option won't work with vercel deployment at all

**Comment by sampoder** [comment]
👀 Thanks for sharing @SleepWalker! They seem to be a bit different / more complex, but I certainly think they'd be great additions.

**Comment by gregg-cbs** [comment]
So according to the issue @SleepWalker posted, @Afulton11 is talking about ISR and explains the static generation hiccup.

From what I understand Afulton11 in that thread says that:
`bla.github.com/uk/clapham/1`

Will show the same generated page as:
`blabla.github.com/uk/clapham/1`

because the subdomain is not considered in the caching mechanism?
Only everything after the domain is considered, the `/uk/clapham/1`?

Im assuming with SSR I can extract the subdomain and use it in my data fetching query to retrieve the correct page, or will I face similar or other issues with subdomain wildcards?

**Comment by SleepWalker** [comment]
@gregg-cbs you can read subdomains in SSR mode, because you can access `req` from getServerProps. But in this case you'll lose static page optimizations, which you'll get for free, when using vercel cloud.
