### ISSUE TITLE
Support getServerSideProps in _app.js

### ISSUE THREAD

**Issue by cseas** [vercel/next.js#21528]
**Describe the feature you'd like to request**

There should be a way to inject data into the application from the server at fetch time. This can be easily done with an Express backend by just adding `window.key="value"` before serving an html file. But I couldn't find a way to achieve the same effect with `Next.js`.

I know `getServerSideProps` does something similar to this but sometimes we want the data to be available throughout the app so putting `getServerSideProps` in every page of the application would be too much code duplication for a simple thing.

**Describe the solution you'd like**

Support `getServerSideProps` in `_app.js` or provide some way to define code at a single place for data that will be injected by the server at fetch for every page.

**Describe alternatives you've considered**

I ran into a use case for this when I was trying to insert scripts in the `<head>` of every page in the application but the `src` of the scripts is something that should be populated by the server because it varies depending on runtime environment (test, staging, prod, etc.).

The whole explanation is on StackOverflow with a complex workaround I found to make it work:
https://stackoverflow.com/a/65890481/7435656

**Comment by dotcs** [comment]
As described in the comments in the [linked stackoverflow issue](https://stackoverflow.com/questions/65878812/insert-different-scripts-based-on-environment-in-next-js-at-runtime/65890207?noredirect=1#comment116500914_65890207) it's possible to write a custom `_document.js` that implements the access to `process.env` in the `getInitialProps` call.

```js
static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx)
    return {
        my_env: process.env.RUNTIME_ENV || 'default',
        ...initialProps,
    }
}
```

But the docs don't really tell if this behavior is stable and can be used, since [`getInitialProps` is marked as deprecated](https://nextjs.org/docs/api-reference/data-fetching/getInitialProps), but it is currently still used in the [default `_document.js` implementation](https://nextjs.org/docs/advanced-features/custom-document).

> If you're using Next.js 9.3 or newer, we recommend that you use getStaticProps or getServerSideProps instead of getInitialProps.

**Comment by balazsorban44** [comment]
@dotcs I cannot seem to find the part in the docs that says `getInitialProps` is being deprecated. Can you point me to it? I recall it is the opposite, I don't think the Next.js team will deprecate it any time soon.

**Comment by dotcs** [comment]
@balazsorban44 You're right. It's not deprecated but marked as not recommended any longer. Sorry for picking the wrong word here. I've updated my post above accordingly.
