### ISSUE TITLE
Image optimization not kicking in on the server

### ISSUE THREAD

**Issue by timoclsn** [vercel/next.js#21701]
**What version of Next.js are you using?**

10.0.6

**What version of Node.js are you using?**

15.7.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

Vercel

**Describe the Bug**

Thanks @leerob for pointing me here!

I recently ran into an issue where the image component image optimization is not kicking in on the "server" (vercel) but is working perfectly when running locally.

I added a (running) map image to my website (https://timoclasen.de/#running). It uses the [Mapbox static image API](https://docs.mapbox.com/help/how-mapbox-works/static-maps/). The API returns a png so I put the API URL in the Image component to utilize the image optimization.

Running locally it works fine – the image is served as .webp and with the right dimensions.

Runnig in production on vercel the optimization seems not to kick in and the map image is served in it's original format as a .png and in it's full dimension.

For all other images on the site image optimization works perfectly.

(I have added "api.mapbox.com" to my next.config.js)

**Expected Behavior**

I would expect to have the same behavior on the server as I have locally.

The map image should be served optimized (as .webp when supported in right dimensions).

**To Reproduce**

Add Mapbox static image API call to next.js image component like that:

```jsx
<Image
        src="https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/-122.337798,37.810550,9.67,0.00,0.00/1000x600@2x?access_token=pk.eyJ1IjoidGltb2Nsc24iLCJhIjoiY2traDV4YXRtMGI0ZjJucGd2bTB4bWpwOSJ9.cIQSkf21XbiK61DK_p8FEg"
        alt="static Mapbox map of the San Francisco bay area"
        width={1000}
        height={600}
      />
```

**Comment by timoclsn** [comment]
I have the suspicion that it has something todo with the URL length.

My Mapbox URL is over 9000 bytes long. Maybe there is some (undocumented?) length limit for image optimization on Vercel?

I will investigate further and see what the limit may be.

**Comment by timoclsn** [comment]
I found a a maximum of string length of `4,096` in the Vercel docs for some things like the rewrite URLs. Testing seems so confirm that there is the same limit for the image component URLs on Vercel.

**Comment by jathanasiou** [comment]
I am facing a similar issue in AWS Elastic Beanstalk. Local runs (either via `next dev` or `next start`) serve the images in WEBP format even though their origin has them as PNGs or JPGs.

When I access the same page after deploying the app to Beanstalk, resized images are being used but they are not server as WEBPs for some reason.

In both cases the origin is the same headless CMS host so this seems pretty weird.

**Comment by jneterer** [comment]
@timoclsn @jathanasiou I have the same issue on Netlify. Locally, my image will return optimized as `webp` however in production it returns as its original `png`. My url isn't long, no more than 250 characters, and I haven't been able to find anything that indicates what could be wrong so far.

**Comment by nikoferro** [comment]
Adding a +1 here. Having the exact same issue as @jneterer

**Comment by adamwebster** [comment]
I am also having this issue with the app I am developing. Locally everything works as expected with it converting it to webp but on the production server it serves the original files.

**Comment by imhuynq** [comment]
+1 here :(

**Comment by tolgaatam** [comment]
> @timoclsn @jathanasiou I have the same issue on Netlify. Locally, my image will return optimized as `webp` however in production it returns as its original `png`. My url isn't long, no more than 250 characters, and I haven't been able to find anything that indicates what could be wrong so far.

have you had any luck so far? I am in the exact same situation.

**Comment by tolgaatam** [comment]
@jathanasiou @jneterer @adamwebster have any of you found any solution to this problem? 10.0.8 on elastic beanstalk. no webp conversion at all :/

**Comment by tolgaatam** [comment]
An update on the issue:

I am using AWS Elastic BeanStalk behind a CloudFront CDN. NextJS version is 10.0.7, because 10.0.8 has huge image optimization performance issues.

Local dev environment was able to produce webP images whereas I would not get any optimization on my server. I made 2 changes and my issue is resolved. Either or both of them could have contributed in the solution.

1) Until v10.0.8, NextJS uses Sharp for image optimization. However, Sharp is an **`optionalDependency`** of NextJS. So, @jathanasiou , your guess might be correct, Elastic Beanstalk might be choosing to skip that install. I do not have any info whether Elastic Beanstalk does this, though. Nonetheless, I added the same version of Sharp that NextJS depends on to my project (`sharp: "0.26.3"` for `next: "10.0.7"`), in order to make sure that Elastic Beanstalk **has to** install it. After the addition, `package-lock.json` was listing sharp as not optional 👍.

2) I had already configured my CDN (CloudFront) to cache paths starting with `/_next` by forwarding query parameters and cookies. Although NextJS sets `max-age=0` for Next images (`/_next/image` endpoint), still the CDN works as if it would cache all the files, and only forward cookies and query parameters. However, NextJS decides whether to serve the image as webP vs jpg/png/svg etc. depending on the `Accept` header. With the current settings, CDN would not forward the `Accept` header to the origin, hence the origin would decide to keep the original format of the image (It may even decide not to compress the image for this reason). For that reason, I updated my CDN settings to cache based on and forward `Accept` header.

Consequently, my server ended up serving 120kb webP file, which used to be served as 820kb png file before the changes.

To stress my point once more, the second change might not work without the first one. If you are using a CDN like me, you can start by trying the 2nd method first.

**Comment by jathanasiou** [comment]
@tolgaatam  thank you for confirming this problem.

Given this finding, is the consensus that nextjs applications should pin `sharp` in their own `package.json`? I do not know of an npm command or EBS setup that specifically forces the installation of optional NPM dependencies. I do believe I read something about `npm ci` being used instead of `npm i` on EBS so that might be relevant to it missing there but being available on the localdev environment.

**Comment by joaogarin** [comment]
Hello all,

I am finding a similar issue with our apps which run on a dedicated server, locally it works fine but in production for some reason it doesn't transform to the optimized formats. Its just showing the original image format (png or jpg)

We do have a proxy to hide the backend URL and serve the images with the same domain as the frontend which on nginx looks something like this . 

```
location ~* /sites/default/files/.*\.(png|jpg|jpeg|gif|ico|svg)$ {
    proxy_set_header Host backend.examplesite.url.com
    proxy_pass https://127.0.0.1;
  }

  location ~* /system/files/.*\.(png|jpg|jpeg|gif|ico|svg)$ {
    proxy_set_header Host backend.examplesite.url.com;
    proxy_pass https://127.0.0.1;
  }
``` 

Our images config then would look like this :

```
domains: ['www.examplesite.url.com']
```

The backend runs on Drupal and locally we have no problems with the images (they do show in the optimized format) and locally we don't have this proxy so I am thinking this can have something to do with it?

**Comment by tolgaatam** [comment]
> @tolgaatam thank you for confirming this problem.
> 
> Given this finding, is the consensus that nextjs applications should pin `sharp` in their own `package.json`? I do not know of an npm command or EBS setup that specifically forces the installation of optional NPM dependencies. I do believe I read something about `npm ci` being used instead of `npm i` on EBS so that might be relevant to it missing there but being available on the localdev environment.

I would recommend pinning sharp in package.json when you don't know how the production environment executes the dependency installation 👍

**Comment by tolgaatam** [comment]
@joaogarin , while proxy passing with nginx, try setting `proxy_pass_request_headers      on;` . This will ensure that the original `Accept` header will be passed to your nextJS process. You could alternatively investigate whether your server has sharp installed or not. You could try requiring 'sharp' in a try catch block and log the result for this.

**Comment by joaogarin** [comment]
Hello, thanks I will try this and see if that helps in some way. Regarding the sharp package, I don't see it installed also locally, I am on nextjs 10.2 wasn't sharp replaced by a web assembly alternative? https://nextjs.org/blog/next-10-1#nextimage-improvements

**Comment by tolgaatam** [comment]
> Hello, thanks I will try this and see if that helps in some way. Regarding the sharp package, I don't see it installed also locally, I am on nextjs 10.2 wasn't sharp replaced by a web assembly alternative? https://nextjs.org/blog/next-10-1#nextimage-improvements

Yes, my bad. I am still using 10.0.7 because that the first version of the webassembly package was not working efficiently on 10.0.8. I guess that may not be your issue, but header forwarding might be..

**Comment by vishwanatharondekar** [comment]
In my case this was indeed `Accept` header not forwarding. I installed sharp as well and made sure the cache miss was there. With that in mind this is not really nextjs issue to fix.

**Comment by balazsorban44** [comment]
As the OP's problem has been resolved as of https://github.com/vercel/next.js/issues/21701#issuecomment-770427682 I will close this issue. If you experience similar issues, please open a new bug report with a full reproudction.
