### ISSUE TITLE
Any plan to support less?

### ISSUE THREAD

**Issue by dungmv** [vercel/next.js#22796]
### Describe the feature you'd like to request

I want to use ant design and ant design mobile with nextjs, but nextjs only has build-in css and sass.

### Describe the solution you'd like

if nextjs has build-in less support, it's very useful

### Describe alternatives you've considered

if nextjs not enough resource to add build-in less support, so you can update less plugin, it isn't updated a long time. it seems outdated

**Comment by haggen** [comment]
Hi @dungmv, I don't know Next.js' plans for LESS integration but I also needed to work with Ant Design so I took matters myself. Here's what I did:

1. Seeing that the LESS plugin was deprecated, that no de facto replacement was available and that there was several gotchas to work with Ant Design I decided to come up with my own solution;
2. Since Next.js has built-in support for SASS which is a preprocessor pretty much like LESS I thought I could start from there, so I dove into Next.js' related code wanting to replicate it for LESS.
3. I've been using this solution for the last few months and it's doing well, taking full advantage of code splitting, tree shaking and every optimization Next.js offers.
4. What I ended up with is to hook into the Webpack config generation on startup, find the rules related to SASS, make a deep copy and then tweak it to apply to LESS. Here's the code; https://gist.github.com/haggen/05dc0d9a9d1e30334ce94fcabf193fe4
