### ISSUE TITLE
Add security headers by default (with ability to override or disable)

### ISSUE THREAD

**Issue by leerob** [vercel/next.js#23993]
### Describe the feature you'd like to request

Next.js provides the ability to set custom `headers`, but you need to do the research to understand which security headers should be included to secure your site. It would be great if Next.js had sensible defaults that users could override or disable if not needed. This would provide more security out of the box.

### Describe the solution you'd like

By default, we should we some (or all) of the security headers listed in this tweet: https://twitter.com/leeerob/status/1381605537742254082.

We should also generate a least privilege CSP. This will require adding documentation as well, so folks understand why these have been added, what they do, and how to turn them off.

### Describe alternatives you've considered

Manually adding security headers in `next.config.js`. Currently, we have added documentation with some recommendation for headers to add: https://nextjs.org/docs/advanced-features/security-headers

### Resources

- https://securityheaders.com
- https://observatory.mozilla.org/
- [One community solution](https://github.com/UnlyEd/next-right-now/blob/v2-mst-aptd-at-lcz-sty/next.config.js#L112-L215)

<sub>[NEXT-1376](https://linear.app/vercel/issue/NEXT-1376/add-security-headers-by-default-with-ability-to-override-or-disable)</sub>

**Comment by adamelmore** [comment]
I mentioned in reply to the referenced tweet that Ness (https://github.com/nessjs/ness) implements a similar feature when deploying sites to AWS. For the security headers, it typically uses an origin response handler, but when deploying Next.js sites it has to use a (less ideal) viewer request, simply because Next.js already needs to leverage the origin response slot.

For the CSP generation, I wrote a [semi-naive implementation](https://github.com/nessjs/ness/blob/main/src/utils/csp.ts) using cheerio to parse the build output HTML files. Obviously, this can fall over in dynamic content scenarios, but anecdotally it's worked great for me on a dozen or so Next.js sites. I think it'd be good to get someone with more of a web security background to review, but the CSPs this code generates do pass the observatory.mozilla.org test (A+).

If bringing this functionality into Next.js is attractive and I can be helpful in any way, I'm here for it.

**Comment by leerob** [comment]
In the meantime, I've written some documentation: https://nextjs.org/docs/advanced-features/security-headers.

**Comment by trezy** [comment]
I *definitely* think we should be help developers by setting stricter default security on Next.js, but setting default CSP headers could be a tough pill for new devs to swallow if they're not already familiar with it. Here are a few scenarios to consider:

### Next.js site where all content is static and controlled by the site owner.
*Example: Software documentation site generated from Markdown files.*

This is a pretty easy one. We could go for a system like @adamelmore built for [`ness`](https://github.com/nessjs/ness) and extract URLs from static source, and everything would be gravy.

---

### Next.js site where all content is static, but includes user-generated content.
*Example: A developer blog that allows users to use images in comments on posts.*

This one gets a lot more tricky. If we extract URLs from the static source and use those to generate a CSP, we're giving the developer a false sense of security. If a static page is generated with user comments, they may include URLs to malicious (or just undesirable) URLs that should really be blocked by the CSP. If we go this route, we should *definitely* provide some kind of warning to the developer that they should enforce their own CSP rather than relying on what's provided by Next.

---

### Next.js site where some scripts are injected dynamically.
*Example: Any site that uses a tag manager (like Google Tag Manager or Adobe Launch) that injects other scripts after load.*

This is the toughest one of all. If we go the route of pulling URLs from static source, we'll only catch the tag manager URL. We won't capture *any* of the other URLs that would be injected after load on the client. This results in the developer's tag manager being broken without a clear reason why.

---

Let me be clear: none of this is to discourage Next from implementing a default CSP. Rather, I want to point out some important issues that I've considered and encountered while working on [`next-safe`](https://github.com/trezy/next-safe).

At the moment, I'm leaning more towards enabling the user to write a good CSP, rather than setting defaults that could become onboarding hurdles for developers new to Next. Admittedly, I'm biased there because I think everybody should just use my library. 😛 

That said, one of the biggest downfalls of `next-safe` is that it can't get a nonce when creating the CSP headers because the `headers()` function in `next.config.js` doesn't receive any arguments. Instead, we have to use `unsafe-inline` to avoid breaking Next all together. We can actually achieve a stronger CSP via a `<meta>` tag added to `<NextHead>`, but that has its own downsides (like MITM attacks that would inject scripts before the `<meta>` tag).

I've been meaning to dig into Next and see if there's a good way to set a nonce on all of the script tags, then pass that nonce to the `headers()` function. This would allow us to generate strong headers with strict CSP, rather than having to use `unsafe-inline` because of the inline scripts that are required.

**Comment by Vadorequest** [comment]
Well, from above comments it looks like people writing libs are into this security stuff and aim at making it easier and more manageable for other people. That's great!

Actually, it's @leerob who got me there in the first place [by his tweet](https://twitter.com/leeerob/status/1381605537742254082) 😂 

As I dived deeper into this, I bookmarked a few useful links:

- https://blog.vnaik.com/posts/web-attacks.html
- https://infosec.mozilla.org/guidelines/web_security

And eventually tried to improve Next Right Now [default headers configuration](https://github.com/UnlyEd/next-right-now/blob/v2-mst-aptd-at-lcz-sty/next.config.js#L112-L215), not only focusing on security but also on performances. (caching static assets and fonts, mostly)

I also strongly believe it's the role of the Next.js framework to push developer to do better. And it mostly starts by educating us. (which Lee does a very good job at, IMHO)

https://nextjs.org/docs/advanced-features/security-headers is a good start. 🎉  
I think there should be some warnings when starting the Next.js server locally, too. (that's what I'd look at first, way before diving into some hidden documentation gem)

What's most complicated is to find a common ground for everyone, every app has its own rules, some need to be embedded into other websites, others don't. I also tried to make it opt-in with a flag to make it easy to customise for people using NRN. I eventually decided I wouldn't dive too deep into it, to avoid over-complicating things.

The CSP -in particular- looks horrible to write/maintain/debug, when I looked at the specs I was like "I don't want to do that, it's way too complicated, too much ground to cover". I thought Next.js could help me with that (and that's what https://github.com/trezy/next-safe tries to do).

I'd love for the framework to educate us more on those topics, we don't know what we don't know, and it's impossible to know the best practices of every tech-related things out there.

**Comment by trezy** [comment]
> I'd love for the framework to educate us more on those topics, we don't know what we don't know, and it's impossible to know the best practices of every tech-related things out there.

@Vadorequest nailed it. It would be great to see Next.js replace `next-safe` with something native and opt-in, and I think the messaging and education around that is the most important piece. 😊

**Comment by adamelmore** [comment]
> Even better would be generating hashes for each of the inline scripts

I'm fairly certain this is what I'm doing with Ness, but I have the benefit of adding the headers in a CloudFront function on `viewer-response`, since Ness manages deploys.

**Comment by Vadorequest** [comment]
> [...] and I think the messaging and education around that is the most important piece. 

Exactly. Even if Next.js can't optimize everything automatically for us, it should at least warn/educate us about the important stuff. There are a few things that can be automated, but I feel like most of the work needs to be done by the developers themselves.

I'm not only focusing on security here, but best-practices in general, not matter if they're related to performances, security, UX, etc. 

For instance, I took me **two years** to figure out I wasn't caching any asset (images, scripts, fonts). I somehow assumed it was built-in, and I never looked into it by myself. (and yet again, it's one's of Lee's tweets that got me thinking about it!)

But, have I had a warning in the server console at the start of the app stating something like "No `Cache-Control` value defined in `next.config.js`, are you sure you don't have any static asset that could benefit from caching? [link]" would have educated me about it, and I'd have improved my knowledge of `Cache-Control` header and how/when to use it.

It's a very simple example, but I bet it's very common. I know Next.js has telemetry usage, maybe they have stats such as what % of projects use a `Cache-Control` header. I assume 99.5+% should use at least one `Cache-Control` directive.

**Comment by mikesherov** [comment]
Hi, just found this thread, and looking forward to ease-of-use improvements for CSP headers. Is there any reason to suggest a CSP header other than a nonce-based policy with strict-dynamic and unsafe-inline fallback? If next.js made it easy to share a nonce between header config and script and style tag generation, wouldn't a "catch-all" "good" default policy (for script and style) be:

For pages that are not SSG:

```
`Content-Security-Policy: script-src 'nonce-${nonce}' 'unsafe-inline' 'strict-dynamic';`
```

For SSG pages:
```
`Content-Security-Policy: script-src 'sha-${shaOfScript1}' 'sha-${shaOfScript2}' 'unsafe-inline' 'strict-dynamic';`
```

I'm trying to understand if there are caveats to these approaches, and if not, is there anything other than time and effort preventing this from being implemented as such?

**Comment by trezy** [comment]
> Is there any reason to suggest a CSP header other than a nonce-based policy with strict-dynamic and unsafe-inline fallback?

Yeah, the biggest issue here is that Safari doesn't yet support `strict-dynamic`, which would cause all sorts of headaches for sites with tag managers (or other post-client-load script loaders). Once Safari supports `strict-dynamic`, though, I think that's a pretty solid default.

**Comment by mikesherov** [comment]
Sorry, I should have been clear. Since `strict-dynamic` will nullify `self`, `unsafe-eval` and source lists, wouldn't this be a policy that is a safe default for non-SSG:

`script-src 'nonce-r@nd0m' 'strict-dynamic' 'unsafe-inline' https: 'self'`

As per: https://content-security-policy.com/strict-dynamic/

**Comment by shmdhussain** [comment]
How can we have different nonce value for static pages (may contain user infos loaded through apis if user logged in).

with next js, all the pages are cached either by cdn or nextjs revalidate time.

My current thinking is Do we have to generate the page for user , every time when user requests the page , with different nonce value

Is there any better solutions there?.

Strict-dynamic nonce-key is the way to go for me to implement google tag manager(bcz I need trust cascade for scripts loaded by google tag manager), but with caching this makes nonce value ineffective.

**Comment by yordis** [comment]
Hey folks, while waiting for Next on the topic, if you have some opinions and/or want to participate in figuring out good defaults, I started working on: https://github.com/straw-hat-team/next-sdk/pull/1

It is not meant to be in production **yet**, I am moving things into it still.

Check the test cases, there is a tiny abstraction on top of `headers` where you deal with class/objects to help the end-user configure the app and avoid mistakes common mistakes.

Each directive has its own sensitive default which I would like to get your feedback on it.

**Comment by nibtime** [comment]
Hi,

I thought it might be a good point now to chime into this. I created a package [`@next-safe/middleware`](https://www.npmjs.com/package/@next-safe/middleware). I had the following things in mind with this:

1.  This should be easy to set up for any hybrid NextJS app: https://web.dev/strict-csp/. That implies an automatic decision between Nonce-based (getServerSideProps) and Hash-based (getStaticProps).
2. Reporting and Report-Only mode are crucial, so CSP must always be set by header, never by `<meta>` tag.
3. minimalistic and composable configuration by objects

There is a lot more to CSPs as also implied by some comments here (like https://github.com/vercel/next.js/issues/23993#issuecomment-818626449, there are some good ideas I haven;t looked at so far) , but my main focus for the lib was `script-src`:

Allowlist CSP

Doesn't effectively protect your site. ❌
Must be highly customized. 😓

Strict CSP

Effectively protects your site. ✅
Always has the same structure. 😌 

"Always has the same structure" means it could be the same for any Next.JS app and  "Effectively protects your site." sounded like a good default to me, so I thought this could be worthwhile to do.

Because of 1. and 2., I felt it was mandatory to base the solution on Next 12 middleware. If your app hasn't a single static route and you use Nonce-based only, you can handle it in `Document.getInitialProps`, but for Hybrid, you need middleware. 

For static pages is it essentially solving this task: **How do I get the correct set of script hashes used by the static page/route about to load into the CSP response header before?**. Also, this works together with SRI, so all the scripts those hashes belong to must have the respective hash as an integrity attribute.

Can't you just a single hashed script that loads all Next scripts? Yes, but I wouldn't recommend it. There is this solution by Google that essentially does that: https://github.com/google/strict-csp. Problems:

* uses `<meta>` tag.
* loading all Next scripts with a single hashed trusted proxy loading script introduced some strange bugs (I tried this strategy, of course, it is the easiest way) that break Next in a way that it is both not a CSP violation and prevents the error from being reported to Sentry. Site crashes for end users and you'll never know about it. The best kind of bugs :) 
* doesn't handle hybrid in any way, and what are you gonna do with ISR? So there need to be Next specifics. 

For 3. there already exists `next-safe`. It allows you to configure security headers, including CSP in headers of `next.config.js`. Basically, that is already what you want to configure the stuff specific to your apps, like `connect-src` or `image-src`. So I decided to reuse that, as it already has a user base and handles this perfectly fine.

And that's how it works and what it does:

<details>
<summary><h2>Using next-safe as middleware for base CSP configuration</h2></summary>

create a file `pages/_middleware.(js|ts)` and add:
```ts
import { nextSafe } from '@next-safe/middleware';

const isDev = process.env.NODE_ENV === 'development';

// req is of type NextRequest
const middleware = nextSafe((req) => ({
  isDev
  // configure your app specific base config (CSP and other security headers)
  // https://trezy.gitbook.io/next-safe/usage/configuration
}));

export default middleware;
```

That's it, that is the same as using `next-safe` in `next.config.js` as described in its [docs](https://trezy.gitbook.io/next-safe/usage/configuration). A notable difference: You can return a different configuration based on request data. That is not possible in `next.config.js`.

</details>

<details>
<summary><h2>strict CSP for hybrid apps the easy way</h2></summary>

Then comes the uniform stuff: So ideally, if you now want a strict CSP, all you have to do, is to chain a second middleware in sequence that adds this concern, so let's do that.

Extend `pages/_middleware.(js|ts)` like so:

```ts
import { chain, nextSafe, strictDynamic } from '@next-safe/middleware';

const isDev = process.env.NODE_ENV === 'development';

const nextSafeMiddleware = nextSafe((req) => ({
  isDev
  // https://trezy.gitbook.io/next-safe/usage/configuration
}));

export default chain(nextSafeMiddleware, strictDynamic())
```

Another step to make this work is required: It has to be wired up with prerendering. For this, the package provides custom extended components for `next/document`.

Create a custom `pages/document.(js|tsx)`:

```tsx
import Document, { provideComponents } from '@next-safe/middleware/dist/document';
import { Html, Main } from 'next/document';
import React from 'react';

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return initialProps
  }

  render() {
    // those components are automagically wired with strictDynamic
    const { Head, NextScript } = provideComponents(this.props);
    return (
      <Html>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
```

That's it. You have https://web.dev/strict-csp/ implemented for your hybrid Next.JS app now. A pretty solid default :). 

There are some caveats with this, e.g. Firefox not supporting Hash-based strict CSP because of a really stupid SRI bug, Safari doesn't support it at all, some browsers might break on the presence of the directive, who knows, etc. Because of all those unknowns, I made it easily adaptable: you can configure which fallback `script-src` to use and also define "what is considered supported" yourself. I used the best defaults to my knowledge, so if those work for you, there is no need to configure anything yourself. 

Regarding custom scripts: Everything gets hashed or nonced automatically and is picked up by CSP. For inline scripts, you need to do nothing, external scripts with src attribute that are loaded before Next need to have an integrity attribute set to work with Hash-based strict CSP. Else just use scripts, preferably with `next/script`, this will make your life easiest. More on this can be found in the package README.

</details>

<details>
<summary><h2>use inline styles without <code>'unsafe-inline'</code></h2></summary>

I gave an answer with more details on this in https://github.com/vercel/next.js/discussions/18451#discussioncomment-2524733.
If you use a CSS-in-JS framework and for 3rd party components that use inline styles (e.g. `<ErrorComponent>` of Next).

Extend `pages/_middleware.(js|ts)` like so:

```ts
import { chain, nextSafe, strictDynamic, strictInlineStyles } from '@next-safe/middleware';

const isDev = process.env.NODE_ENV === 'development';

const nextSafeMiddleware = nextSafe((req) => ({
  isDev
  // https://trezy.gitbook.io/next-safe/usage/configuration
}));

export default chain(nextSafeMiddleware, strictDynamic(), strictInlineStyles())
```

This also requires the custom `pages/document.(js|tsx)` set up as stated above. For this to work, I go over `intialProps.html` with cheerio, so if you prerender unescaped dynamic user content with `dangerouslySetInnerHtml` it would be trustified. It is a tradeoff between convenience and security. This is a fundamental tradeoff I feel, I figured that out when I booted Kali Linux for the first time :). So be careful there if you use this.

</details>


## Why something like this should be a part of Next.js
I 100% agree that this should be integrated with Next.js natively, that feels like very framework-level stuff to me. I also think I am not the person who should do this. Somebody with a lot more knowledge about both web security and Next.JS prerendering should tackle it. There are certainly lots of ways how you could implement this a lot better. 

Another argument for this: it is only e2e testable and things can totally break just for the fact that there are like 10M browsers with different versions on different devices. Definitely, something where you want that Next.js has your back and not a single guy maintaining it when you are really serious about both site stability and security.

But as a PoC that shows that it can be done and so with very little configuration effort on behalf of Next.JS users I think it is quite good. I haven't found any good solution that does this, so I think it must be worth something.

And it is way better than slinging around CSP configurations by string interpolation in `next.config.js` :). So I use it myself of course, without the package I am completely on my own without guidance on the topic whatsoever and I engrained I lot of the things I learned into the lib and its documentation. 

I also keep deploying this to more sites and all have Sentry reporting, so far everything seems fine, but that is just a limited slice, I am not getting Google-level reporting data :)

Suggestion: Next.JS could start some cooperation with the author of https://web.dev/strict-csp/ (Lukas Weichselbaum) and the CSP stuff could become a part of something like https://web.dev/introducing-aurora/, which covers things like a11y and performance, but not yet web security I think.  That would be most ideal but also is wishful thinking :). I like and appreciate those efforts very much as a user of Next.JS.

## Some more resources

* Repo: https://github.com/nibtime/next-safe-middleware
* e2e test app: https://next-safe-middleware.vercel.app/
* actual site config with Sentry reporting: https://gist.github.com/nibtime/d366bccccb761431acda31a8c85a5de6
* demo project on StackBlitz: https://stackblitz.com/edit/nextjs-km7zwa

**Comment by nibtime** [comment]
Interesting: Safari supports `'strict-dynamic'` since  15.4: https://twitter.com/we1x/status/1503653726065774598

I suppose the Apple user base will update to the newest software versions faster than any other user base, so `'strict-dynamic'` will soon be the best and most secure default without question

**Comment by mrbeardad** [comment]
Has there been any progress on this issue?

**Comment by pfista** [comment]
Also wondering how we can set `script-src` to `strict-dynamic` using either nonces or hashes with Next.js/Vercel.

**Comment by leerob** [comment]
Hey folks, wanted to swing back here with an update. After digging through many different issues and discussions, I've [**made a new page in the documentation**](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy) ([PR](https://github.com/vercel/next.js/pull/54601)) specifically for Content Security Policy and nonces. This docs page: 

- Explains how to generate a `nonce` with Middleware
- Shows how to consume the `nonce` in a route with `headers()`
- Shows a complete CSP without needing to use any `unsafe`
- Shows how to ignore the `nonce` Middleware from running on prefetches / static assets

Further, we've patched some bugs and made improvements to `nonce` handling in Next.js that will be available in the latest `canary` version (for those of you time traveling from the future, upgrade to Next.js 13.5). We also updated the `with-strict-csp` example in the `examples/` folder, which is backlinked from the [new documentation page](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy).

Really hope this helps out, thank you all 🙏 I'll be closing this issue out. To continue the discussion, [please go here](https://github.com/vercel/next.js/discussions/54907). I feel this is the best solution going forward to allow folks to easily add CSP / nonces without adding additional configuration into the framework.
