### ISSUE TITLE
src attribute on <img> tag in being overwritten by unoptimized url

### ISSUE THREAD

**Issue by femesq** [vercel/next.js#24005]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

15.3.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel (cloned an example to reproduce error)

### Unoptimized image `src` is overwriting the optimized one

The attributes at line [452](
https://github.com/vercel/next.js/blob/canary/packages/next/client/image.tsx#L452)  is being overwriting the optimized `src` calculated on line [443](https://github.com/vercel/next.js/blob/canary/packages/next/client/image.tsx#L443).
Also line 454 seems pointless, since `sizes` is also returned by `generateImgAttrs`.

Before submitting and PR, wanted to know if I am missing something?

### Expected Behavior

Optimized images should be served instead.

### To Reproduce

Seens affect only SSG. To reproduce, I cloned the `image-component` example and deployed here: [image-component-henna.vercel.app/layout-intrinsic](https://image-component-henna.vercel.app/layout-intrinsic)
![image](https://user-images.githubusercontent.com/1899668/114471865-a9882080-9bc7-11eb-87c8-a61f89e6e311.png)

**Comment by JanKaifer** [comment]
Your links are not permalinks and they are not tied to a specific commit. So they are useless now. Use "copy permalink" next time 
![Screenshot from 2022-11-25 16-24-51](https://user-images.githubusercontent.com/12820484/204015620-24c0601a-c715-48c9-8563-e2cae1f69bfd.png)


We changed `next/image` a lot so it is probably already fixed in `next@13`.
If you still experience this send us a reproduction (repo we can clone) and we will reopen.
