### ISSUE TITLE
Back button not working

### ISSUE THREAD

**Issue by r6m** [vercel/next.js#24883]
### What version of Next.js are you using?

10.2

### What version of Node.js are you using?

14.15.0

### What browser are you using?

Android WebView

### What operating system are you using?

Android

### How are you deploying your application?

next string

### Describe the Bug

I have a shop and I put the link in instagram website in bio. the Issue is when I press back button on instagram android webview, it does not work and stucks for a while. sometimes closing the webview and click again on link fixes issue.
this does not happen on android chrome app or desktop, and I don't know how to debug it.

I tried `router.back()` on a button, but same problem.

Someone may have encountered this problem?

### Expected Behavior

pressing back button or `router.back()` should go to previous page on instagram android webview.

### To Reproduce
[EDITED]
I can't  reproduce the behavior now.

**Comment by rezam90** [comment]
I changed my Navbar back button click to the following:
```js
const handleBack = () => {
    // Router.back()
    window.history.go(-1)
    setTimeout(() => location.reload(), 500);
  }
```
I know this is not a good way to handle it, if it stucks on page load I reload the page and it works.
But the browser back button still not working.
Do you have any Idea how to fix it or do something like above with the browser back button too?

**Comment by curiousercreative** [comment]
On a next@11 project, I was stunned that the back button was not working this morning and I found this issue and a few other similar issues. Later this morning, I noticed that other websites had the same issue so I restarted Chromium and all websites are back to working. Obviously, this won't be the solution to many issues, but something to try as the panic sets in :)

**Comment by mehmetpekcan** [comment]
There was a problem that I facing similar. And here how I fixed:

There was a place that I called `window.history.replaceState` and I converted it to `next/router` usage. This issue causes because when we manipulating `window.history` api without Next.js acknowledge, it doesn't keep track of it and error occurs.

So if you facing similar issue try to find `window.history` usages on your codebase there should be some `history.pushState`, `history.replaceState` kind manipulations.
