### ISSUE TITLE
Trying to redirect with a 'query' type - does not remove the querystring from the redirect.

### ISSUE THREAD

**Issue by ned-kelly** [vercel/next.js#28231]
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

12.14.0

### What browser are you using?

Chrome

### What operating system are you using?

OSX

### How are you deploying your application?

serverless-next.js -- https://github.com/serverless-nextjs/serverless-next.js

### Describe the Bug

So I'm having issues redirecting from a site with a query-string - to a slug that uses a 'folder' type structure...

### Expected Behavior

The expected behaviour is that URL's such as
site.com/page.html?id=SomePage

Should be able to redirect to a structure like:
site.com/page/SomePage

### To Reproduce

**Example config in next.config.js file:**

```{
  source: '/page.html',
  has: [
    {
      type: 'query',
      key: 'id',
    },
  ],
  permanent: true,
  destination: '/page/:id*',
}```

**Comment by Andarist** [comment]
I don't think this is supported right now. If we look into how this gets resolved it looks like things are simply merged:
https://github.com/vercel/next.js/blob/6072afc83a63587065a9012222ee5a9a69159df2/packages/next/server/router.ts#L363-L368

Note that some other parts of this function are also relevant - you can read through it to understand better how the matching process works.

**Comment by ijjk** [comment]
Hi, this is currently expected as the query values from the request are passed through to the destination to ensure context like the `utm_source` and other query params aren't lost from a redirect. I'm going to close this since it isn't a bug and is currently expected. 

If you need to ensure these query values are removed for some reason you can rewrite to an API route that handles the redirect instead.

**Comment by chancegraff** [comment]
Hi @ijjk, I was reading through [the documentation for redirects](https://nextjs.org/docs/api-reference/next.config.js/redirects#header-cookie-and-query-matching) and am coming up against something a little confusing WRT the issue described here. Specifically, this section of code:

```js
      // if the source, query, and cookie are matched,
      // this redirect will be applied
      {
        source: '/specific/:path*',
        has: [
          {
            type: 'query',
            key: 'page',
            // the page value will not be available in the
            // destination since value is provided and doesn't
            // use a named capture group e.g. (?<page>home)
            value: 'home',
          },
          {
            type: 'cookie',
            key: 'authorized',
            value: 'true',
          },
        ],
        permanent: false,
        destination: '/another/:path*',
      },
```

In particular, the comment for the first option in the `has` attribute specifies that the value for `page` won't be available in the destination since the value is provided and it's not using a named capture group. I understand the comment to be saying that since the key `value` is set to `'home'`, the destination will not include the `page` query param.

I would greatly appreciate clarification. Thank you :)
