### ISSUE TITLE
Edge function / middleware error: "TypeError: Unable to parse URL" when deployed to Vercel

### ISSUE THREAD

**Issue by adrianmiles** [vercel/next.js#31208]
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

v16.10.0 (local) 

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When testing locally, the following `_middleware.ts` works perfectly:

```
export async function middleware(req: NextRequest) {
  const { pathname: redirectUrl } = req.nextUrl;
  const {  userTypeId } = req.cookies;

  if (!userTypeId || Number(userTypeId) !== UserTypeEnum.FIRST_TIME) {
    return Response.redirect("/play");
  }
  return NextResponse.next();
}
```
However, when deployed to Vercel I get the following error in my function logs:
```
TypeError: Unable to parse URL: /play
at Object.d [as handler]
at t.V
at Object.a
```

### Expected Behavior

I would expect the page to redirect or continue without the error occuring.

### To Reproduce

Create `_middleware` like above and deploy to vercel and try hit a route that the middleware is linked to

**Comment by adrianmiles** [comment]
Replacing Response with NextResponse and using rewrite instead of redirect fixed the issue for me, e.g. 
```
    return NextResponse.rewrite(`/play`);
```

**Comment by Kikobeats** [comment]
@adrianmiles What is reporting the error is the url provided should be an absolute string or URL instance.

You can achieve that by passing `nextURL` to `NextResponse.rewrite`:

```jsx
export async function middleware(req: NextRequest) {
  const url = req.nextUrl;
  const { pathname: redirectUrl } = url;
  const {  userTypeId } = req.cookies;

  if (!userTypeId || Number(userTypeId) !== UserTypeEnum.FIRST_TIME) {
    url.pathname = "/play";
    return Response.redirect(url);
  }
  return NextResponse.next();
}
```

**Comment by javivelasco** [comment]
@adrianmiles The problem here is that the implementation of `Response` for Next.js is allowing you to provide a relative URL as a redirection target, while in Vercel production this is not allowed. In this context, we must wonder what's the hostname for the redirection.

Typically one would expect the hostname to be the same where the request is being performed against, and this is information that you as a user have but the `Response` does not have on its prototype. For this reason, my recommendation would be that you change the pathname in the incoming request or you specify the host retrieving such information from the request.

What doesn't make sense for sure is that this works locally but does not work in production for Vercel. I think the best way to approach this is to make not possible for the `Response.redirect` method to be called with a relative URL. We will ship a PR changing this behaviour.

**Comment by javivelasco** [comment]
After shipping [#33410](https://github.com/vercel/next.js/pull/33410) you'll get a warning when using relative URLs in cases where it is not going to be supported in the future. This will hint you to fix the case reported in this issue and eventually we will remove the warning to instead make it fail. Since it will be a breaking change we will keep the warning for a while.
