### ISSUE TITLE
Unable to disable prefetch on `Router.push()`

### ISSUE THREAD

**Issue by dan-j** [vercel/next.js#31680]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

16

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying your application?

next start

### Describe the Bug

Calling `Router.push()` is triggering a prefetch request but the downstream service does not allow HEAD requests and is returning 405.

Similar to the `prefetch={false}` prop on the `<Link />` component, would it be possible to disable prefetching when using `Router.push()`?

### Expected Behavior

I can disable prefetching on `push()`

### To Reproduce

```ts
// Bring in routing functionality from next router hook
	const { push } = useRouter();

	// Create a function to handle logging out through Ory
	const handleLogOut = useCallback(async () => {
		const logoutUrl = await axios({
			url: `${API_URL}/self-service/logout/browser`,
			method: "get",
			headers: {
				"content-type": "application/json",
				accept: "application/json",
			},
			withCredentials: true,
		});

		push(logoutUrl.data.logout_url);
	}, [push]);
```

**Comment by tills13** [comment]
Is `logoutUrl.data.logout_url` and internal URL or a external URL? If the latter (based on "the downstream service", it seems that way), using `history` directly or even `location.href = ...` might be more appropriate.

**Comment by dan-j** [comment]
It's an 3rd party system which we host and is behind the same domain.

Our workaround is to use `window.location`, but in reality it would be good to not have to refresh the window. It essentially triggers a cookie to be deleted and the user is redirected to the login screen

**Comment by javivelasco** [comment]
@dan-j Unless I'm missing something, I think there is a side issue with this. The `HEAD` request has to happen always from client as it is what allows it to determine wether it can do a client side navigation or it must ask the server what's gonna happen next.

Imagine the case where there is an authentication middleware that checks on a cookie. Once the client loads the page, if you click on a page _protected_ by the Middleware, we must check against it if navigation is going to be successful or if it is going to be blocked. A similar case happens on rewrites where you might be linking to `/foo` but you rewrite to `/bar` so the client must pre-fetch `/bar`.

My point with this is that it is not just about pre-fetching. What we can consider to provide for these use cases is disabling client navigation for pages affected by Middleware but this might turn into a pretty bad user experience because we'd be disabling client-side navigation.

I'm afraid that allowing to disable `prefetch` on `Router.push()` will not prevent all `HEAD` requests from happening and you'll still face the same issue. Considered what I mentioned, am I correct?

**Comment by queicherius** [comment]
My use-case is slightly different, but boils down to a similar option to disable prefetch for `router.replace`.

I'm using `router.replace` to replace only the query string of the current page with some new state (in my case pagination information). Currently this causes a HEAD request that is always unnecessary because the query string is only consumed client side.

I'm using `router.replace` over manually calling `history.replaceState` because the latter does not keep `router.query` in sync.

**Comment by javivelasco** [comment]
We are working on some related updates that will fix this issue.
