### ISSUE TITLE
[ESLint] Lint failed next.config.mjs when import ESM

### ISSUE THREAD

**Issue by nghiepit** [vercel/next.js#31824]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next lint

### Describe the Bug

Rename `next.config.js` to `next.config.mjs` and import package with ESM syntax.
```ts
import {PHASE_PRODUCTION_BUILD} from 'next/constants';

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
```
Run lint `next lint`
> Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/xxx/next-12/node_modules/next/constants' imported from /xxx/next-12/next.config.mjs
Did you mean to import next-12/node_modules/next/constants.js?

![image](https://user-images.githubusercontent.com/4768095/143567214-ebd8b46f-aa9e-47a5-af53-f10a5e512510.png)

### Expected Behavior

Lint just works without error

### To Reproduce

Create `next.config.mjs` with content

```ts
import {PHASE_PRODUCTION_BUILD} from 'next/constants';

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
```
And run
`yarn lint`

**Comment by housseindjirdeh** [comment]
I don't think this is an issue with regards to the ESLint setup in Next.js. I'm noticing the same issue locally for both `next build` and `next lint` when renaming `next.config.js` to `next.config.mjs` (while having SWC disabled) - so I think this was likely fixed by https://github.com/vercel/next.js/pull/29935.

Can you confirm if you are still seeing this issue, and if yes - are you only seeing it for `next lint` and not `next build`? 

Closing this for now, but can re-open it if necessary!
