### ISSUE TITLE
React 18: "VIDEOJS: WARN: The element supplied is not included in the DOM" when nextjs project upgrade to react@rc and react-dom@rc

### ISSUE THREAD

**Issue by supriome** [vercel/next.js#32355]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

"VIDEOJS: WARN: The element supplied is not included in the DOM" when upgrade react to 18 rc in my nextjs project.

But when i use create react app to text videojs with react 18,  it don't have this issue.

I this maybe this problem of hydrateRoot(), because createRoot() project is work.

### Expected Behavior

Videojs works.

### To Reproduce

![image](https://user-images.githubusercontent.com/19944032/145510994-be0519a3-c430-4fcc-a84f-074bac7e4ee1.png)

I have a project on github, you can test by clone it. `https://github.com/supriome/nextjs-video-react18-issue`

**Comment by supriome** [comment]
And When i use `experimental concurrentFeatures ` on `next.config.js`, there is a error `error - ReferenceError: global is not defined`.

So is nextjs ready when upgrade to react 18?

![image](https://user-images.githubusercontent.com/19944032/145512195-e9cef239-e6ab-4408-bd2c-8cb8067ebce8.png)

**Comment by supriome** [comment]
#30968

**Comment by supriome** [comment]
I try all beta verion of react and rc version of react, all have this error, and can't start project.

But i try [Vercel next-rsc-demo](https://github.com/vercel/next-rsc-demo) It works. So maybe there is some error of nextjs when deal with react 18.

**Comment by huozhi** [comment]
It looks like one of your dependency (video.js) is using `global` as dependency that causes the error on edge runtime, since `global` isn't supported as a nodejs runtime keyword there.

Are you trying to just upgrade to react 18 rc without playing with the experimental SSR streaming, you don't need to enable `concurrentFeatures` flag. We're also working on a solution to try streaming SSR in node runtime.

next-rsc-demo is pretty simple without using many 3rd party dependencies so that's why it doesn't run into this error.

**Comment by huozhi** [comment]
Could you try the new experimental `runtime: 'nodejs'` option introduced in next.js 12.1.0? Should be able to resolve the issue. Checkout the [doc](https://nextjs.org/docs/advanced-features/react-18/streaming) for migration here. Thanks!
