### ISSUE TITLE
Middleware fails in v12.0.8

### ISSUE THREAD

**Issue by danr-za** [vercel/next.js#33450]
### Run `next info` (available from version 12.0.8 and up)

```sh
 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 3.1.0
      pnpm: 6.11.0
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2
```

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

After upgrading to v12.0.8 yesterday, middleware throws the following error:
```sh
error - Error: To use middleware you must provide a `hostname` and `port` to the Next.js Server
```

The setup is pretty straightforward:
* I have `basePath` and `assetPrefix` set
* `pages/users/_middleware.ts` is the location

### Expected Behavior

Should be working as same as in v12.0.7

### To Reproduce

* Create a project
* Add `_middleware.ts` file under `pages/users` for example
* Navigate to `/users`

**Comment by balazsorban44** [comment]
Hi, I could only reproduce this with a [custom server](https://nextjs.org/docs/advanced-features/custom-server) setup. Did you just forget to mention that?

**Comment by ivorpad** [comment]
@balazsorban44 For me the problem is happening on Netlify. Their package uses a custom server [netlify-plugin-nextjs@L46-L49](https://github.com/netlify/netlify-plugin-nextjs/blob/main/src/templates/getHandler.ts#L46-L49)

Next.js Custom Server docs don't say you can pass `hostname` and `port` 

<img width="710" alt="Screenshot 2022-01-19 at 16 21 01" src="https://user-images.githubusercontent.com/52452/150160587-1903ef79-f65a-4ce4-8ebe-67f2287176d9.png">

I would prefer this to be a warning rather than an error as it's breaking Next.js in Netlify.

**Comment by balazsorban44** [comment]
@danr-za since I'm unable to reproduce this without using a custom server, the following reply applies to you as well as to @ivorpad.

When using middleware we always need to have an absolute URL to handle. If you run Next.js in server mode (`dev` or `start`) we figure out the port and host automatically when instantiating the server and then pass them as options for `NextServer`. While those options are not mandatory, they are required if you are using middleware so if you are running Next.js with a custom server (which seems to be the case for Netlify here), you must pass them.

**Comment by danr-za** [comment]
I am not using a custom server.

**Comment by danr-za** [comment]
Hey @balazsorban44, the following is my `next.config.js`. 
As I mentioned in my previous comment, I do not use a custom server.

```js
const basePath = '/app'

/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
  basePath,
  assetPrefix: basePath,
  poweredByHeader: false,
  nx: { svgr: false },
  eslint: {
    ignoreDuringBuilds: true
  },
  env: {
    appBasePath: basePath
  },
  sentry: {
    disableServerWebpackPlugin: disableSentry,
    disableClientWebpackPlugin: disableSentry
  },
  async redirects() {
    return [
      {
        source: '/liveness',
        destination: '/app/api/health/liveness',
        basePath: false,
        permanent: false
      },
      {
        source: '/ready',
        destination: '/app/api/health/ready',
        basePath: false,
        permanent: false
      },
      {
        source: '/startup',
        destination: '/app/api/health/startup',
        basePath: false,
        permanent: false
      },
      {
        source: `/:path((?!${basePath.replace('/', '')}).*)`,
        destination: `${basePath}/:path*`,
        basePath: false,
        permanent: false
      }
    ]
  }
}

const plugins = withPlugins([withNx, withAssets], nextConfig)

module.exports = withSentryConfig(plugins, sentryOptions)
```

**Comment by saevarb** [comment]
I am using a custom server, and I just upgraded from 12.0.0 to 12.0.8 and I am now getting this error. Before this, the middleware worked fine without any configuration. 

This is also not documented anywhere: https://nextjs.org/docs/middleware nor does it seems like there is any information to find on how to pass the custom server this information(except the port, which is already being passed).

This is very clearly an issue. At the very least, the fact that it isn't documented and it's a regression compared to 12.0.0 behavior makes this a valid issue, so why was this issue closed @balazsorban44 ?
