### ISSUE TITLE
Docs: Add whether Next Export compatible for each feature

### ISSUE THREAD

**Issue by orvn** [vercel/next.js#33874]
### What is the improvement or update you wish to see?

> _Note: this is a general issue which applies to multiple pages in the Next.js documentation_

Currently, the Next docs _sometimes_ specify whether something works for `next export`, but sometimes they do not.

For every docs page specifying a major Next.js feature, it would be useful to see whether that feature is compatible with Next when exported as a static site.

### Is there any context that might help us understand?

Overall, I find that Next.js's docs are really explanatory, but they're written (understandably) from the standpoint of running a Next app, as a dynamic server that accepts requests and responses.

With the proliferation of static sites, a lesser-used but equally important area to document would be whether each feature is compatible with `next export`.

For instance, I was looking at the [multi-zones page](https://github.com/vercel/next.js/blob/canary/docs/advanced-features/multi-zones.md), and it makes no specific mention of use with `next build` vs `next export`.

The `next/image` page on the other hand [_does_ mention a specific caveat](https://nextjs.org/docs/api-reference/next/image#built-in-loaders) with regard to loader use in `next export`.

It would be great to have a statement about `next export` compatibility on every docs page that relates to a major feature, especially advanced features and the API reference pages.

**Comment by balazsorban44** [comment]
In addition to this [whole page](https://nextjs.org/docs/advanced-features/static-html-export), we have dedicated sections for [supported](https://nextjs.org/docs/advanced-features/static-html-export#supported-features) and [unsupported](https://nextjs.org/docs/advanced-features/static-html-export#unsupported-features) features using `next export`.

We might occasionally hint at certain features not being supported from elsewhere, but if you want to learn more about `next export` and see the whole picture, you should visit the dedicated page. Otherwise, we end up duplicating our docs, which might get out of sync.
