### ISSUE TITLE
outputStandalone + serverRuntimeConfig not working as expected

### ISSUE THREAD

**Issue by dstoyanoff** [vercel/next.js#33910]
### Run `next info` (available from version 12.0.8 and up)

 Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Tue Jan 18 13:02:08 PST 2022; root:xnu-8020.100.406.0.1~18/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 3.1.1
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.13.2

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Docker

### Describe the Bug

I have noticed the `outputStandalone` option and decide to try it for our docker deployment. It worked great and dramatically reduced the size of the image (x12). However, I stumbled upon a small problem. 

When the server.js file is generated, it automatically expands `publicRuntimeConfig` and `serverRuntimeConfig` into the conf entry of NextServer. This pretty much means that we cannot use any dynamic environment variables in docker, as all of them are only respected during build.

### Expected Behavior

next.config.js should be copied to the standalone output and its configuration should be used.

It's quite common to have a single docker image that can suit all environments with different configuration. Using the regular next build, without `outputStandalone`, this is also possible.

### To Reproduce

Add the following to next.config.js:
```
    serverRuntimeConfig: {
      API_URL: process.env.API_URL
    },
    experimental: {
      outputStandalone: true
    },
```

run `next build`

inspect `.next/standalone/server.js`- there is no API_URL entry in `serverRuntimeConfig`

**Comment by ijjk** [comment]
Hi, currently the config with `outputStandalone` is serialized and inlined in the `server.js` file generated to prevent relying on any dependencies in `next.config.js` and prevent unexpected breaking from building to deploying. If the `serverRuntimeConfig` values can not be set during build-time and need to be able to change with the `env` then you can change the inlined config in the `server.js` file to `conf: require('./path/to/next.config.js')` instead. 

Also, to better understand why `serverRuntimeConfig` is being used here, why are you storing the env variable in `serverRuntimeConfig` instead of accessing `process.env.API_URL` in the code directly where needed?

**Comment by martinezleoml** [comment]
> Also, to better understand why `serverRuntimeConfig` is being used here, why are you storing the env variable in `serverRuntimeConfig` instead of accessing `process.env.API_URL` in the code directly where needed?

Hi @ijjk!

I may have a use case for this feature: I manage multiple environments for the same Next.js project with credentials (used server-side only) that can vary between environments, for exemple backend URLs (that are proxied through /api routes) & related API secrets.

`serverRuntimeConfig` hydrated with `process.env.MY_VARIABLES` is very useful in this case as it doesn't require the whole project to be rebuilt + packaged in Docker when deploying the project to all the environments.

**Comment by ijjk** [comment]
@martinezleoml you shouldn't need to rebuild when using `process.env.MY_VARIABLES`, the only kind of env variables that should require a rebuild are `NEXT_PUBLIC_` prefixed and these should only be used for client-side values. It sounds like this can be achieved without `serverRuntimeConfig` and using the env values directly.

**Comment by ahmettahasakar** [comment]
Possibly, it can be achieved yes. And perhaps it should be a consideration for new projects. 

However, for existing projects that follow the `process.env.MY_VARIABLES` in `serverRuntimeConfig` pattern, require more flexibility. Otherwise, they either must do a major refactor or not be able to use `standalone` at all.

**Comment by ijjk** [comment]
@ahmettahasakar this shouldn't be a major refactor at all, a wrapper import could be used to replace the existing `getConfig` for example:

```js
// lib/runtime-config.js
export default function getConfig() {
  return {
    serverRuntimeConfig: {
      someConfig: process.env.SERVER_VAR
    },
    publicRuntimeConfig: {
      anotherConfig: process.env.NEXT_PUBLIC_CLIENT_VAR
    }
  }
}
```
and then do a replace on the `next/config` import and replace it with this above wrapper instead.

**Comment by ahmettahasakar** [comment]
Can you also provide an example for next/config?
Thank you

**Comment by ijjk** [comment]
@ahmettahasakar the above is an example for `next/config`, instead of importing `getConfig` from `next/config` you should import it from `lib/runtime-config` after adding the file to your project.

**Comment by ijjk** [comment]
No, the only values that will be inlined into the javascript bundles are the ones prefixed with `NEXT_PUBLIC_` the rest are only available when actually present in the env `next` is being run, see related documentation here https://nextjs.org/docs/basic-features/environment-variables

**Comment by ahmettahasakar** [comment]
I am not talking about the `NEXT_PUBLIC_` ones. 

If I use:

```
// lib/runtime-config.js
export default function getConfig() {
  return {
    serverRuntimeConfig: {
      API_KEY: process.env.API_KEY || 'SECRET_KEY'
    },
    publicRuntimeConfig: {
      anotherConfig: process.env.NEXT_PUBLIC_CLIENT_VAR
    }
  }
}
```

then `API_KEY` is embedded in public javascript files. I am attaching the screenshot from chrome inspect.
![image](https://user-images.githubusercontent.com/2559157/155026867-044607a0-1e43-46f5-9d79-8f06f20154dd.png)

However, if I store them in `next.config.js`, it is not embedded in any of the public javascript files.

**Comment by balazsorban44** [comment]
Apart from the static fallback on `SECRET_KEY`, here you can see that with his suggestion, the value of `process.env.API_KEY` is not exposed to the client

`.env.local`
```
NEXT_PUBLIC_CLIENT_VAR=foo
API_KEY=bar
```

`pages/index.js`
```js
import getConfig from "../lib/runtime-config"
...
console.log(getConfig())
...
```

![image](https://user-images.githubusercontent.com/18369201/155099684-2f172c81-e07e-4bd8-b94c-90a0ea7217f4.png)

**Comment by ahmettahasakar** [comment]
Looks like there are two problem areas. Can we reopen this issue please? It is closed right now.

**Comment by balazsorban44** [comment]
Please refer to the image above. As shown, environment variables not prefixed with `NEXT_PUBLIC_` won't be included in the client-side bundle.

The reason for the fallback showing up otherwise is because of how JavaScript works. If the first value is `undefined`, the second will be evaluated. You should not hardcode secrets in your source code.

**Comment by ahmettahasakar** [comment]
If i use next.config.js, then I dont have this problem. 

I agree with not hardcoding values into config but it happens. Especially for default server side settings. 

If we can use the standalone setting without refactoring the project, this feature will be more popular.

**Comment by balazsorban44** [comment]
The OP closed the issue themselves, indicating they were happy with the given answer already.

I believe @ijjk has given a sufficient guide on how to migrate without major refactorings in his comment https://github.com/vercel/next.js/issues/33910#issuecomment-1046352240. Removing hardcoded secrets shouldn't be considered a refactor, only adhering to best practices in the name of security. If `SECRET_KEY` is present in your source code, then this is not a Next.js-related issue. A more thorough explanation around this topic has been given here https://github.com/vercel/next.js/discussions/32874#discussioncomment-1944271

Hope that helps! :pray:

You mentioned there were two problem areas, what was the other one? Maybe it's worth opening a new issue/discussion since this has been resolved/closed by the OP?

**Comment by balazsorban44** [comment]
No problem, thanks for understanding! Don't hesitate to ask if there is anything else!
