### ISSUE TITLE
Static pages with revalidation and Next-Auth

### ISSUE THREAD

**Issue by callmegin** [vercel/next.js#34316]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 14.17.6
      npm: 6.14.15
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

  In the project we're using `Next-Auth` and in `_app.tsx` we have `getInitialProps` where we're fetching the session and some other stuff.
Now `index` has `getStaticProps`, which ideally should help with performance, since we have a lot of API calls and having them prefetched on the server would increase performance quite substantially. Issue is - that information should be seen only by authenticated users.

**ISSUE:** `index` page with `getStaticProps` generates a static page with cached user data which can be sensitive data as well.
**Example:**
1st user logs in and is not able to see authenticated status or information meant for authenticated user until `revalidate` period ends. After that - authenticated status is visible if page is refreshed.
2nd user (in this case new private tab or another browser) is immediately authenticated as 1st user. When refreshing after `revalidate` period has ended - user is not authenticated anymore.
After all this 1st user would be unauthenticated until the next `revalidate` period...Rinse and repeat :) 

![next auth getstaticprops](https://user-images.githubusercontent.com/70571729/153834861-654a6e35-5a5c-45d2-8f0e-dea4ea68e2ca.gif)

[`_app.tsx`](https://github.com/callmegin/next-auth-test/blob/main/pages/_app.tsx)
```js
function MyApp({ Component, pageProps, session }: AppProps & CustomProps) {
  return (
    <>
      <SessionProvider session={session}>
        <Component {...pageProps} />
      </SessionProvider>
    </>
  );
}

MyApp.getInitialProps = async (appContext: AppContext): Promise<AppInitialProps & CustomProps> => {
  const appProps = await App.getInitialProps(appContext);
  const session = (await getSession(appContext.ctx)) as Session;
  return { ...appProps, session };
};
```

[`index.tsx`](https://github.com/callmegin/next-auth-test/blob/main/pages/index.tsx)
```js
const Home: NextPage = (props) => {
  const { data: session } = useSession();
  const userName = session?.user?.name;

  const button = session ? (
    <button onClick={() => signOut()}>Sign out</button>
  ) : (
    <button onClick={() => signIn()}>Sign in</button>
  );

  let userSession = (
    <div>
      <p>You are not logged in</p>
    </div>
  );

  if (session) {
    userSession = (
      <div>
        <p>You are logged in as: {userName}</p>
      </div>
    );
  }

  return (
    <div>
      {button}
      {userSession}

      <div>from getStaticProps: {(props as any).timestamp}</div>
      <div>client: {new Date().toISOString()}</div>
    </div>
  );
};

export async function getStaticProps() {
  return {
    props: {
      timestamp: new Date().toISOString(),
    },
    revalidate: 1,
  };
}
...
```

### Expected Behavior

After signing in, user shouldn't be required to refresh the page to start seeing data meant for authenticated users.
The next user shouldn't be be able to see previous users` data.

### To Reproduce

Clone my repo : https://github.com/callmegin/next-auth-test 

**BUILD BEFORE TESTING**

**Comment by balazsorban44** [comment]
Hi, NextAuth.js maintainer here.

```js
MyApp.getInitialProps = async (appContext: AppContext): Promise<AppInitialProps & CustomProps> => {
  const appProps = await App.getInitialProps(appContext);

  const session = (await getSession(appContext.ctx)) as Session;
  return { ...appProps, session };
};
```

This code together with `getStaticProps` on your `index` page has a few issues.

You instruct Next.js to invoke a session call that together with the getStaticProps call will generate a static version of the site, including your credentials. (You can even observe this at build-time when a `[next-auth][error][CLIENT_FETCH_ERROR]` error will show up in your logs)

To mitigate the issue, you have a few options:

1. NextAuth.js recently introduced Middleware. Using that, you can lock down your whole site with a single line:
```js
export { default } from "next-auth/middleware" Slightly tweaking your code
```

See the [docs page](https://next-auth.js.org/configuration/nextjs#middleware) for more information.

2. use `getServerSideProps`: Fetching the user data _must_ happen dynamically, to avoid caching sensitive information. Instead of `getInitialProps` + `getStaticSideProps`, you can simply add the following to your desired pages:
```js
export async function getServerSideProps(ctx) {
  return {
    props: { session: await getSession(ctx)}
  }
}
```
If you think it's tedious to add this to several pages, you can define this function in a shared location and add only this to the pages:

```js
export { getServerSideProps } from "shared"
```

NOTE: The only gain with using getServerSideProps is to avoid a flash of content. With a nice loading UI, this can be mitigated, preserving the static nature of your site, while waiting for the user to be authenticated.

You can find similar suggestions in the official Next.js documentation on authentication: https://nextjs.org/docs/authentication#authenticating-statically-generated-pages
