### ISSUE TITLE
Tree-shaking fails for different imports from the same file across multiple routes

### ISSUE THREAD

**Issue by joyt** [vercel/next.js#34559]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
> next info

/bin/sh: pnpm: command not found

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 19.6.0: Tue Oct 12 18:34:05 PDT 2021; root:xnu-6153.141.43~1/RELEASE_X86_64
    Binaries:
      Node: 12.22.9
      npm: 8.3.1
      Yarn: 1.22.5
      pnpm: N/A
    Relevant packages:
      next: 12.0.11-canary.21
      react: 17.0.2
      react-dom: 17.0.2
```

### Describe the Bug

When importing from the same file across multiple routes, the NextJS output bundle for those routes **includes all the code from the file that is used by any route, regardless of whether it is needed for a particular route**. The imported code is clearly tree-shakable / side-effect free. Note that unnecessary code is omitted from all routes correctly if _none_ of the routes import it.

### Expected Behavior

I expect the output bundle for a specific route to omit unnecessary code that is only used by a different route.

In the below example, the JS bundle for the `/test` route should not have "string2".

### To Reproduce

Example:
```ts
// strings.ts - shared utility file
export const STRING1 = "string1";
export const STRING2 = "string2";

// pages/test.tsx
import { STRING1 } from '../strings';
...

// pages/test2.tsx
import { STRING2 } from '../strings';
...

// -> JS bundle for /test route includes both "string1" and "string2" definitions
```

Minimal repro example repository: https://github.com/joyt/nextjs-tree-shake-fail

**Comment by sokra** [comment]
That's currently a limitation of webpack. Improving that would require some move advanced code transformation/optimizations which can't be easily implemented.

The reason behind this is that there can only be a single variant of the module `strings.ts` in all pages, since multiple pages can be loaded together at runtime (you can navigate from page `test` to `test2` at runtime on client side, which will load both).

It's not possible to duplicate a module and tree shake it in different ways when they can be potentially loaded at the same time. A module could potentially include state (even while that is not the case here) which would be illegal to duplicate.

There are some workarounds to that.

The easiest way is to put each string in a separate file.

Another way it to use reexports for a side-effect-free flagged file.

``` js
// string1.ts
export const STRING1 = "string1";

// string2.ts
export const STRING2 = "string2";

// strings.ts - shared utility file
export { STRING1 } from "./string1.ts";
export { STRING2 } from "./string2.ts";

// package.json
{
  "sideEffects": false
}

// pages/test.tsx
import { STRING1 } from '../strings';
...

// pages/test2.tsx
import { STRING2 } from '../strings';
```

**Comment by balazsorban44** [comment]
Closing as an answer was given above. :+1:

**Comment by joyt** [comment]
Ok, thanks for the detailed explanation @balazsorban44.

Do you happen to know if webpack is planning to work on improving this / if there's an issue tracking it? Feels like logically it should be possible to recognize when pieces of code are totally independent even if they happen to be in the same file (or using `@__PURE__` annotations) and treat them accordingly - this is the case for a lot of utility functions.
