### ISSUE TITLE
Middleware does not take rewrites into account

### ISSUE THREAD

**Issue by cvolant** [vercel/next.js#35566]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #40-Ubuntu SMP Mon Mar 7 08:03:10 UTC 2022
    Binaries:
      Node: 14.17.0
      npm: 6.14.13
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.17
      react: 17.0.2
      react-dom: 17.0.2

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

When using rewrites, the middleware dedicated to the destination page is not executed: the middleware dedicated to the source page is executed instead, if it exists.

```
/pages
├ ...
├ /news
| ├ _middelware
| └ [...slug]
├ /blog
| └ _middelware
├ ...
```
And in next.config.js:
```js
  // ...
  async rewrites() {
    return [
      {
        source: '/blog/:slug*',
        destination: '/news/:slug*',
      },
    ]
  },
  // ...
```
In this case, visiting `/blog/something` display the `/news/[...slug]` page with the `{ slug: 'something' }` query, but the associated `/news/_middleware` is not executed. Instead the `/blog/_middleware` (associated with no pages: `/pages/blog` does not contain any) is executed.

### Expected Behavior

I expect the _middleware associated with the rewrite destination page to be executed and not the one associated with a hypothetical source page.

### To Reproduce

Here is a minimal reproduction: https://github.com/cvolant/next-middleware-rewrite-issue

Reproduction steps are described in the readme file.

**Comment by srikanthkh** [comment]
Facing the same issue. @cvolant did you find any workarounds?

**Comment by cvolant** [comment]
@srikanthkh I merely added a folder with the same name as the rewritten route and put my middleware in it...

**Comment by tbgse** [comment]
We're facing the same issue as well, can confirm that the workaround proposed by @cvolant works (creating an extra folder for the original path with the same middleware) but that's super wonky 🤕

**Comment by keslert** [comment]
Ran into this issue today. I want to a/b test my homepage using middleware to choose which page to show. I don't want to add middleware to /pages/_middleware because I don't want to trigger an edge function for every single page request.

// next.config.js
async rewrites() {
    return {
      beforeFiles: [
        { source: "/", destination: "/homepage" },
      ],
  }
}
// /homepage/_middleware.ts
import { NextRequest, NextResponse } from "next/server";

const COOKIE_NAME = "homepage-version";

const MARKETING_BUCKETS = ["og", "a"] as const;
const getBucket = () =>
  MARKETING_BUCKETS[Math.floor(Math.random() * MARKETING_BUCKETS.length)];

export function middleware(req: NextRequest) {
  const bucket = req.cookies[COOKIE_NAME] || getBucket();
  const res = NextResponse.rewrite(`/homepage/${bucket}`);

  if (!req.cookies[COOKIE_NAME]) {
    res.cookie(COOKIE_NAME, bucket)
  }

  return res;
}

**Comment by javivelasco** [comment]
In the most recent canary we revamped how Middleware plays with configuration rewrites. As of this new version we will execute middleware **before** any configuration rewrites which means that if you have a configuration rewrite that points from `A` to `B` and there is a middleware, it will see the request going to `A` but not the final destination `B`.

To overcome this use case you can simply move the rewrite from configuration to the middleware and then execute the behaviour you want in there. I'm going to close the issue as the way it works currently in canary is how we expected it to work but of course feedback is more than welcome.

Feel free to open a new issue to drop feedback if you feel it doesn't make sense 🙏 
Thanks for reporting :)
