### ISSUE TITLE
How do I disable images.domains

### ISSUE THREAD

**Issue by sgehrman** [vercel/next.js#35828]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

wat?

### What browser are you using? (if relevant)

no idea

### How are you deploying your application? (if relevant)

who cares

### Describe the Bug

You guys added this ridiculous images.domains thing.

How do I remove it?

### Expected Behavior

should work normally, not hipster shit.

### To Reproduce

drink soy lattes and be a hipster.

**Comment by balazsorban44** [comment]
Please have a read of our code of conduct before posting. https://github.com/vercel/next.js/blob/canary/CODE_OF_CONDUCT.md

From your description, it's not clear what you are trying to achieve, so I'm going to close this. If you have project specific question, you can open a discussion, otherwise create a new issue with a reproduction. Thanks
