### ISSUE TITLE
Error during server rendering renders blank screen instead of 500 page or error boundary

### ISSUE THREAD

**Issue by flybayer** [vercel/next.js#36634]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
Binaries:
  Node: 16.14.2
  npm: 8.1.4
  Yarn: 1.22.1
  pnpm: 6.32.4
Relevant packages:
  next: 12.1.6-canary.16
  react: 18.1.0
  react-dom: 18.1.0
```

### Describe the Bug

An error thrown during component rendering on the server is not working correctly. Instead of rendering the Next.js 500 page or an errorboundary, **the page is completely blank.**

### Expected Behavior

During server rendering:
- Throwing an error in component without an ErrorBoundary should render the default Next.js 500 page
- Throwing an error in component as a child of an ErrorBoundary should render the ErrorBoundary

#### Runable reproduction: https://codesandbox.io/s/interesting-sanderson-lf1ksq?file=/pages/index.js

```tsx
import { ErrorBoundary } from "react-error-boundary";

function Thing() {
  throw new Error("I'm broken");
}

export default function IndexPage() {
  return (
    <div>
      <p>Next.js Example</p>
      <ErrorBoundary FallbackComponent={() => "Caught by Error Boundary"}>
        <Thing />
      </ErrorBoundary>
    </div>
  );
}
```

This next.js page will render a blank white screen.

**Comment by JanKaifer** [comment]
You probably know more about this than I do, but If I understand it correctly:
- Error boundary is not supported on the server, so that should be ignored
- We should throw 500 when server render fails and we do now in `next@13`: https://codesandbox.io/p/sandbox/nervous-sutherland-wgyutn?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A16%2C%22endLineNumber%22%3A24%2C%22startColumn%22%3A16%2C%22startLineNumber%22%3A24%7D%5D
