### ISSUE TITLE
[BUG] ImageComponent does not work when combine `trailingSlash` and `basePath`

### ISSUE THREAD

**Issue by raulfdm** [vercel/next.js#36681]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.2
      npm: 7.24.2
      Yarn: 1.22.17
      pnpm: 6.27.1
    Relevant packages:
      next: 12.1.7-canary.1
      react: 17.0.2
      react-dom: 17.0.2
```

### What browser are you using? (if relevant)

Microsoft Edge Version 101.0.1210.32 (Official build) (arm64)

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

When we combine `basePath` with `trailingSlash`, the `next/image` component does not applies the correct `src` and `srcSet`.

It always generates `/_next/...` instead `/<base-path>/_next/...`.

That leads to images not loading properly.

### Expected Behavior

Add the `basePath` into the generated `src` and `srcSets` so the image can be loaded properly.

### To Reproduce

1. clone this project: https://github.com/raulfdm/next-basepath-trailing-image-bug
3. install the dependencies `npm install`
4. run the server `npm run dev`
5. open the app at [`http://localhost:3001/docs/`](http://localhost:3001/docs/)
6. see the image component failing
7. press the button that adds the base path
8. the image should be properly displayed

If you run `npm build && npm start`, the image will still be broken.

**Comment by bigsml** [comment]
could temporary resolve the problem by adding following to file next.config.js

```
  images: {
    path: "/<base-path>/_next/image",
  },
```

**Comment by styfle** [comment]
Looks like the order of these two if statements needs to be flipped:

https://github.com/vercel/next.js/blob/1f68a5df526cc8085fa83ba2781cfa8ce28189f6/packages/next/server/config.ts#L398-L410

**Comment by PGuimarais** [comment]
> Looks like the order of these two if statements needs to be flipped:
> 
> https://github.com/vercel/next.js/blob/1f68a5df526cc8085fa83ba2781cfa8ce28189f6/packages/next/server/config.ts#L398-L410

Yep. After patching the file images are now working. Thanks @styfle

**Comment by fbarrailla** [comment]
The issue is still happening with `next@12.3.1`.

See the reproduction here:
- [CodeSandbox](https://codesandbox.io/p/github/fbarrailla/next-image-issue/draft/exciting-breeze)
- [Repository](https://github.com/fbarrailla/next-image-issue)

**Comment by nmalyarsky** [comment]
That's actually not the problem with the `trailingSlash` per se. It is caused by the `images` property being explicitly declared in your config file. Without that declaration `images` variable in `server/config.ts` is in fact the very same object in memory as the `imageConfigDefault` one. So no matter what changes are made to the `path` property, condition `images.path === imageConfigDefault.path` on line 408 always passes. 

It stops working in case of custom `images` config, because in that scenario `imageConfigDefault` is left intact (i.e. its `path` has a constant value of `/_next/image`) and `images` object mutates (i.e. `path` changes to `/_next/image/` due to `trailingSlash` option presence).
