### ISSUE TITLE
Ignore type errors in node_modules

### ISSUE THREAD

**Issue by liftyourgame** [vercel/next.js#36695]
### Describe the feature you'd like to request

Can we have a way to disable typechecking in node_modules or even better have a list of modules to ignore type issues for?

As I understand it ignoreBuildErrors ignores all type errors. I want my code checked but should be able to trust modules to work.

I've been having trouble using the 'square' module for taking card payments because of a minor type mismatch between that module and one of its own dependencies.

### Describe the solution you'd like

Add new options to next.config.ts:

ignoreTypeErrorsInDependencies: true    // ignores all of node_modules
ignoreTypeErrorsInDependencies:['square']    // ignores all type errors of a list of dependencies

### Describe alternatives you've considered

Use ignoreBuildErrors == false and just look for type errors in my IDE.

**Comment by balazsorban44** [comment]
Please see the `exclude` option in your `tsconfig.json` file: https://www.typescriptlang.org/tsconfig#exclude

`node_modules` should already be excluded though as Next.js enforces it:

https://github.com/vercel/next.js/blob/da8d1984d266c1d00e8186268ec14ba5415ef53d/packages/next/lib/typescript/writeConfigurationDefaults.ts#L169-L174

**Comment by liftyourgame** [comment]
tsconfig.js does exclude node_modules but as you say nextjs enforces this anyway.

So why is the type-checking phase giving me errors on file in node_modules? @balazsorban44

**Comment by balazsorban44** [comment]
Do you have a reproduction?

**Comment by liftyourgame** [comment]
Nope. Switching to Remix which doesn’t have this problem. Please close.

**Comment by balazsorban44** [comment]
I tried to create a minimal reproduction from what I could gather, but I could not reproduce the problem you were having. See: https://github.com/balazsorban44/36695

You can see that running `npm build` will succeed, even when the `square` package is present in `node_modules`, containing the type errors. This should work, even if you forcefully removed the `node_modules` entry from your `tsconfig.json`'s `exports` field, because Next.js will re-apply it on the next build.

Running `npm build:tsc` (that simply uses `tsc` for building) on the other hand does not verify your configuration and you can circumvent excluding the `node_modules` from type checking.

See: https://github.com/balazsorban44/36695/blob/d46d56747ad350674dd8a955cdb7d4aeedd94615/tsconfig.tsc.json#L26

If you can provide a reproduction that has the issue with `next build`, we are happy to investigate further. :+1:

**Comment by liftyourgame** [comment]
Thanks for your efforts. npm 'square' are looking at the type mismatch issue in their module.

**Comment by balazsorban44** [comment]
No problem. Just wanted to clarify that the issue here isn't Next.js, as mentioned `node_modules` is already excluded, so I just wanted to understand how you were getting the mentioned issue.

**Comment by liftyourgame** [comment]
calling npm run build.  not npm build:tsc
same error on node 14 and 16

**Comment by liftyourgame** [comment]
Happy to share my project privately if you like on Gitlab

**Comment by balazsorban44** [comment]
Please do.

**Comment by liftyourgame** [comment]
What's your gitlab handle?

**Comment by balazsorban44** [comment]
https://gitlab.com/balazsorban
