### ISSUE TITLE
Dynamic route folder, _middleware did not redirect (this page isn’t working)

### ISSUE THREAD

**Issue by xkid1** [vercel/next.js#37112]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Please see attached picture for your reference

![image](https://user-images.githubusercontent.com/22137536/169772011-0f58e111-7ba9-490b-99e6-a7793ce47b7f.png)

![image](https://user-images.githubusercontent.com/22137536/169772299-6eca160d-a9a0-4e3f-a02d-defdb50c0d7f.png)

### What browser are you using? (if relevant)

Chrome v100

### How are you deploying your application? (if relevant)

in development

### Describe the Bug

I'm checking if has a cookie, if undefined  I would redirect to custom url base on the user empty. Example if the user directly access  the **http://localhost:3000/cutom-url**, if no cookies i will  redirect  to **http://localhost:3000/cutom-url/auth**

attached picture for reference 

![image](https://user-images.githubusercontent.com/22137536/169772569-97e9a910-20f3-4fdf-acf7-e9c8cf8139b9.png)

![image](https://user-images.githubusercontent.com/22137536/169773419-207e5dae-003b-4c24-83de-73cfeb4b096f.png)

### Expected Behavior

Expected Behavior* attached picture

![image](https://user-images.githubusercontent.com/22137536/169773658-8176be92-67c3-49fa-ab71-d2dc70151a94.png)

### To Reproduce

![image](https://user-images.githubusercontent.com/22137536/169773871-c50ba8b3-e90d-46d2-9674-6bae92a15b30.png)

**Comment by xkid1** [comment]
Thanks for the info, so my config from middleware won't work. is there any solution? so I can redirect from dynamic route folder.

**Comment by javivelasco** [comment]
This used to happen due to middleware nesting. In the previous DX we were creating a mental link between a page being rendered and a middleware being executed. In practice this is quite hard because pages with dynamic segments would render or not depending on if pages with static segments or static files existed. What we were doing was to infer a matcher for the middleware according to the location where it was defined which is actually decoupled from its sibling page render. In other words, in this model executing middleware depends on pages being rendered which actually happens _after_ we executed middleware.

We've deprecated this model in favour of a single root middleware where you can define the matcher. So instead of executing it when certain page renders you can simply define a generic matcher that would explicitly express when it should be executed. This also solves issues like nesting, execution order and so on.

Since this is something that can't happen in the latest canary I'm going to close this issue. I hope it is useful.
Thanks for reporting!
