### ISSUE TITLE
Cookies Set In Middleware Not Available on getServerSideProps on First Load

### ISSUE THREAD

**Issue by sdoironkcdus** [vercel/next.js#37761]
### Verify canary release

- [ ] I verified that the issue exists in Next.js canary release
- NOTE:  This issue was untestable in canary.  In canary, setting cookies in the `middleware` was not possible via the `NextResponse` class (which is what this issue is about) so I'm unable to confirm whether this issue is present in that version.

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: N/A
      pnpm: 7.2.0
    Relevant packages:
      next: 12.1.5
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

Chrome 102.0.5005.115

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

When setting a cookie in the `_middleware` using the `NextResponse` class (or any other way of setting a cookie in the middleware), after the middleware has responded and a page that uses `getServerSideProps` has loaded, the cookie will not be available on the `req.cookies` object of the `getServerSideProps`.  However, after you refresh the page it will be available.  This problem persists regardless of the `sameSite` or `httpOnly` property values when setting the cookie as well.

### Expected Behavior

Cookies that are created in the `_middleware` will be available on a page's `getServerSideProps` `req.cookies` object after the middleware completes.

### To Reproduce

1.  Create basic Next.js app with React (make sure it's using Next.js version 12.1.5, using 12.1.7 canary won't work, the cookie functionality seems to be entirely non-functional on that version)
2.  Create a `_middleware.js` file in the `pages` folder (if one doesn't already exist)
3.  Add basic logic to the `_middleware` file that will set a cookie using Next.js's `NextResponse` class (or just copy/paste the code provided below)

```
import { NextResponse } from 'next/server'

export async function middleware(req, ev) {
    return NextResponse.next().cookie('test', 'test', {
        path: '/',
        maxAge: 1000 * 60 * 1, // 1000 milliseconds * 60 seconds = 1 minute
        httpOnly: false,
        sameSite: false
    })
}
```
4.  Create a `test.js` page with the following code:
```
const Test = () => {
    return <p>test</p>
}

export const getServerSideProps = async ({ req, res }) => {
    console.log({ cookies: req.cookies })
    return {
        props: {}
    }
}

export default Test
```
5.  Run your `localhost`
6.  Go directly to the `http://localhost:3000/test` page
7.  Observe the `cookies` log in the terminal and how it **does not** contain the `test` cookie
8.  Look into the Google Chrome dev tools in the `Application` tab, open the cookies for localhost, and see that the `test` cookie does exist, but did not exist on the `req.cookies` object of the `getServerSideProps`
9.  Refresh the page and observe the `cookies` log in the terminal and how it **does** now contain the `test` cookie

The bug as explained is that the `test` cookie should be available at step 8, not at step 9 after the page has been refreshed.  The purpose for this is so that the middleware can set cookies so they can be used with data fetching on `getServerSideProps` of a page before the client side loads (so data can be passed from getServerSideProps as props to the client)

**Comment by thoriqaulia163** [comment]
I'm facing same issue here, middleware should be run first, before any page run, but turns out getserverside run before or intime with the middleware. After few debugging I found out that "async" function on middleware and getserversideprops affect serverside runtime. So while middleware still running and hasn't return response, the getserverside running and try to get the cookie which wasn't set by middleware. 

Until now I don't have fix solution for this but I do have couple temporary solution. 

1. redirect page if the cookie you want to get in getserversideprops hasn't set, so the page will reload and middleware set the cookie.

export const getServerSideProps =async(context) => {
    const mycookie = cookie.parse(
      (context.req && context.req.headers.cookie) || ""
    );

    let test = mycookie.test;
  

    if(test){
      return { props: {test} }
    }
    else{
      return { redirect: {permanent: false ,destination: "<THIS PAGE PATH>"} }
    }
  }

PROS:
+ easy to implement
CONS:
- you must make sure if the cookie will set, otherwise it will gos to infinite redirect loop
- redundant set cookie (you set cookie twice for a page)

2. give default cookie value in getserversideprops, if the cookie hasn't set.

PROS:
+ easy to implement

CONS:
- if your cookie value is dynamic (example: you get cookie value from fetch api) you need to implement the fetch api in getserversideprops which will make your code much longer. But you can do whatever fetch api you do in middleware to getserversideprops since both of them is running on server side.

3. Dont Use async on middleware and getserverside props

PROS:
+ you need no change just delete "async" word.

CONS:
- you cannot do any asnychronous things in both middleware and getserversideprops (example: "fetch api" which I believe you want to use) , or you may do but with a lot of trick and base on condition.


Sorry for my bad english and explanation, I hope this will help a little bit until there is a better or fix solution

**Comment by sdoironkcdus** [comment]
@thoriqaulia163 Thanks for your reply.  It's good to hear I'm not the only one experiencing this.  Also that is a good callout on the `async` affecting how/when the middleware and SSR pages run; I was unaware of this being the case

**Comment by javivelasco** [comment]
Hi there! I've been looking into this and I think the behaviour I can see in `canary` is expected. 

When it comes to the OP the first important thing to note is that when you set a cookie in middleware you are doing so on the `response`. When there is a first request, you are reading `request` from `gSSP` and the original request had no cookie so it is expected that it gets an empty value as middleware effects would not alter the request but the response. If you visit the page again when you already have the cookie, then `gSSP` will receive the cookie as the original _request_ included. I see that probably in your use case it would make sense that you add a property to the `request` so `gSSP` would be able to access such property. This is a different feature we are considering to include soon but right now it works as intended.

@thoriqaulia163 Middleware runs before anything but configuration redirects and configuration headers. It is blocking until you respond so if you run await a `fetch` we won't keep routing until it resolves. If you need to do some async work that is non blocking you should use `context.waitUntil` to ensure the middleware doesn't die before finishing its job.

I don't see work that we need to do here as it works as expected. Maybe to fully support your use case we'd need to add a feature to allow updating the request parameters. I'm pretty sure we will ship it but right now it is not modelled. Thanks a lot for reporting 🙏
