### ISSUE TITLE
12.1.7-canary.40 Edge middleware NextResponse.rewrite cause endless rewrite loop

### ISSUE THREAD

**Issue by maintao** [vercel/next.js#37804]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 8.9.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.41
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

In root middleware.ts, use `NextResponse.rewrite` to my own subpage, it goto subpage first, and then auto redirect to index. If no index exists, it will run into an endless redirect loop. That's horrible.

This issue exists in `next@12.1.7-canary.41`.
`next@12.1.7-canary.40` doesn't have this issue.

### Expected Behavior

Rewrite to target page.

### Link to reproduction

https://reproduce-issue-endless-rewrite.vercel.app

### To Reproduce

Complete code:
https://github.com/maintao/reproduce-issue-endless-rewrite

**Comment by maintao** [comment]
This issue still exists in `next@12.1.7-canary.42`.
Hope fix soon. @ijjk Thanks.

**Comment by ijjk** [comment]
@maintao the endless redirect guard is fixed in the latest canary as can be seen on [this deployment](https://reproduce-issue-endless-rewrite-9zlx58xie-ijjk-testing.vercel.app/) which triggers the invariant error. The invariant error can be fixed by updating the matcher to handle `/index` which is currently present when fetching the data on the client: 

```js
export const config = {
  matcher: "/(index)?",
};
```

Updated deployment the above matcher fixing the invariant https://reproduce-issue-endless-rewrite-gwcirw4x6-ijjk-testing.vercel.app/
