### ISSUE TITLE
Example works only with default port 3000

### ISSUE THREAD

**Issue by damianobarbati** [vercel/next.js#37952]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.45
      react: 17.0.2
      react-dom: 17.0.2
```

### Which example does this report relate to?

with-playwright-app

### How are you deploying your application? (if relevant)

yarn test:e2e

### Describe the Bug

Playwright fails because it fails to detect when webserver starts.

### Expected Behavior

Playwright should succeed.

### To Reproduce

Set the port to 80 instead of leaving the default 3000, changing these 2 lines:
- `"dev": "next dev -p 80"` here <https://github.com/vercel/next.js/blob/canary/examples/with-playwright/package.json#L4>
- `3000` here <https://github.com/vercel/next.js/blob/canary/examples/with-playwright/playwright.config.ts#L19>

Run `DEBUG=pw:webserver yarn test:e2e`.

It fails because the `WebServer available event` is never fired.

**Comment by thebergamo** [comment]
In general I believe this has something to do with Playwright other than Next.js itself. 
After some testing I manage to make it running, but instead of specifying port itself you should use `use.baseURL` and `webServer.url` that would help to make it running without issues.

Please take a look in this file from my fork: https://github.com/vercel/next.js/blob/657663770e6eb0bbeab3b1a771c53519378f386e/examples/with-playwright/playwright.config.ts

This works correctly.
