### ISSUE TITLE
Docs: On Demand Revalidation example is not working

### ISSUE THREAD

**Issue by vladnicula** [vercel/next.js#38031]
### What is the improvement or update you wish to see?

https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#using-on-demand-revalidation states that we should have an API function which in the end will call `await res.revalidate('/path-to-revalidate')`.

`res.revalidate` does not exist in nextjs (at least not in a clean install of nextjs 12.1.6). I had to use `res.unstable_revalidate`.

### Is there any context that might help us understand?

`res.revalidate` is not available in a clean install of nextjs 12.1.6

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#using-on-demand-revalidation

**Comment by balazsorban44** [comment]
Hi, this is due to the fact that the documentation is currently pointing to the `canary` release, preparing for our next release. See: https://github.com/vercel/next.js/pull/37955

If you are on `12.1.6`, you can keep using `unstable_revalidate`, but `canary` and the next stable release will bump this feature into stable.
