### ISSUE TITLE
Server-side rendering not working on production in next@12.1.6

### ISSUE THREAD

**Issue by sc-addypathania** [vercel/next.js#38176]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
Platform: Windows
Arch: x64
Version: 20H2
Binaries:
Node: v14.17.6
npm: 8.1.3
Yarn: 1.22.17
Relevant packages:
next: 12.1.6
react: 17.0.2
react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome 102.0.5005.115

### How are you deploying your application? (if relevant)

next build

### Describe the Bug

When using server-side rendering with next@12.1.6, the context doesn't get passed down to the children component.
When trying to log the context value, the context gets logged on the client-side but not on the server-side.

NOTE: This issue cannot be reproduced with other versions of nextjs and is only specific to 12.1.6.
The issue also gets resolved when upgrading react to the latest version i.e. 18.2.0.
This works with` next dev` but fails with `next build` && `next start`.

### Expected Behavior

The context should get passed down to the children on the server-side in production.

### Link to reproduction

https://github.com/sc-addypathania/nextjs-bug-repro/tree/main

### To Reproduce

1) npm run build
2) npm run start
3) Check the console/terminal the context is coming out to be undefined whereas its getting logged correctly on the browser

**Comment by sc-addypathania** [comment]
Transferred from discussion: https://github.com/vercel/next.js/discussions/37826

**Comment by Klemensas** [comment]
Encountered the same bug, just with `next@12.2.0`. Using `react-intl` and it's [`injectIntl`](https://formatjs.io/docs/react-intl/api/#injectintl-hoc) helper results in the problematic behavior.

Can confirm latest react addresses this, but I'm not ready yet to upgrade.
Quite a nasty surprise and took a while to figure out what was happening 😞 if the fix isn't trivial  it would be nice to have it mentioned in the migration guide so others can save time

**Comment by julianobrasil** [comment]
@sc-addypathania, I haven't tested it with context, but with redux you have a similar problem. If you add the `Provider` on the `_app.js` it works if you try to update the store during the SSR on the pages. I guess we have a similar behavior with the `Context.Provider` (the updates works in the pages if you wrap `_app.js` with it and try to consume the context from components that are children of the pages)

**Comment by jcomo** [comment]
Fwiw, this seems like a pretty severe bug. As far as I can tell, in my tests, any context will be provided as undefined to consumers, meaning that this is likely going to break server-rendered pages for any apps that render components/libraries like Formik, i18n, redux, etc. with localized contexts.

It seems related to this issue: https://github.com/vercel/next.js/issues/38765 -- and the issue author may have narrowed down the root cause to this commit/PR (potentially): https://github.com/vercel/next.js/pull/36552

I was testing on 12.2.3 with React 17.0.2, and can confirm the bug still persists in that config. Downgrading to 12.1.5 fixed it for me!

The tricky part is that it will only break server-rendered pages on a full build (dev server seems to be fine), so most people won't realize the issue until a staging/prod deploy.

**Comment by jcomo** [comment]
Thank you for the quick fix @huozhi !!
