### ISSUE TITLE
Text content did not match. Server: "hello " Client: "hello 1111111111"

### ISSUE THREAD

**Issue by robertcasanova** [vercel/next.js#38290]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.13.0
      npm: 8.3.0
      Yarn: N/A
      pnpm: 7.0.0
    Relevant packages:
      next: 12.2.1-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/604.1

### Describe the Bug

On Safari Mobile version 15.5 we get the following error:

```
Text content did not match. Server: "hello " Client: "hello 1111111111"
```

This happens only with numbers > 10 digits inside a React.Fragment.

### Expected Behavior

The client and server content should match.

### Link to reproduction

https://github.com/robertcasanova/next-error-client-server-mismatch

### To Reproduce

- Clone the repo.
- Run `npm i`
- Run `npm run dev`
- Go to `http://localhost:3000` on Safari Mobile to see the error
- Go to `http://localhost:3000/works` to see the correct version (without React.Fragment)

**Comment by SukkaW** [comment]
That's really weird. It seems that the issue can only be reproduced on iOS Safari. I am able to reproduce the issue on Xcode iOS simulator:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/40715044/178483226-2688337c-b2a6-44f6-add8-fc5576bf18ec.png">

Also, the issue seems to happen only in development mode, not in production mode (`next start` is not affected).

**Comment by shuding** [comment]
@robertcasanova @SukkaW 

Because iOS Safari is trying to do something smart here ;)

<img width="1891" alt="CleanShot 2022-08-28 at 01 42 47@2x" src="https://user-images.githubusercontent.com/3676859/187051671-0c2ee8c2-c79d-4f51-bf28-596aab807fe9.png">

This isn't something Next.js or React can help I guess. You can add `<meta name="format-detection" content="telephone=no">` ([docs](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193-SW1)) to disable this behavior.

**Comment by robertcasanova** [comment]
@shuding thx a lot! Nice catch. =)
