### ISSUE TITLE
Docs: Gracefully exit/kill server

### ISSUE THREAD

**Issue by MDOR** [vercel/next.js#38714]
### What is the improvement or update you wish to see?

When using the backend server API, I would like to include some of the functionalities available in Node JS, to detect multiple signals and/or process envents.

I'm trying to trigger some hooks, on `SIGTERM`, `beforeExit`, `exit`, `unhandledRejection`, `rejectionHandled` and `uncaughtException`.

I cannot wire it into the existing functionality, as a global listener. 
I saw the documentation about a custom server, but it would be a good addition in case not available. So people will have more control to do a clean-up and/or managing exit signals. 

```js
    function exitHook(hook) {
      return function exitFn(code) {
        const msg = `${hook}: Process to exit with code ${code}`;
        try {
          const error = new Error(msg);
          triageError(error);
        } catch (e) {
          console.error(e);
        } finally {
          console.info(msg);
        }
      };
    }
 
    process.on('SIGTERM', exitHook('SIGTERM'));
    process.on('SIGINT', exitHook('SIGINT'));
    process.on('uncaughtException', exitHook('uncaughtException'));
    process.on('beforeExit', exitHook('beforeExit'));
    process.on('exit', exitHook('exit'));
  
    const unhandledRejections = new Map();
    process.on('unhandledRejection', (reason, promise) => {
      unhandledRejections.set(promise, reason);
      triageError(reason);
    });
    process.on('rejectionHandled', (promise) => {
      unhandledRejections.delete(promise);
    });  
```

### Is there any context that might help us understand?

I'm trying to improve a reporter, but I cannot wire events to `SIGTERM`, `beforeExit`, `exit`, `unhandledRejection`, `rejectionHandled` and `uncaughtException`.

This needs to be done without a custom server.

**Comment by samcx** [comment]
@MDOR Unfortunately, something like this isn't possible without a custom server.

Due to the age of this issue, I will be closing this.

Feel free to start a new conversation in our <picture data-single-emoji=":nextjs:" title=":nextjs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/nextjs/2a85d633ae594556.png" alt=":nextjs:" align="absmiddle"></picture> [Discussions](https://github.com/vercel/next.js/discussions) if you wish to continue this conversation (as a feature request?)!
