### ISSUE TITLE
Rewrites with destination `/index/` do not work in standalone mode

### ISSUE THREAD

**Issue by chrilis** [vercel/next.js#38742]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.3-canary.10
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

In `standalone` output mode rewrites with a destination of `/index/` do not work. With other destination values like `/test/` or running the app in non-standalone mode (`npm run dev` or `npm run start`) the behavior does not occur.

### Expected Behavior

The query params on the wildcard page template `[[.../slug]].js` should contain a param `slug` with the value `index` for the following urls:
-  `/`
- `/test-middleware/`.

### Link to reproduction

https://github.com/chrilis/next-standalone-rewrite

### To Reproduce

- Run `npm run build && cp -r public .next/standalone && cp -r .next/static .next/standalone/.next && node .next/standalone/server.js`
- Visit [http://localhost:3000/](http://localhost:3000/): The query should contain a param `slug` with the value `index`, but it does not.
- Visit [http://localhost:3000/test-middleware/](http://localhost:3000/test-middleware/): The query should contain a param `slug` with the value `index`, but it does not.

**Comment by balazsorban44** [comment]
This seems to be related to: https://github.com/vercel/next.js/pull/13699

Specifically this code:
https://github.com/vercel/next.js/blob/20b63e13ab2631d6043277895d373aa31a1b327c/packages/next/server/base-server.ts#L1139-L1147

`output: 'standalone'` produces a similar artifact to custom servers so this will trigger and rewrite your path which seems to be the root cause. I'll try to verify with someone else what's the expected behavior here.
