### ISSUE TITLE
styled-components' `css` prop not working via SWC transform

### ISSUE THREAD

**Issue by alebelcor** [vercel/next.js#38891]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
Binaries:
  Node: 14.19.3
  npm: 6.14.17
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 12.1.6
  react: 17.0.2
  react-dom: 17.0.2

### Describe the Bug

The [styled-components transform](https://nextjs.org/docs/advanced-features/compiler#styled-components) for SWC isn't working as expected when using the [`css` prop](https://styled-components.com/docs/api#css-prop) to add styles.

Instead of applying the styles a `css` HTML attribute is added to the element.

### Expected Behavior

When using the `css` prop in JSX I expect the styled to be applied to the rendered HTML instead of the value being passed as a prop and rendered as an HTML attribute.

### Link to reproduction

https://codesandbox.io/s/next-12-styled-components-transform-bug-t53kxi

### To Reproduce

In the CodeSandbox I have two styled components that set a different text color. Then I have two tags where I set different colors but via the `css` prop.

The styles added via the `css` prop are not applied.

**Comment by adrienrn** [comment]
Second this!

NB: It seems that this only happens when using strings and not template strings (truly hope I'm wrong because this should not make any difference unless some transpiling magic), at least, in my project that seems to be correlated.

Forking the codesandbox, I see the following behaviour.

1. Initial load of the page, works!
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/5598481/181030882-d6875a59-a96c-4744-b974-8576d875150f.png">

2. Making a change to the `css=""` element, live reload recompiles, color does **not** update:
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/5598481/181031270-9dc6bc75-8d7a-4015-a5fb-caccc57efef2.png">

3. Making a change to the `css={``}` element, live reload recompiles, color updates:
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/5598481/181032045-0b24b4e7-e973-40f1-9629-eb0eb971b9c5.png">

4. Reloading the page, both changes apply correctly:
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/5598481/181032377-7b605efb-7109-45e5-8fe4-f145fa32a4c9.png">

**Comment by alebelcor** [comment]
Looks like this was fixed in 12.2.0:

* https://github.com/vercel/next.js/pull/37861
* https://github.com/vercel/next.js/pull/37962

Closing this.

**Comment by adrienrn** [comment]
Are you certain it was fixed in v12.2.0? Your original codesandbox (and mine) seem to be using v12.2.3-canary3 and still exhibited the issue.

**Comment by alebelcor** [comment]
Yep, seems to work fine on initial load.
