### ISSUE TITLE
Scripts with async in Head are executed twice

### ISSUE THREAD

**Issue by tylerbroadway** [vercel/next.js#38942]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 14.16.1
      npm: 6.14.12
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2
```

### What browser are you using? (if relevant)

Chrome 103.0.5060.114

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Scripts in Head run twice if marked async. After the second execution, our Wistia embedded video player does not render.

### Expected Behavior

Scripts should only run once.

### Link to reproduction

https://bigcommerce.de/mojocheck/b2b-edition

### To Reproduce

• Visit the link to reproduction
• Scroll down until you see the Wistia embedded video
• Open devtools console & refresh page (may need to refresh more than once to reproduce error)
• Should see a duplicate DOM ID error (there should be 2 separate errors, as there are 2 embeds on this page)

### Screenshots
<img width="1790" alt="Screen Shot 2022-07-22 at 7 50 34 PM" src="https://user-images.githubusercontent.com/32829986/180584013-a2c9a199-95d5-4d96-b49a-decb023be657.png">

**Comment by iljamulders** [comment]
Are you using [https://nextjs.org/docs/basic-features/script](https://nextjs.org/docs/basic-features/script)?
next/script makes sure it's only loaded once.

**Comment by spreadpando** [comment]
I'm experiencing this as well. The official Next.js answer seems to be to use next/script, but that doesn't suit every use case. For instance I need to load third party scripts synchronously and before the document body renders. Because these scripts are unique to each page, I can't use next/script with `strategy=beforeInteractive` in a custom _document.js. 
There seems to be no officially supported way to do this presently in next.js that isn't bugged.
