### ISSUE TITLE
Add router.isChangingRoute bool or something similar

### ISSUE THREAD

**Issue by Zerebokep** [vercel/next.js#39202]
### Describe the feature you'd like to request

Calling router.push/replace is causing weird error messages which are hard to track down (as discussed here: https://github.com/vercel/next.js/discussions/39040#discussioncomment-3289472)

### Describe the solution you'd like

Please add something like router.isChangingRoute.

### Describe alternatives you've considered

Bypassing this issue by setting up a own state is possible, but it generates too much duplicate code.

**Comment by MrJoy** [comment]
Perhaps a more ergonomic solution would be to de-bounce calls to `router.push` / `router.replace` automatically.

It might be prudent to add both, since debouncing does beg the question of what to do if multiple calls are made that are _not_ strict duplicates of one another.  The obvious solution would be to log an error / raise an exception, so that the developer is aware of the issue and the need to address it.  In such a situation they could still potentially benefit from this attribute.

**Comment by balazsorban44** [comment]
Please see https://github.com/vercel/next.js/issues/39128#issuecomment-1198115040
