### ISSUE TITLE
Docs: Internationalized Routing

### ISSUE THREAD

**Issue by federicovezzoli** [vercel/next.js#39281]
### What is the improvement or update you wish to see?

Following the documentation it's not very clear how to make the intl routing works for the multi domain case.
I've followed the documentation but I always get sub-path routing when next/link generates the localized routes.
Is it because I'm locally? it's not clear.
Is it a bug?
Thanks a lot

### Is there any context that might help us understand?

Here is my configuration, deploying it with on netlify.
```   
locales: ['en-gb', 'es-es', 'de-de', 'fr-fr', 'it-it'],
    defaultLocale: 'it-it',
    domains: [
    {
      domain: 'xxx-it.netlify.app',
      defaultLocale: 'it-it'
    },
    {
      domain: 'xxx-en.netlify.app',
      defaultLocale: 'en-gb'
    },
    {
      domain: 'xxx-fr.netlify.app',
      defaultLocale: 'fr-fr'
    },
    {
      domain: 'xxx-de.netlify.app',
      defaultLocale: 'de-de'
    },
    {
      domain: 'xxx-es.netlify.app',
      defaultLocale: 'es-es'
    }
],
    localeDetection: false
  },
  ```

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/advanced-features/i18n-routing

**Comment by Babbili** [comment]
@federicovezzoli if you would like `localeDetection: false` in `next.config.js` file
then try to add the `locale` property to the `<Link />` component and set as `false`, then include the `locale` dynamicly in the `href` prop, see `locale` prop in [`next/link` docs](https://nextjs.org/docs/api-reference/next/link) 
```jsx
import Link from 'next/link'
// ...
<Link locale={false} href={`xxx-${locale}.netlify.app`} >
    <a>{`xxx-${locale}.netlify.app`}</a>
</Link>
```
and then you need to modify locales in `next.config.js` to match the domains given
```js
locales: ['en', 'es', 'de', 'fr', 'it'],
    defaultLocale: 'it',
    domains: [
    {
      domain: 'xxx-it.netlify.app',
      defaultLocale: 'it'
    },
    {
      domain: 'xxx-en.netlify.app',
      defaultLocale: 'en'
    },
    {
      domain: 'xxx-fr.netlify.app',
      defaultLocale: 'fr'
    },
    {
      domain: 'xxx-de.netlify.app',
      defaultLocale: 'de'
    },
    {
      domain: 'xxx-es.netlify.app',
      defaultLocale: 'es'
    }
],
    localeDetection: false
  },
```

Or if i were you i would just enable localeDetection in `next.config.js` and comment out `localeDetection: false`, (default to true)
and see how things go

**Comment by samcx** [comment]
@federicovezzoli Our docs around internationalization has updated much since this issue was last reported!

- https://nextjs.org/docs/app/building-your-application/routing/internationalization
- https://nextjs.org/docs/pages/building-your-application/routing/internationalization

If you have any more questions around internationalization with <picture data-single-emoji=":nextjs:" title=":nextjs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/nextjs/2a85d633ae594556.png" alt=":nextjs:" align="absmiddle"></picture>, feel free to create a new [bug report](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml) or a new [discussion](https://github.com/vercel/next.js/discussions).
