### ISSUE TITLE
Avif server as octet-stream

### ISSUE THREAD

**Issue by pegak** [vercel/next.js#39706]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Same problem as for Gatsby: https://github.com/gatsbyjs/gatsby/issues/31068
Or previously Remix: https://github.com/remix-run/remix/issues/3771

### What browser are you using? (if relevant)

Chrome 104, Edge 106

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Wrong mime type for AVIF image from public folder.

### Expected Behavior

Correct Content-Type, so image can be loaded.

### Link to reproduction

https://github.com/pegak/nauc-me-it - you need to have pixel density 2x, run locally and check bg-landing.avif loading :)

### To Reproduce

1. Put AVIF image into public folder.
2. Use that image (I use it from CSS as a background image).
3. Image does not work.
4. Check Network tab in Devtools.
5. Image is loaded, but with type `octet-stream`.

**Comment by SukkaW** [comment]
That's really weird.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/40715044/185431283-9ad67aab-620e-45ef-aa83-c5d41203147d.png">

I use my browser to visit the URL directly, and the response header shows `image/avif`.

**Comment by pegak** [comment]
And when you run it locally via yarn, yarn run dev? I think it is broken even when running yarn run build && yarn run start.

**Comment by SukkaW** [comment]
> And when you run it locally via yarn, yarn run dev? I think it is broken even when running yarn run build && yarn run start.

@pegak Yes. I am able to reproduce the issue in local environment.

https://github.com/vercel/next.js/blob/cc1f3b8a38645726c6ec1d9c6c843f0a200adcf0/packages/next/server/serve-static.ts#L23-L28

Next.js already implemented `.avif` handling (as a specific edge case). I will have a look at it to see what went wrong.

**Comment by SukkaW** [comment]
@pegak I have submitted a PR that will fix the issue: https://github.com/vercel/next.js/pull/39733

**Comment by pegak** [comment]
Thank you very much! I must make some time to contribute to open source community to give something back! :)

**Comment by SukkaW** [comment]
> Thank you very much! I must make some time to contribute to open source community to give something back! :)

@pegak Actually now you have a great chance to start!

Your issue is caused by an upstream package [send](https://github.com/pillarjs/send). It depends on another package [mime](https://npm.im/mime) to provide the content-type mapping.

The `mime` package has added `avif` in `mime@2.4.7`, but `send` is still using `mime@1.6.0`, hence your issue. You can submit a PR to `send` to help them update the `mime` dependency version!

A few notes:

- It seems that `send` is about to release a major version `1.0.0`, thus there might be a dedicated developing branch. If there is a dedicated branch for the upcoming `send@1.0.0`, you should create your PR toward that branch, not `master`.
- From `mime@1.6.0` to `mime@2` is a major version bump, and `mime@2` has introduced some breaking changes to its API.

**Comment by pegak** [comment]
Thanks, looks like they already switched to `mime-types`, but thanks for the recommendation anyway. :)
