### ISSUE TITLE
module shared in SSR different pages.

### ISSUE THREAD

**Issue by virsir** [vercel/next.js#40171]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 12.2.5
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

browser

### Describe the Bug

I have 2 simple pages with SSR enabeld. see: https://stackblitz.com/edit/vercel-next-js-cx1trj

Problems:
1. visit index page,  Error shows `server text is not match with client`. I got that, it is an expected behaviour.
2. visit `/about`, everything ok
3. visit index page, Errorshows `server text is not match with client`.That's ok.
3. visit `/about` again, Error shows `server text is not match with client`.  **It seems a bug to me.**

It seems the global module, imported and initialized for each page separately in the beginning(it output `console.warn('init globals');` 2 times), but later it has been used as a same object.

### Expected Behavior

The global module either should be separated or in a shared memory in all time.

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-cx1trj

### To Reproduce

1. visit index page,  Error shows `server text is not match with client`. I got that, it is an expected behaviour.
2. visit `/about`, everything ok, the page display the number 1.
3. visit index page, Error shows `server text is not match with client`.That's ok.
3. visit `/about` again, Error shows `server text is not match with client`.  **It seems a bug to me.**

**Comment by grayaustinc** [comment]
So this is not a bug.  What's happening is that when you first start the server, the index page get's build initially
```
wait  - compiling / (client and server)...
event - compiled client and server successfully in 195 ms (219 modules)
```
This will set the global value to 3 which is what you expect the value to be when you go to the about page.
What happens though is that upon navigating to the about page, the page get's compiled which basically restarts the server causing global state changes to be reset
```
wait  - compiling /about (client and server)...
event - compiled client and server successfully in 854 ms (219 modules)
```

- Do note that this compilation also happens for the _error page as well.

This is why at point 2, the global value is reset to 1.
Now that both pages are compiled, points 3 and 4 are expected as now the global value is not being reset due to page compilation.

When you build the nextjs project, the global does not get reset since the pages are precompiled.  I hope this explanation has helped you!

**Comment by virsir** [comment]
So, if I am not wrong, the problem I posted would only occur in dev mode, not in production env?

**Comment by grayaustinc** [comment]
> the problem I posted would only occur in dev mode, not in production env?

 Basically, yes.  It should work just fine in production.  The problem you are having is simply a side effect from the pages being compiled.  The `init globals` console message only ever appears right after the page is compiled due to [Fast Refresh](https://nextjs.org/docs/basic-features/fast-refresh).  I would highly recommend reading up on [How It Works](https://nextjs.org/docs/basic-features/fast-refresh#how-it-works) for a better understanding of what's going on as compilation of a page also causes a full reload.
```
Fast Refresh will re-run both that file, and the other files importing it.
```

So this is just my opinion on using global values the way that you are - 
_I would try to avoid using globals like this, and instead looking into using an in-memory database like Redis or Memcached.  Especially if you plan on updating the global values.  If you ever plan having multiple servers running, you would want a way to share the global values between the servers, and an in-memory database would be the best way to do it._

**Comment by virsir** [comment]
Thanks.
