### ISSUE TITLE
Image component is missing alt tag.

### ISSUE THREAD

**Issue by rsantoshreddy** [vercel/next.js#41230]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

all

### Describe the Bug

![image](https://user-images.githubusercontent.com/6243528/194317043-018cb040-37d8-45e9-bd8c-a9c44eddb493.png)
When we use the Next.js Image, we get three images rendered. The first image is missing alt. Please help.

### Expected Behavior

Can we have css tweaks and remove the first image without alt text?

### Link to reproduction

na

### To Reproduce

na

**Comment by gaston-flores** [comment]
I think that's [used internally by Next/Image](https://github.com/vercel/next.js/blob/f83cc0cbed4f1bf72360741241a7dfb0aac88aad/packages/next/client/image.tsx#L1038) to prevent layout shift, and since it's not meant to display anything, [it's acceptable behavior](https://www.a11yproject.com/posts/alt-text/):
> Use an empty alt attribute for any image that is decorative or not necessary for understanding the content of the page. For example, an image providing decoration to an article's heading could be hidden by giving the image an `alt=""` or simply `alt`

**Comment by balazsorban44** [comment]
As explained above, that image is a placeholder that is being replaced. The presence of `aria-hidden=true` means it's not meant to be seen by screen readers.
