### ISSUE TITLE
Hydration Error Using Input Type Email

### ISSUE THREAD

**Issue by ted-dino** [vercel/next.js#41293]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #202207312230~1663791054~22.04~28340d4 SMP PREEMPT_DYNAMIC Wed S
    Binaries:
      Node: 16.17.0
      npm: 8.17.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.5
      eslint-config-next: N/A
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

Firefox 105.0.3

### Describe the Bug

Hi, does anyone know why I get a hydration error when using the email input type? Unlike email, other formats do not return the error. This seems to occur only in Firefox.

found this same issue on stackoverflow: https://stackoverflow.com/questions/73571827/nextjs-input-hydration-error-when-using-type-email

### Expected Behavior

It should display the input email without error. 

### Link to reproduction

https://github.com/ted-dino/authentication-app/blob/main/pages/register.tsx#L90

### To Reproduce

i use `npx create-next-app@latest --typescript`
then create an input type `email` and open in firefox

**Comment by teobler** [comment]
Hi @ted-dino I try to use your way to reproduce the issue:
`npx create-next-app@latest --typescript`
then create an input type email and open in firefox
https://github.com/teobler/reproduce-issue

but I cannot get this error in firefox.
And in your stackoverflow link, there is a link([codesandbox.io/s/modest-haslett-um0jht](https://codesandbox.io/s/modest-haslett-um0jht)) try to reproduce the issue, still cannot get the issue, I don't think this is due to "email input".

**Comment by ted-dino** [comment]
yeah, its weird man and it only happens in Firefox. When I open it in Chrome(latest version), I don't get that error.

**Comment by balazsorban44** [comment]
Could you test it in Private Mode? I suspect that there might be an addon that modifies the HTML by injection.

**Comment by Bidouyeur** [comment]
I have the same issue and yes, it seems related to firefox relay. When I disable this addon, everything works fine.
