### ISSUE TITLE
i18n routing: disagreement between docs and actual behavior around sub-path routing for default locale

### ISSUE THREAD

**Issue by srmagura** [vercel/next.js#41307]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.0
      npm: 8.19.2
      Yarn: 3.2.3
      pnpm: N/A
    Relevant packages:
      next: 12.3.2-canary.23
      eslint-config-next: 12.3.1
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 105.0.5195.125

### How are you deploying your application? (if relevant)

I am testing this in local development (`next dev`).

### Describe the Bug

The [i18n routing docs](https://nextjs.org/docs/advanced-features/i18n-routing#sub-path-routing) state in the "Sub-path Routing" section:

> With the above configuration en-US, fr, and nl-NL will be available to be routed to, and en-US is the default locale. If you have a pages/blog.js the following urls would be available:
>
> - /blog
> - /fr/blog
> - /nl-nl/blog
>
> The default locale does not have a prefix.

In practice, I find that the page is rendered for the paths:

- /blog
- **/en-us/blog**
- /fr/blog
- /nl-nl/blog

I.e. there are two URL paths that render the English page. 

The question is: **Are the docs inaccurate, or is Next not behaving as it should?**

**Having the English page accessible at two paths likely has implications for SEO.** To make Google happy, you need to [list all alternate versions of the page](https://developers.google.com/search/docs/specialty/international/localized-versions) using `<link rel="alternate">` in the `<head>`. It is unclear if there should be `<link>` tags for both `/blog` and `/en-US/blog`, or if there should only be one for `/blog`. I'm also concerned that Google will get confused (and possibly penalize our search rankings) if we have two `<link>` tags that specify `hrefLang="en-US"`.

### Expected Behavior

Ideally, the actual behavior of Next would be changed to align with what is stated in the docs:

> The default locale does not have a prefix.

### Link to reproduction

https://github.com/srmagura/next-i18n-routing-repro

### To Reproduce

1. Run the linked minimal repro.
2. Go to http://localhost:3000/blog. It renders "Blog — en-US".
3. Go to http://localhost:3000/en-US/blog. It renders "Blog — en-US".
 
![image](https://user-images.githubusercontent.com/801549/194905833-0e45ffa5-0d8b-4bf1-9e0a-68d980dd16c3.png)

**Comment by elkreto** [comment]
Hi, I have encountered the same issue. In overall the i18n feature of next.js is weird and inconsistent to say the least. Trying to fill those gaps and make routes not available is hard. I'm actively looking for a solution to this issue. In my use case I want the default locale routes with prefix to be not accessible - 404 or to be redirected to the route without the prefix. This has been causing me headaches - redirects won't work - if you would write something like inside the next.config.js:
`
{
    source: '/en-US/:path*',
    destination: '/:path*',
    locale: false, 
   permanent: true
}
`

You will see `ERR_TOO_MANY_REDIRECTS ` when trying to type anything starting with default locale (/en-US/ in this case) 

The second idea that I had to redirect traffic from `/en-US/*` to `/*`  is to use middleware - those are available in next.js 12.2 or higher. I'm stuck on 10.0.9 and can't uhttps://github.com/vercel/next.js/issues/21210pgrade due to issues with assets, so I haven't been able to try if that will work. 

The issue is known - at least assuming from the number of issues on github alone that are open and describe the same problem. 

Here are much older threads describing the same bug: 

-https://github.com/vercel/next.js/issues/20120

-https://github.com/vercel/next.js/issues/21210  

Let me know if you find the solution - maybe the middleware approach will fix it and migrating to next.js 12 will be worth the work.

**Comment by aleksijohansson** [comment]
We are experiencing the exact same issue!

**Comment by thexpand** [comment]
@srmagura One can only hope. But it seems unlikely for them to provide this functionality out of the box. You can check out this issue for more information: https://github.com/vercel/next.js/issues/41980

Also, as stated in the beta docs for the new `app` directory, they don't plan to have i18n support:
https://beta.nextjs.org/docs/app-directory-roadmap#not-planned-features

**Comment by leerob** [comment]
Hey folks! We have heard your feedback and are making i18n routing much more configurable in the `app` directory. We will likely not be making large changes to i18n routing in `pages`, which could potentially have breaking changes. After talking to many customers, we've found that the use cases for i18n routing vary quite a bit, and it's hard to find a single configuration that works for everyone. Thus, the docs for `app` teach how to get a solution with Middleware.

https://beta.nextjs.org/docs/guides/internationalization
