### ISSUE TITLE
Huuge performance drop with latest canary version and middleware

### ISSUE THREAD

**Issue by 11koukou** [vercel/next.js#41551]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise LTSC 2021
    Binaries:
      Node: 16.17.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.2-canary.31
      eslint-config-next: 12.3.1
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

After upgrading to latest canary version, in order to migrate from "/next/future/image" to "next/image" , I have a huge performance drop (middleware enabled). It is pretty obvious when I load my website but also when I run lighthouse which reports a core of 51 instead of ~97 that i reported before the upgrade. If I either switch to latest next stable release or disable the middleware performance returns to normal levels

### Expected Behavior

Latest canary release should not drop the performance

### Link to reproduction

https://github.com/11koukou/my-app

### To Reproduce

Simply clone the project, npm install, npm run build, and npm start. Check out the performance and then disable/delete the "middleware.ts" file , repeat the steps and check the performance again. Without middleware lighthouse reports 100. The same happens if you just downgrade to next version 12.3.1 and keep the middleware enabled

**Comment by 11koukou** [comment]
Found out that performance drops due to middleware being enabled, if I disable middleware everything works as previously. So something happens with the server side code

**Comment by 11koukou** [comment]
Added reproduction repo

**Comment by balazsorban44** [comment]
Slight variations on the result might happen for different reasons (fluctuating network connection, extensions being enabled, etc.), but I cannot reproduce the above-mentioned issue:

`canary` + `middleware.ts`:
![image](https://user-images.githubusercontent.com/18369201/196700232-c7414807-486a-4ae4-91ab-0f22b6a95af4.png)

`canary` without `middleware.ts`:
![image](https://user-images.githubusercontent.com/18369201/196700513-a712d6f6-4ecc-4a3f-a747-61b049e90b45.png)

`latest` + `middleware.ts`:
![image](https://user-images.githubusercontent.com/18369201/196700849-5ba486a8-f627-4144-b551-b90ce2439ff7.png)

`latest` without `middleware.ts`:
![image](https://user-images.githubusercontent.com/18369201/196700721-dbee44f9-2748-4a45-8cfb-7fb67a0fdcb2.png)

I essentially see no difference in the results.

Remember to run Lighthouse on a production build `next build && next start` rather than against `next dev`, as most of the optimizations aren't applied as the dev environment is meant to give the best UX rather than the best performance. :+1: Also, do run Lighthouse in an incognito window/without enabled browser extensions with no other background activity for the most accurate scores.

I also recommend setting priority on the first image, if it will be above the fold/instantly on page load. See: https://nextjs.org/docs/basic-features/image-optimization#priority

**Comment by 11koukou** [comment]
I can confirm that the issue persists with node version 16.18.0 or 16.17.1. In any node version 16.5.0 and lower that I have tested the issue does not exist
