### ISSUE TITLE
Fira Code doesn’t work with @next/font

### ISSUE THREAD

**Issue by calebmer** [vercel/next.js#41916]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022
    Binaries:
      Node: 14.19.3
      npm: 6.14.17
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

I downgraded to Next.js 13 because the canary kept giving me a “`@next/font` is configured incorrectly” error.

### Describe the Bug

The `Fira_Code()` font from `@next/font/google` renders as a generic system arial font instead of [Fira Code](https://github.com/tonsky/FiraCode).

When I look in the network tab it appears as if Fira Code is being downloaded?

### Expected Behavior

When using the Fira Code font it actually looks like Fira Code and not a generic arial font.

### Link to reproduction

https://codesandbox.io/s/next-font-fira-code-bug-repro-cds8ze?file=/package.json

### To Reproduce

1. Open the [sandbox](https://cds8ze.sse.codesandbox.io/)
2. Note that the font is not [Fira Code](https://github.com/tonsky/FiraCode)

**Comment by hanneslund** [comment]
You're getting a warning that you have not [specified a subset](https://beta.nextjs.org/docs/optimizing/fonts#specifying-a-subset) to be preloaded.
> The @next/font/google font Fira Code has no selected subsets. Please specify subsets in the function call or in your next.config.js, otherwise no fonts will be preloaded.

Since no subset is specified and the [`font-display`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) is `optional` by default, it won't be downloaded in time before its [block period](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display#the_font_display_timeline) is over. So the generated fallback font is shown instead.

Try adding `'latin'` to the [specified subsets](https://beta.nextjs.org/docs/optimizing/fonts#specifying-a-subset).

**Comment by calebmer** [comment]
I’m also having issues with `Inter({weight: "700"})`. Weirdly, while playing around with this it seems like the correct font pops in a couple seconds after I interact with the `<style>` tag in `<head>`?

**Comment by calebmer** [comment]
@hanneslund ah yeah! That does it. Oops missed the log…

**Comment by hanneslund** [comment]
@calebmer awesome! 💯
