### ISSUE TITLE
Cannot use css media queries (screen size)

### ISSUE THREAD

**Issue by TurniXXD** [vercel/next.js#42072]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed, 05 Oct 2022 12:15:15 +0000
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.1-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Brave

### Describe the Bug

I cannot use media queries for minimal / maximal screen width / height in client component. First I tried tailwindcss `sm:` abbriviations and then native css but nothing seems to work.

### Expected Behavior

I can use media queries normally.

### Link to reproduction

https://github.com/TurniXXD/blog

### To Reproduce

- Create next app with typescript
- Add the `experimental: { appDir: true }` config
- Setup tailwindcss

**Comment by balazsorban44** [comment]
Thanks this is a known issue and happens due to a temporary solution that adds some extra `div` elements in the DOM. This is used for improved scroll management and the plan is to remove the div's all together in a future release and fix this in React upstream. For more context: https://github.com/vercel/next.js/discussions/41745#discussioncomment-3964086

**Comment by gfortaine** [comment]
@TurniXXD https://github.com/vercel/next.js/issues/41842#issuecomment-1292104770

cc @codekcv
