### ISSUE TITLE
Link tags do not populate Scripts on renavigation

### ISSUE THREAD

**Issue by temrb** [vercel/next.js#42088]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Mac os

next latest
react latest

### Describe the Bug

I do not know why this issue has yet to be solved...

Very old issue that was closed due to inactivity. 
https://github.com/vercel/next.js/issues/4477

I ended up using A tags even if I get lint errors.

### Expected Behavior

Script tags to work on navigation

### Link to reproduction

https://github.com/vercel/next.js/issues/4477

### To Reproduce

https://github.com/vercel/next.js/issues/4477

**Comment by balazsorban44** [comment]
Please add a reproduction using `next@canary`.

**Comment by temrb** [comment]
@balazsorban44  I am using async script -- loading strategies fail for this

**Comment by balazsorban44** [comment]
> I will link repro in a moment

Appreciated! :pray:

**Comment by temrb** [comment]
@balazsorban44 

https://github.com/temrb/next-link-issue

**Comment by balazsorban44** [comment]
So after re-reading this and looking at the reproduction, I don't think there is an issue here. 

From [the docs](https://nextjs.org/docs/basic-features/script#:~:text=The%20script%20will%20only%20be%20fetched%20and%20executed%20when%20this%20specific%20page%20is%20loaded%20on%20the%20browser.): 
> The script will only be fetched and executed when this specific page is loaded on the browser.

If you need to execute some code after the script has loaded, you can check out the `onLoad` or `onReady` [event callbacaks](https://nextjs.org/docs/basic-features/script#executing-additional-code).

**Comment by temrb** [comment]
On the reproduction wasnt that the only code being executed? 
And the page is loaded **everytime** when you click on the link? Maybe the wording is incredible confusing me

**Comment by temrb** [comment]
@balazsorban44 

even with this statement,

> The script will only be fetched and executed when this specific page is loaded on the browser.

 I think there is an issue as it's **not fetching the script at all in network when the page loads**... when you interact with the link in the "using link" tab...
 
 
 Either issue with <Link> or <Script> or I am heavily mis understanding the docs which is an issue on it's own...

**Comment by temrb** [comment]
> The script will only be fetched and executed when this specific page is loaded on the browser.

https://user-images.githubusercontent.com/22056864/198749053-0cf18c2c-a683-4a0e-8908-9cc0ea5e7c2d.mov

It doesnt load the script or any scripts at all Idk if this has been a silent bug for many years that Nextjs/ vercel did not want to address at the time as the community was talking about it then lol

#4477

**Comment by RemyMachado** [comment]
This behavior is a big problem. I found dozens of issues on StackOverflow and GitHub that may be connected to this behavior.  

Just to name a few:
- [NextJS: Reloading Ads Javascript and Ad Slots on Route Change](https://stackoverflow.com/questions/69294792/nextjs-reloading-ads-javascript-and-ad-slots-on-route-change)
- [Next.js Loads <script> tags but it doesn't execute them](https://stackoverflow.com/questions/54067291/next-js-loads-script-tags-but-it-doesnt-execute-them)
- [Scripts not working in React, NextJS project unless I specifically refresh the page](https://stackoverflow.com/questions/71877933/scripts-not-working-in-react-nextjs-project-unless-i-specifically-refresh-the-p)
- [Invisible reCAPTCHA disappears on page navigation in next.js app](https://stackoverflow.com/questions/72644727/invisible-recaptcha-disappears-on-page-navigation-in-next-js-app)
- [Next 11 and adding Script tags not working. No scripts are rendered](https://stackoverflow.com/questions/68058814/next-11-and-adding-script-tags-not-working-no-scripts-are-rendered)
- #4477
- #35064

Unfortunately, a single sentence in the documentation isn't sufficient. There is no indication on how to  reload the script.  
> Note: Once a next/script component has been loaded by the browser, it will stay in the DOM and client-side navigations won't re-execute the script.

___

### I hoped there would be examples and documentation on how to load/reload the scripts on client-navigation

At the moment I'm using a sketchy workaround by manipulating the `DOM`.

```jsx
import { FC, ScriptHTMLAttributes, useEffect, useId } from 'react'

interface Props
  extends Pick<ScriptHTMLAttributes<HTMLScriptElement>, 'id' | 'src' | 'async' | 'defer'> {
  src: string
}

const ScriptReloadOnClientNavigation: FC<Props> = ({ id, src, async = false, defer = false }) => {
  const uniqId = useId()

  useEffect(() => {
    const script = document.createElement('script')

    script.id = id || uniqId
    script.src = src
    script.async = async
    script.defer = defer

    document.body.appendChild(script)

    return () => {
      document.body.removeChild(script)
    }
  }, [async, defer, id, src, uniqId])

  return null
}

export default ScriptReloadOnClientNavigation
```

It allows the script to be reloaded every time it's mounted. Thus, working on client-navigation.
Note that I prefer using a `Component` rather than a `custom hook` since I want this behavior to be read like a `<script />` tag would.

**Comment by temrb** [comment]
@RemyMachado agreed. I was initially using use effect and custom hook like you mentioned here.. though it was super clunky. I abandoned it completly and gave up on this path of that feature and went a different approach.
