### ISSUE TITLE
Component in layout renders below children, when placed above.

### ISSUE THREAD

**Issue by kasperaamodt** [vercel/next.js#42143]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.18
      pnpm: 7.6.0
    Relevant packages:
      next: 13.0.1-canary.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

In my root layout, I have a `<Header />` component placed before `<body>{children}</body>`. In all routes, the header renders after the closing body tag, causing a hydration error.

### Expected Behavior

I expect the header to render above the body, where I am placing it.

### Link to reproduction

https://codesandbox.io/s/currying-morning-v0mbio?file=/app/layout.tsx

### To Reproduce

Run the codesandbox

**Comment by iljamulders** [comment]
@kasperaamodt 
De browser is changing the html because because you're writing invalid html syntax. And react loses track of where it went.
Try making a test.html and compare the source code vs the developer inspect tool:
```html
<!DOCTYPE html>
<html lang="no">
<head>
    <title>Naturbildet</title>
    <link rel="icon" href="/favicon.ico"/>
</head>
<header><span>This is a header</span></header>
<body>
<div data-nextjs-scroll-focus-boundary="">
    <div><h1 class="text-4xl font-bold">Hello world from a page</h1></div>
</div>
</body>
</html>
```

If you check the source code of your pages, you will see next.js "correctly" placing the `<header>` before the `<body>`
<img width="1043" alt="Screenshot 2022-10-29 at 20 37 53" src="https://user-images.githubusercontent.com/6195121/198847747-5070da00-00b1-4678-a6c7-98af4455cea3.png">

**Comment by kasperaamodt** [comment]
@iljamulders yes, haha I realized and closed the issue just before you commented! Thank you for explaining though! 😄
