### ISSUE TITLE
[v13 + appDir] prefetch={false} breaks client-side navigation

### ISSUE THREAD

**Issue by apostolos** [vercel/next.js#42175]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Aug 24 22:24:20 UTC 2022
    Binaries:
      Node: 19.0.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.14.1
    Relevant packages:
      next: 13.0.1-canary.1
      eslint-config-next: 13.0.1-canary.1
      react: 0.0.0-experimental-cf3932be5-20221027
      react-dom: 0.0.0-experimental-cf3932be5-20221027

### Describe the Bug

Adding `prefetch={false}` to a link breaks client-side navigation. Clicking on the link causes a full page navigation (no error is thrown).

IMPORTANT: If there is another <Link> *for the same path* with prefetch enabled, then the Link with `prefetch=false` also works correctly. You can uncomment the 2nd link in the StackBlitz to reproduce that behavior as well.

### Expected Behavior

Clicking on a link with `prefetch={false}` should perform a client-side navigation.

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-no-client-side-nav?file=app%2Fpage.tsx

### To Reproduce

Open homepage and click on the link. You can confirm the full page navigation via the browser's console.

**Comment by Smirow** [comment]
I can confirm. However i'm not seeing consistant behaviour between dev/prod/Vercel, but there is definitely something going on (maybe some versioning issues).
Maybe related, `<Link/>` seems unable to prefetch dynamic routes like `/app/test/[testId]/leaf/page.tsx`. 
Prefetching dynamic route generates a `200` reponse in dev mode but the response is actually empty. The same prefetching generates a `404` error on Vercel. Definitely unstable.

**Comment by Smirow** [comment]
I can confirm. I am seeing similar issues when trying to prefetch dynamic routes like `app/test/[testId]/leaf/page.tsx` where the prefetching systematically fails **on Vercel** (but works fine with next dev & start) and leads to a complete page reload.
I am also seeing the same issue when setting headers to the request in the middleware (as allowed in Next 13 https://nextjs.org/docs/advanced-features/middleware).

**Comment by Smirow** [comment]
So the behavior you described is due to forcing `OptimisticNavigation` when calling the router in `link.tsx` when prefetching is disabled. Not sure it was the intended behavior.

https://github.com/vercel/next.js/blob/0affdebf67b0b94d409285906e250acb19b2cca1/packages/next/client/link.tsx#L186-L188

The problem on Vercel does **not** seem to be related to this.

**Comment by jackypan1989** [comment]
Same issue with ```prefetch={false}```

**Comment by Hanskrogh** [comment]
Any news on this?

**Comment by Smirow** [comment]
I think that @timneutkens told before in another issue that is currently the excepted behavior. Can you confirm?

**Comment by isilweo** [comment]
Let's say we have a page with 50 visible links (let's name it contest) to other pages (contest_result/[id]). Contest results is a page that has let's say 500kb of <table> data that needs to be loaded using SSR. 
Right now the behavior is either
1 - prefetch is enabled - all links are prefetched but in this case it is 25mb of prefetched data (500kb*50links) and client navigation is working
2 - prefetch is disabled - we don't prefetch 25mb of data but if we follow the link client side navigation is broken and we have full page refresh which is missing the whole point of using react/nextjs

i don't understand how this would be expected behavior. so what should we do in above case? don't use app dir and go back to old/current aproach with pages and "api pages"?

**Comment by Smirow** [comment]
see https://github.com/vercel/next.js/pull/43730#issuecomment-1357362975

**Comment by Smirow** [comment]
And from the docs `On navigation, Next.js will use soft navigation if the route you are navigating to has been prefetched, and either doesn't include dynamic segments or has the same dynamic parameters as the current route.`

https://beta.nextjs.org/docs/routing/linking-and-navigating#conditions-for-soft-navigation

**Comment by timneutkens** [comment]
Verified the issue that was originally reported with the provided reproduction has been fixed a while back.

@astateful please open a new issue with a full reproduction
