### ISSUE TITLE
App Dir is caching renders even with "dynamic" set to "force-dynamic"

### ISSUE THREAD

**Issue by AlexKvazos** [vercel/next.js#42546]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #14 SMP Sat Jun 4 00:16:10 CEST 2022
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.0.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

When clicking on <Link /> to go to a page that has "dynamic" segment config set to "force-dynamic" the page still uses a cached render from a previous visit.

### Expected Behavior

The "force-dynamic" config should make the page render again each time you visit the page through <Link /> or any other client side transition.

### Link to reproduction

https://stackblitz.com/edit/nextjs-sxijav?file=package.json,app%2Fnested%2Fpage.tsx

### To Reproduce

- Click link to go to the nested page
- A random number will show
- Click link to go to home page
- Click link to go to nested page
- Bug: Same number shows (Expected: Different number)

**Comment by zenflow** [comment]
Manually setting `cache: "no-store"` on all the fetch calls doesn't work [to make the page dynamic] either.

**Comment by Fredkiss3** [comment]
It is because of [soft navigation](https://beta.nextjs.org/docs/routing/linking-and-navigating#soft-navigation), with the new layouts nextjs does soft navigation by default, when your page has not been rendered already and the user navigates to it with a link component, it does not rerender the page each time. 

What the nextjs team said is that your page should rerender if you do a mutation with their upcoming mutation, or if you call `router.refresh`.
 
It is a PIA i think because the mental model of dynamic pages is that it should rerender each time you go to them.

**Comment by zenflow** [comment]
From the docs link above:
> On navigation, Next.js will prioritize using soft navigation if the route you are navigating to has been [prefetched](https://beta.nextjs.org/docs/routing/linking-and-navigating#prefetching), and either doesn't include [dynamic segments](https://beta.nextjs.org/docs/routing/defining-routes#dynamic-segments) or has the same dynamic parameters as the current route.

So not only a PITA, it doesn't work when data is dynamic but not dynamic based on route params (i.e. data that changes frequently, or data that changes based on current user / http headers). How are we supposed to force hard navigation in these cases?

**Comment by AlexKvazos** [comment]
It does feel missleading that a "force-dynamic" page will still use a soft render. There should be some place in the docs suggesting something like...

```tsx
useState(() => router.refresh())
```

Or some other way to have this run on the first render only. I don't think this is very elegant.

**Comment by gfortaine** [comment]
@AlexKvazos given that it is Client-Side Navigation, it seems that you should wrap the result of the `getRandomNumber` function in a `useEffect` to trigger a re-render,   please see https://github.com/vercel/next.js/issues/41851#issuecomment-1312745014

**Comment by gfortaine** [comment]
@Fredkiss3 Please upgrade to Next.js 13.0.3 (& use a Client Component) to make it work : https://stackblitz.com/edit/nextjs-zjyueq?file=app%2Fnested%2Fpage.tsx

**Comment by Fredkiss3** [comment]
@gfortaine , the solution you’re suggesting is to use ˋuseˋ, use automatically fetch infinitely, so no it’s not a viable solution, at least right now, since ˋuseˋ is not a stable API right now, and is supposed to come with the ˋcacheˋ api in react.

**Comment by Fredkiss3** [comment]
Yes use is an experimental, but the RFC hasn’t landed yet and the infinite fetches seems to be more of react issue that NextJs. 
I don’t really want to recommend this since it is still heavily in development and the default behaviour now is not optimal.

> indeed there is a clear case where it leads to infinite fetches : when we start directly on the /nested path. But clicking on /nested in / is OK. Thus, it looks like that Next.js doesn't handle use very well right now.

Still One odd thing I noticed is that it still does at least 3 or 4 fetches (which is isn’t supposed to be the case, right ?)

at least with the `"use client"` it should only fetch twice : once in the server and the second time in client during hydration. 

But it fetches once in the server and 3 or 4 more in the client.

**Comment by gfortaine** [comment]
After a thorough reading of the documentation, it seems that [`fetch` is not yet supported in Client Components](https://beta.nextjs.org/docs/data-fetching/fetching#use-in-client-components). By the way, I do confirm that the use of `use` in Client Components is litteraly unusable for the time being due to infinite trigger of the function being called (`fetch` ot whatever)

**Comment by gfortaine** [comment]
According to the following comment, it seems that one should create a new root layout (`/nested`) to trigger a hard navigation : 

https://github.com/vercel/next.js/discussions/41745#discussioncomment-3985483

**Comment by Fredkiss3** [comment]
@gfortaine  I've put up an example with that in mind : https://stackblitz.com/edit/nextjs-wxc4fy
But In my opinion, that is some pretty hacky way to solve this. And i don't think this would be a viable solution...

I still think this is not good enough, and they should this fix... or at least indicate in the doc a way around this.

**Comment by Fredkiss3** [comment]
What is weird, is that when using a dynamic route segment, a hard navigation always occurs : https://stackblitz.com/edit/nextjs-51tdbm

I think this is indeed a bug

**Comment by zenflow** [comment]
> What is weird, is that when using a dynamic route segment, a hard navigation always occurs : [https://stackblitz.com/edit/nextjs-51tdbm?file=app%2F[any]%2Fpage.tsx](https://stackblitz.com/edit/nextjs-51tdbm?file=app%2F%5Bany%5D%2Fpage.tsx)

@Fredkiss3 Just pointing out that this is the documented behavior. See https://beta.nextjs.org/docs/routing/linking-and-navigating#soft-navigation :

> On navigation, Next.js will prioritize using soft navigation if the route you are navigating to has been [prefetched](https://beta.nextjs.org/docs/routing/linking-and-navigating#prefetching), and either doesn't include [dynamic segments](https://beta.nextjs.org/docs/routing/defining-routes#dynamic-segments) or has the same dynamic parameters as the current route.

Of course there's still an issue with this documented behavior..
What are we supposed to do when we have dynamic data that changes frequently? Or data that depends on authentication state? Currently stale data will be shown until user does a manual refresh, or we need some hack to force a "hard refresh" (`useState(() => router.refresh())`, which I haven't looked into using but I think may have some undesired side-effects).

**Comment by AlexKvazos** [comment]
Closing in favor of #42991
