### ISSUE TITLE
ISR + Vercel: next/link does not trigger revalidation

### ISSUE THREAD

**Issue by sdjnes** [vercel/next.js#43289]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 14.16.1
      npm: 6.14.12
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.3
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When navigating through a site with client side navigation (`next/link` components) that is deployed to Vercel and has the `revalidate` prop, the pages are not revalidated until a page refresh is done, or the page is visited directly via its URL.

Related discussion: https://github.com/vercel/next.js/discussions/42685

### Expected Behavior

Pages should be revalidated when visited via a `next/link`.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://vercel-next-isr-test-eycgc5wwf-sjones-inpostcouk.vercel.app/

### To Reproduce

I have a repository with a MRE: https://github.com/sdjnes/vercel-next-isr-test

It has 3 branches:

`main`: uses the `next` and `react` version that I have in the app I am seeing the problem in, `12.3.1` and `17`
`next-13`: uses `next: 13.0.3` and `react: 18` to represent a more modern setup
`canary`: uses `next: 13.0.5-canary.6` and `react: 18`

#### Deployments to Vercel
`main` deployment: https://vercel-next-isr-test.vercel.app/
`next-13` deployment: https://vercel-next-isr-test-nsnaodexd-sjones-inpostcouk.vercel.app/
`canary` deployment: https://vercel-next-isr-test-eycgc5wwf-sjones-inpostcouk.vercel.app/

#### Steps
1. Visit one of the deployments (issue is seen in all)
2. Go to ISR Page 1
3. Click between ISR Page 1 and ISR Page 2 using the `next/link`s on the page
4. Observe the `getStaticProps` timestamp does not update, and can be older than the `revalidate: 10` prop set for both pages
5. Refresh one of the pages to trigger the revalidation, and refresh again to see the updated `getStaticProps` timestamp

I have posted [a video](https://github.com/vercel/next.js/discussions/42685#discussioncomment-4161654) to the discussion demonstrating the steps.

I'm still not 100% if ISR should work this way with client side navigation -- please see the [discussion](https://github.com/vercel/next.js/discussions/42685) and let me know if I've misunderstood something.

**Comment by nicksergeant** [comment]
I ran into this also, but I also noticed that removing the `revalidate` option doesn't resolve the issue for me, so I wonder if this is a recent bug related to `getStaticProps` and `next/link` / client-side pushState nav in general.

**Comment by nicksergeant** [comment]
Link to a conversation on Discord that may be helpful: https://discord.com/channels/752553802359505017/1066904088224223312/1066904088224223312

**Comment by sdjnes** [comment]
> I ran into this also, but I also noticed that removing the `revalidate` option doesn't resolve the issue for me, so I wonder if this is a recent bug related to `getStaticProps` and `next/link` / client-side pushState nav in general.

I have been in contact with Vercel support that have confirmed the bug I outlined in the issue, and from what I understood it's an issue on Vercel's side and not Next.js.

**Comment by RemyMachado** [comment]
I don't think it's a Vercel issue, but rather a Next.js issue. I'm reproducing it when building locally on my machine. As long as I client-navigate with next/link the page won't revalidate. I need to explicitly hit the server-side in order to trigger an ISR with `revalidate`.

Also, since I'm using a caching solution (apollo-react, react-query, etc.) to consume APIs, I can refresh the client-side data every once in a while with the hook options. However, it's probably less efficient than triggering ISR since the data will only update for this single client and the next users will hit an outdated version that could have been invalidated a while ago.

**Comment by ijjk** [comment]
Hi, this has behavior has been updated since this issue was opened is works properly in the latest version `v13.4.1`. The current expected behavior is a best effort request is done on hover to update the client cache but if the user clicks before this request finishes the cache is leveraged instead to ensure immediate navigations. 

The revalidated content updating client-side in latest version can be seen in below screen recording. 


https://github.com/vercel/next.js/assets/22380829/af7c5d01-d2a0-499a-9e1b-6d1ebd3dc749

If you would like to always bypass the cache instead of this best-effort on-hover handing you can leverage `next.router.push('/isr-page-2', undefined, { unstable_skipClientCache: true })` directly which always bypasses the client cache.

**Comment by QzCurious** [comment]
Hi, @ijjk. I was experimenting app router with ISR and found this issue. Turns out that app router is not working as compare to pages router. Should this be a bug?

https://github.com/vercel/next.js/assets/38932402/80ef6289-366f-4ce0-b386-8f78a6243c23

The code for the recording is [here](https://github.com/QzCurious/next-isr-not-triggered-by-link). It is tested with `13.4.4-canary.10`.
