### ISSUE TITLE
Prefetch enabled during development

### ISSUE THREAD

**Issue by lucasmerlin** [vercel/next.js#43307]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 ```
   Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.0.5-canary.6
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

When starting next in development mode, next/link links prefetch, even though prefetching should be disabled during development:

https://beta.nextjs.org/docs/api-reference/components/link
> Prefetching is only enabled in production.

My site is pretty big and next trying to prefetch all the links causes the next dev server to build all prefetched pages when loading a single page, making development extremely slow. 

It even tries to prefetch non-app pages, which doesn't really seem to work at all.

### Expected Behavior

next/link shouldn't prefetch during development.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/lucasmerlin/router-prefetch-test

### To Reproduce

Ceckout repo
yarn && yarn dev

Go to http://localhost:3000/user/test/home
Open devtools

Observe prefetched pages in network dev tools:
![Bildschirmfoto 2022-11-23 um 17 50 33](https://user-images.githubusercontent.com/8009393/203603231-f54dbd0a-639e-4efc-87c4-9fa1de605a71.png)

**Comment by Alexandredc** [comment]
I have exactly the same issue on 2 different projects.

**Comment by vnghia187** [comment]
running dev crash to often for me because of heap out of memory, almost every hours
`
<--- Last few GCs --->

[14886:0x5fd1c20]  1180005 ms: Mark-sweep (reduce) 2030.5 (2062.0) -> 2029.9 (2062.2) MB, 159.5 / 0.0 ms  (average mu = 0.606, current mu = 0.015) allocation failure scavenge might not succeed
[14886:0x5fd1c20]  1180266 ms: Mark-sweep (reduce) 2030.9 (2062.2) -> 2030.3 (2062.5) MB, 259.0 / 0.0 ms  (average mu = 0.373, current mu = 0.010) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb02930 node::Abort() [/home/nghiavi/.nvm/versions/node/v16.17.0/bin/node]
 2: 0xa18149 node::FatalError(char const*, char const*) [/home/nghiavi/.nvm/versions/node/v16.17.0/bin/node]
 3: 0xcdd16e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/nghiavi/.nvm/versions/node/v16.17.0/bin/node]
 4: 0xcdd4e7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/nghiavi/.nvm/versions/node/v16.17.0/bin/node]
 5: 0xe94b55  [/home/nghiavi/.nvm/versions/node/v16.17.0/bin/node]
 6: 0xea481d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/nghiavi/.nvm/versions/node/v16.17.0/bin/node]
 7: 0xea751e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/nghiavi/.nvm/versions/node/v16.17.0/bin/node]
 8: 0xe68a5a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/nghiavi/.nvm/versions/node/v16.17.0/bin/node]
 9: 0x11e17c6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/nghiavi/.nvm/versions/node/v16.17.0/bin/node]
10: 0x15d5439  [/home/nghiavi/.nvm/versions/node/v16.17.0/bin/node]
`

**Comment by DmitriiBochok** [comment]
Up!

**Comment by levipadre** [comment]
Can someone explain to me this prefetch thing?
On localhost, when prefect is not disabled, on hovering over a link, I prefetch the page.
The same code on production prefetch every page when I'm in the viewport.
Why is it different?

Also, I think this "hover feature" would be really good. If I have 100 links on the page, I will prefetch 100 pages. By using middleware, that's 100 requests. Not to mention that if I'm not active on the page for a few minutes, it will prefetch every link again for some reason.

Is it possible to make this hovering thing possible as a prefetch option?

Another weird thing is that when I deploy a code without visiting the page (and I'm the only developer), I can see that on the Usage pageMiddleware Edge has been triggered three times. I can imagine that something is necessary, but with the prefetching, I will quickly reach the edge limit.

**Comment by altechzilla** [comment]
Same over here. It's prefetching lots and lots of routes, and on an app with hundreds of paths in generateStaticParams it's a memory nightmare. Any workarounds for this?

**Comment by timneutkens** [comment]
Prefetch is no longer enabled during development since many stable releases ago.
