### ISSUE TITLE
Running multiple instances of same NextJS app

### ISSUE THREAD

**Issue by datteroandrea** [vercel/next.js#43457]
### Describe the feature you'd like to request

Being able of running multiple instances of the same NextJS application can boost the performance of the application by using more efficiently the resources of the server (CPU, multi-process and multi-threading).

### Describe the solution you'd like

Being able to run the same application on different ports without incurring into errors.

### Describe alternatives you've considered

No other alternative AFAIK.

**Comment by Fredkiss3** [comment]
You can run nextjs in different ports with `next start -p YOUR_PORT`, is this solution enough ?

**Comment by datteroandrea** [comment]
Appearently it is not, when running the same application on different ports when I try to load the main page it starts reloading the page continuously and/or it shows the following error:

```
Error: Cannot find module 'D:\projects\react\project\.next\server\pages\mypage.js'
Require stack:
- D:\projects\react\project\node_modules\next\dist\server\require.js
- D:\projects\react\project\node_modules\next\dist\server\next-server.js
- D:\projects\react\project\node_modules\next\dist\server\next.js
- D:\projects\react\project\node_modules\next\dist\server\lib\start-server.js
- D:\projects\react\project\node_modules\next\dist\cli\next-dev.js
- D:\projects\react\project\node_modules\next\dist\lib\commands.js
- D:\projects\react\project\node_modules\next\dist\bin\next
```

**Comment by Fredkiss3** [comment]
In `dev` mode, since it modifies the same folder, i don't think it is possible to run multiple instances of your app in the same repo.

But in production mode with `next start` or `npm run start` you can. 
I've managed to do so with two instances of my app working on two different ports `3001` and `3002` :

https://user-images.githubusercontent.com/38298743/204307121-b7907f8a-98de-4113-b39c-5d213516964e.mov
