### ISSUE TITLE
localStorage is undefined error in 'use client' component

### ISSUE THREAD

**Issue by Biratus** [vercel/next.js#43568]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Wed Nov 30 2022 17:21:37 GMT+0100 (Central European Standard Time)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.0.6-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/nextjs-rsxy9d?file=package.json

### To Reproduce

Start the app

### Describe the Bug

I am attempting to use localStorage within a custom hook.
The server throws a 'localStorage is undefined' error when compiling a 'use client' component.

The error is still thrown even though there is a guard to prevent the use of the variable if it is undefined.

Nonetheless the code works, localStorage is used and the values are saved but the error is still in the logs, which is not pretty and also should not appear since there is a guard.... I tried logging the value of localStorage at the beginning of the hook (undefined when run on server as expected) and logging the comparison (typeof localStorage === 'undefined') which is true on the server (as expected) still the error is thrown.

Thank you Next.js team for your efforts

### Expected Behavior

- The hook should be called only on the client (not sure about that with all the new changes with Next 13)
- The 'localStorage is undefined' should not appear in the logs and the guard should work.

**Comment by balazsorban44** [comment]
You have a reference to `localStorage` in the `useEffect`'s dependency array. The `useEffect` body is not evaluated in the prerendering (which is server-side) pass, but the dependency array is.

Also, since the `useEffect` body is browser-only, you can remove the following check, as it does nothing:

```
if (typeof localStorage === undefined) return;
```

You can try installing ESLint for the project to get notes about the correct usage of dependency arrays:

![image](https://user-images.githubusercontent.com/18369201/204862342-bd4dc246-a989-4819-97e9-d41163e22c75.png)

See also: https://nextjs.org/docs/basic-features/eslint
