### ISSUE TITLE
Middleware rewrite not honoured with SSR

### ISSUE THREAD

**Issue by afewyards** [vercel/next.js#43877]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 18.11.0
      npm: 8.19.2
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.0.7-canary.3
      eslint-config-next: 13.0.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/afewyards/nextjs-rewrites

### To Reproduce

In chrome disable javascript to only get the SSR variant and not the client render.

goto https://nextjs-rewrites-a-dam.vercel.app/ and verify the output is NL
now go to your devtools and change the cookie country to anything else. e.g. US and reload the page
the output is now empty

expected output should have been US

### Describe the Bug

What I think is happening is that the HTML rendered version is not correctly passed the middleware and therefor not correctly applies the rewrite. The JSON version of the page is correct and will render the page on the client again with the right data. This causes unnecessary render cycles.

### Expected Behavior

The middleware rewrites the url and delivers the correct SSR cached page based on the given parameters.

### How are you deploying your application? (if relevant)

Vercel

**Comment by Fredkiss3** [comment]
That's weird, because it works for me 🤔

![Enregistrement de l’écran 2022-12-09 à 11 46 56](https://user-images.githubusercontent.com/38298743/206685836-16236e8f-9db9-4c51-8144-b74943519774.gif)

**Comment by afewyards** [comment]
Hmmm now it does for me as well. Might need to adjust the example. will update this.

**Comment by afewyards** [comment]
Just try a random string in the country field. I think it does work normally once the client requested the json. but if it's fresh it doesnt work

**Comment by afewyards** [comment]
https://user-images.githubusercontent.com/1126236/206690239-6e3c1700-7077-415f-be52-b5588ae65c3c.mov

**Comment by Fredkiss3** [comment]
I think i found the problem : When you first try to generate a page with a different cookie value it shows an empty page, even on several refreshes (if you are in the same device apparently). The next time you access the page with the same cookie it shows the correct page with the correct data.

I found out by going to private mode, disabling JS first, going to the site, changing the cookie value to `RANDOM`, it showed an empty page. Then i closed the private mode, and redid the same thing, it showed the correct page.

It seems to work like ISR, by showing the stale version first when you navigate to the page, then after it has cached the page, it shows you the correct version. 

There is surely some caching involved in the CDN since i disabled caching in the browser, that's why it only shows when i close then open a new private mode browser. 
And if it works with JS enabled, it may be because it fetches the up-to-date page data on client load.

**Comment by afewyards** [comment]
Yeah it works ok if JS is enabled but on my production site we are getting hydration errors because of this.

**Comment by afewyards** [comment]
Ahh It might be the fallback on the props. Gonna see if blocking will resolve this. It should
