### ISSUE TITLE
Some static images missing from build in 13.0.7

### ISSUE THREAD

**Issue by iscekic** [vercel/next.js#44143]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
next 13.0.7
react 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue

/

### To Reproduce

* update to `13.0.7`
* `yarn build`
* `yarn start`

Partial `next.config.js`, if relevant:
```
swcMinify: false,
images: {
    minimumCacheTTL: 3 * 30 * day,
    formats: ["image/avif", "image/webp"],
}
```

### Describe the Bug

Some static images return `404` and are missing from the build folder.

The exact same code works properly in `13.0.6`

### Expected Behavior

Images are present.

### Which browser are you using? (if relevant)

/

### How are you deploying your application? (if relevant)

`next start`

**Comment by iscekic** [comment]
Potentially related: #44012

**Comment by spencerbeggs** [comment]
In this repo, imported images are building to the wrong directory: https://github.com/spencerbeggs/nextjs-template

**Comment by milo-** [comment]
Seeing the same issue, downgrading to 13.0.6 fixes the missing images

**Comment by martinnabhan** [comment]
Hello everyone.

I'm currently debugging this issue and in my case it turns out images imported in client only dynamically imported components using `next/dynamic` (i.e. `dynamic(() => import('...', { ssr: false } ))` aren't getting emitted into `.next/static/media`. I've found out why and am currently preparing a pull request to fix the issue.

Is everyone here also using `next/dynamic` with `ssr: false`?
If you are I'll mark my pull request as fixing this issue!
If not, if you could please provide a reproduction I'll take a look.

**Comment by helioxy** [comment]
you are right. images show with `ssr: true`

**Comment by Trallp** [comment]
The same problem with `ssr: false` on 13.1.1

**Comment by uklyumka** [comment]
The same issue 13.1.1
