### ISSUE TITLE
Error when build in nx monorepo

### ISSUE THREAD

**Issue by tzii** [vercel/next.js#44363]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 16.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), CLI (create-next-app)

### Link to the code that reproduces this issue

https://github.com/tzii/next13-error

### To Reproduce

yarn build web-app --prod

### Describe the Bug

include wrong path in tsconfig

### Expected Behavior

correct path

**Comment by andreyantipov** [comment]
encountering same issue within recent v13.1.1 version

**Comment by micaww** [comment]
i've been encountering this as well. seems to be caused by this change https://github.com/vercel/next.js/blob/canary/packages/next/src/lib/typescript/writeConfigurationDefaults.ts#L169 to include the build dir in the tsconfig types.

with Nx it adds `../../dist/apps/blahblah` which causes a bunch of module not found errors when validating typescript.

i've "fixed" this locally by just commenting out the writing to tsconfig in my node_modules so i could continue working without disabling ts typechecking: https://github.com/vercel/next.js/blob/canary/packages/next/src/lib/typescript/writeConfigurationDefaults.ts#L222

**Comment by Sylphide** [comment]
If you don't want to update your node_modules, you can add the wrong include in the exclude array. It is still just a workaround though.

**Comment by tefkah** [comment]
Same, more specifically i get these messages
```sh
info  - Checking validity of types ..We detected TypeScript in your project and reconfigured your tsconfig.json file for you. Strict-mode is set to false by default.

The following suggested values were added to your tsconfig.json. These values can be changed to fit your project's needs:

        - include was updated to add '../../dist/apps/peer-review/.next/types/**/*.ts'
```

Then i get the error

```sh
info  - Checking validity of types ..Failed to compile.

Type error: Cannot find module '../../../../../app/[pr]/page' or its corresponding type declarations.
```

because `dist/apps/peer-review/.next/types/app/[pr]/page' has this as the first line
```ts
import * as entry from '../../../app/[pr]/page'
```

which obviously doesn't have types.

**Comment by ardokirsipuu** [comment]
Encountering the same issue with Nx. According to my testing it **started from version 13.1.0**. 

It was quite a frustrating experience as undoing my last changes (including reverting back to 13.0.x) still had my builds failing so I spent some time trying to fix the code I wrote. Turned out the issue was not written by me but by Next modifying configuration files. 😬👀 Therefore, I'll write a friendly warning just in case:

**Please note that the order of testing different Next versions here is important as during a build Next adds new include paths to the `tsconfig.json` file, but does not remove entries added by other Next versions. If you want to switch between Next versions multiple times and get authentic results then you have to remove any `**/.next/types/**` entries manually before trying to build with a different version.**

**Comment by hoqua** [comment]
The same issue after 13.1.0 Nx + NextJS - can't build 
`Cannot find module '../../../../app/layout' or its corresponding type declarations.`

I hope there will be some progress on this issue 🙏

**Comment by Brian-McBride** [comment]
NextJS should not modify the `tsconfig.json` files at any time. A warning or suggestion to add at build/serve time is fine,  it should have a `-silent` option. 

It has been ages since I've had a framework modify configuration files past the initialization in setup. This is really making Next v13 and the app directory unusable.

**Comment by sidewaiise** [comment]
### Is anyone working on a PR? I'm happy to look into a fix if not??
Yep, can confirm this is the exact thing I've just experienced. New to NX, and this is a pretty bad first experience.

Will try using the exclude hack that everyone else has been using.
