### ISSUE TITLE
React-icons does not work with next js 13.1

### ISSUE THREAD

**Issue by reyangurjar** [vercel/next.js#44441]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

**Operating System:**
      Platform: linux
      Arch: x64
      Version: #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022
**Binaries:**
      Node: 16.19.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.18.2
 **Relevant packages:**
      next: 13.1.1
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/reyangurjar/miyou.me 

### To Reproduce

I prefer you to use codespace but i have gave the repository link.

### Describe the Bug

I am using the 4.7.1 version of react-icons. And converting the react app into next js. So while doing that i encountered this error in terminal "(node:4625) [DEP0128] DeprecationWarning: Invalid 'main' field in '/workspace/Miyou.me/node_modules/react-icons/package.json' of 'lib'. Please either fix that or report it to the module author.". And when i ignored the warning 
And yes i don't know if it is the problem with next js.

### Expected Behavior

React-icons work fine with next js 13

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

yarn dev

**Comment by ozcancelik** [comment]
I guess it's just a development warning. Not effecting the code. If you want to hide it, you can change code in 
**/node_modules/react-icons/package.json** `"main": "lib"` to `"main": "./lib/cjs/index.js"`.  It's temporary hide the warning. When npm install it will restore bugged version. But I don't know why it's happen. It looks a bug of react-icons. 

Also I think your real problem is about using `useWindowSize()` hook. It's not SSR compatible. You can use custom `useSsrCompatible()` hook to make it compatible. 

Create a new file `hooks/useSsrCompatible.js` and paste the following code:

```
import { useState, useEffect } from "react";

export function useSsrCompatible(newValue, initialValue) {
    const [value, setValue] = useState(initialValue);
    useEffect(() => {
        setValue(newValue);
    }, [newValue]);
    return value;
}
```
Then import it in your component. Use it like this:

`const [width, height] = useSsrCompatible(useWindowSize(), [0, 0]);`

I hope it helps.

You can also check this issue:
[https://github.com/jaredLunde/react-hook/issues/163](https://github.com/jaredLunde/react-hook/issues/163)

**Comment by reyangurjar** [comment]
Yeah i figured that out that it was a use Window size hook so This will definetly work = 

`import React,{useEffect,useState} from "react";
export default function useWindowSize() {
    // Initialize state with undefined width/height so server and client renders match
    // Learn more here: https://joshwcomeau.com/react/the-perils-of-rehydration/
    const [windowSize, setWindowSize] = useState({
      width: undefined,
      height: undefined,
    });
  
    useEffect(() => {
      // only execute all the code below in client side
      if (typeof window !== 'undefined') {
        // Handler to call on window resize
        function handleResize() {
          // Set window width/height to state
          setWindowSize({
            width: window.innerWidth,
            height: window.innerHeight,
          });
        }
      
        // Add event listener
        window.addEventListener("resize", handleResize);
       
        // Call handler right away so state gets updated with initial window size
        handleResize();
      
        // Remove event listener on cleanup
        return () => window.removeEventListener("resize", handleResize);
      }
    }, []); // Empty array ensures that effect is only run on mount
    return windowSize;
  }`
