### ISSUE TITLE
Docs: Is the port property necessary for remote patterns

### ISSUE THREAD

**Issue by IDrumsey** [vercel/next.js#44660]
### What is the improvement or update you wish to see?

The docs on configuring remote patterns shows using the port number property as an empty string,

```javascript
{
    protocol: '...',
    port: '',
    hostname: '...',
    pathname: '...'
}
```

 but when I run `next run dev` I get a warning

```
warn  - Invalid next.config.js options detected: 
  - The value at .images.remotePatterns[...].port must be 1 character or more but it was 0 characters.
```

Should I just omit the port property. If so, maybe adding some documentation for that would be good.

### Is there any context that might help us understand?

no

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/next/image#remote-patterns

<sub>[NEXT-2016](https://linear.app/vercel/issue/NEXT-2016/docs-is-the-port-property-necessary-for-remote-patterns)</sub>

**Comment by styfle** [comment]
The `port` is not required, but it is strongly recommended.

In fact, every prop in `remotePatterns` is strongly recommended to protect your application from malicious users. 

Note that `port: ''` is not the same as `port: undefined` because undefined is effectively a wildcard. When you use `port: ''`, that means you allow images from https://example.com/img.png, but not https://example.com:22/img.png

I'll make sure the json schema is correct and the docs explain this better, thanks!

**Comment by styfle** [comment]
I'm not seeing that warning anymore with the latest Next.js (14.0.4) so that issue is likely fixed.

I'll update the docs in PR #60387, thanks!
