### ISSUE TITLE
Dynamic routes failing in 13.1.2 "Error: invariant: invalid Cache-Control duration provided: 0 < 1"

### ISSUE THREAD

**Issue by DavidTParks** [vercel/next.js#44875]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.3-canary.0
      eslint-config-next: 13.0.5
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/DavidTParks/vamp

### To Reproduce

Clone the repository, run `npm run build` and try to navigate to a dynamic route. It will error out and throw in the terminal 

```
Error: invariant: invalid Cache-Control duration provided: 0 < 1
```

### Describe the Bug

The bug seems to happen when navigating to a dynamic route. Occurs only in production, both locally building and on Vercel. 

```
Error: invariant: invalid Cache-Control duration provided: 0 < 1
```

When trying to navigate via a next/link to a dynamic route. 

### Expected Behavior

Route to the route without throwing

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by erhise** [comment]
+1

**Comment by s4pp1** [comment]
I have the same error. +1

**Comment by codeh007** [comment]
+1

**Comment by schimi-dev** [comment]
+1

**Comment by focux** [comment]
I'm having the same issue. Had to downgrade next to 13.1.1 and it's working back again.

**Comment by lassegit** [comment]
@focux Same here. Deployed 13.1.2 to production late friday afternoon 😂.

**Comment by yajinn** [comment]
+1

**Comment by tolerance-go** [comment]
+1 @focux  works for me, to downgrade 13.1.1

**Comment by DavidTParks** [comment]
> +1 @focux works for me, to downgrade 13.1.1

Yep downgraded for now

**Comment by schimi-dev** [comment]
Hi,
just for your information, doing `export const revalidate = 0`  as described [here](https://beta.nextjs.org/docs/api-reference/segment-config#revalidate) in all pages and layouts that have to be dynamic solved the problem for me. Maybe that helps some of you too.

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.1.3-canary.5` of Next.js to show a proper error explaining what is occurring better. 

The problem here is that the dynamic path is being statically generated during the build and then dynamic server methods are being used during runtime e.g. `cookies()` or `headers()` from `next/headers`. 

If these are being used in a shared library and the page is meant to be statically generated then `export const dynamic = 'force-static'` can be used to prevent this error or alternatively if the page isn't meant to be statically generated and these methods are needed `export const dynamic = 'force-dynamic'` can be leveraged.
