### ISSUE TITLE
getStaticProps runs code as client and fails.

### ISSUE THREAD

**Issue by agamm** [vercel/next.js#45200]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Nov 23 01:01:46 UTC 2022
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.5
      eslint-config-next: 13.1.5
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/jovial-gwen-sgtuet?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A10%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A10%2C%22startLineNumber%22%3A13%7D%5D

### To Reproduce

Create a page with `getStaticProps` and link the render of it to some code that can only be run in the server. Note, I haven't supplied `"use client;"` anywhere in the code and am assuming that all code should run on the server and not the client.

### Describe the Bug

Code that should only be run on the server is run on the clinet.

### Expected Behavior

If I run a page via `getStaticProps` I'm assuming that the code will only run on the server. Unless I specificy `use client`.

### How are you deploying your application? (if relevant)

Codesandbox

**Comment by ArthurDinalli** [comment]
Next.js will pre-render this page at build time using the props returned by getStaticProps. (https://nextjs.org/docs/basic-features/data-fetching/get-static-props)
This means that whenever you`re building your application, nextJs will generate this static page and hydrate with whatever props you`re passing.
If you want it to run on server, you should try using `getServerSideProps`

**Comment by avanrish** [comment]
I think it works as expected, because as far as I know, `pages/` directory supports only client components. Server components have been moved to `app/` directory after v12.2.0  [#38979](https://github.com/vercel/next.js/issues/38979) and you can create them only there, components created anywhere else are considered client components by default.

**Comment by agamm** [comment]
@ArthurDinalli Is there a concept of ISR for `getServerSideProps`? I don't want to run it on each request.
@avanrish I'm not really educated on them, will they allow me to generate the component on the server and use ISR to regenerate every x seconds?

**Comment by avanrish** [comment]
@agamm I don't know what your use case is, but if it's not user-specific, you can run your server code in `getStaticProps` [(codesandbox)](https://codesandbox.io/p/sandbox/focused-panka-g8icdu?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A2%2C%22endLineNumber%22%3A3%2C%22startColumn%22%3A2%2C%22startLineNumber%22%3A3%7D%5D) and use ISR to update every x seconds, but if what you want to achieve is user-specific, then you have to use `getServerSideProps`, which doesn't have any concept of ISR, because `getStaticProps` is for that.
You could also try out new [`app/`](https://beta.nextjs.org/docs/rendering/fundamentals) directory where you can use server components like you intended to do in provided codesandbox.

**Comment by agamm** [comment]
@avanrish The reason I need that is because I don't want to rehydrate. I want everything to be statically generated on the server and ready to be presented on the client as a static page. ISR I need, so I don't generate it on each request and I harness the CDN and caching optimizations available.

**Comment by avanrish** [comment]
If you want a static page then you can achieve it easily with getStaticProps by passing data to props. 
For the `app` directory, you need to enable it in next.config.js, create Root Layout and the Page in there (see [docs](https://beta.nextjs.org/docs/upgrade-guide#migrating-from-pages-to-app)), and move your Testme component into app directory, it should work then.
No idea when it comes out of beta, probably when they finish and test all the features on the roadmap

**Comment by agamm** [comment]
Awesome, I'll dive deeper into that. I would recommend highlighting that js will run (hydration) in the `statisprops` [docs page](https://nextjs.org/docs/basic-features/data-fetching/get-static-props) though.
