### ISSUE TITLE
[NEXT-657] When going back from a page that doesn't exist, it downloads a file

### ISSUE THREAD

**Issue by Dragonaere** [vercel/next.js#45595]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

**Operating System:**
      Platform: linux
      Arch: x64
      Version: #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023
**Binaries:**
      Node: 18.13.0
      npm: 8.19.3
      Yarn: N/A
      pnpm: N/A
**Relevant packages:**
      next: 13.1.7-canary.5
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link), Turbopack (--turbo)

### Link to the code that reproduces this issue

https://github.com/Dragonaere/wyvern/tree/bug

### To Reproduce

Create a link using `next/link` that leads to a route with just a folder, no `page.js` file. Click the link and try using the back button. It should download a file called `download`. A route that doesn't exist at all works as expected, as does a route with

### Describe the Bug

When you have a folder in the `app/` directory but no `page.js`, `layout.js`, etc, when hitting the back arrow after going to that route, instead of going back, it downloads a file called `download` which contains this: `J0:[["children","",["",{}],null,null]]`. If you go to a route that doesn't exist at all, the back arrow works as expected.

### Expected Behavior

It should just go back to the previous page

### Which browser are you using? (if relevant)

Chromium 109.0.5414.119

### How are you deploying your application? (if relevant)

next dev --turbo

<sub>[NEXT-657](https://linear.app/vercel/issue/NEXT-657/when-going-back-from-a-page-that-doesnt-exist-it-downloads-a-file)</sub>

**Comment by Dragonaere** [comment]
A few extra things:

- This only happens with next dev --turbo
- It also only happens when the route with only a folder is the most recent page visited. If you type in another route that exists and the go back to the non-existant route, and then back again, which would normally download the file, it works as expected.

**Comment by mstrokin** [comment]
Happens to me without turbopack too

**Comment by valid-void** [comment]
I experience the same behavior.
There is no problem when navigating through the menu and links on the website. I can return to any page with no problems.

But as soon as I change the URL manually, there are problems.

Instead of going back, it downloads a file with the name of the route/segment I want to go back to.

### To Reproduce
1. Open `https://example.com/page1`
2. Modify URL by hand to `https://example.com/page2`
3. Click on Back Button
**Result:** Downloading a file named `page1` which contains a similar structure like  `J0:[["children","",["",{}],null,null]]`

(If I change the URL and start navigating the site, I can return to any page. Everything works as expected. But as soon as I reach the point in history where the URL was changed, a file downloads.)

Any ideas why this is happening?

#### additional infos:
- Locelhost doesn't show this behavior. It happens only when deployed.
- I am not using 'next dev --turbo'
- only happens when modifing URL manually
- using appDir

**Comment by mstrokin** [comment]
Adding these to layout.js fixes this:
export const dynamic = 'force-dynamic'
export const revalidate = 0

Source: https://beta.nextjs.org/docs/api-reference/segment-config

**Comment by nandap4790** [comment]
@Dragonaere is this issue sorted, because I am facing the issue on page refresh and on forward and back navigation
