### ISSUE TITLE
Images sizes rendering differently on development and production

### ISSUE THREAD

**Issue by nielsreijnders** [vercel/next.js#46186]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.19.0
      npm: 8.0.0
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 13.1.6
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/nielsreijnders/bug-images

### To Reproduce

To reproduce, run locally and check the rendered size, which is around ~400kb. In production the rendered size is around ~900kb. While the image in the CMS is around ~600kb. 

Demo link: https://bug-images.vercel.app/

### Describe the Bug

Images rendering in diffrent sizes. 

### Expected Behavior

Images being lower than the uploaded sizes.

### How are you deploying your application? (if relevant)

Vercel

**Comment by Fredkiss3** [comment]
I don't think this a bug with next but just a browser behavior, when working on my project i ran into similar frustrations because the browser would load a bigger image than needed, twice the size to be correct. It turns out it is because of the screen pixel density in mac being double (i think it is called retina), when you create an image with a fixed size, next insert this `srcset` attribute with 2 urls, one for screens with simple pixel density (`1x`) and double pixel density (`2x` or retina). For the screen of the mac it load the doubled version. this behavior is entirely dependent on the browser. 

```js
srcset="
/_next/image?url=https%3A%2F%2Fadmin.zuiderhaven-alkmaar.nl%2Fwp-content%2Fuploads%2F2023%2F01%2F2021_12_23-V10-P1_3613px_Q10-scaled-1.jpg&w=1920&q=100 1x, 
/_next/image?url=https%3A%2F%2Fadmin.zuiderhaven-alkmaar.nl%2Fwp-content%2Fuploads%2F2023%2F01%2F2021_12_23-V10-P1_3613px_Q10-scaled-1.jpg&w=3840&q=100 2x
"
```

Furthermore, when using nextjs image component if you define an image with a custom width, the `srcset` attribute will have the next biggest size (+ its double) defined in the configuration. You can check the documentation to modify the configuration and choose your image sizes to generate : https://beta.nextjs.org/docs/api-reference/components/image#devicesizes

**Comment by nielsreijnders** [comment]
Thanks, but this is not my issue. I know on a retina it is rendered twice as big. When running it locally it will show a different size with the same width on production. So on Vercel it will show the same image as 1200kb and on localhost it will show it as 400kb. Both with the same width and same quality etc with the same srcset on the same screen.

**Comment by nielsreijnders** [comment]
Thanks for helping but I checked both version in a new tab with the same url like this:

http://localhost:3000/_next/image?url=https%3A%2F%2Fadmin.zuiderhaven-alkmaar.nl%2Fwp-content%2Fuploads%2F2023%2F01%2F2021_12_23-V10-P1_3613px_Q10-scaled-1.jpg&w=3840&q=100

https://bug-images.vercel.app/_next/image?url=https%3A%2F%2Fadmin.zuiderhaven-alkmaar.nl%2Fwp-content%2Fuploads%2F2023%2F01%2F2021_12_23-V10-P1_3613px_Q10-scaled-1.jpg&w=3840&q=100

And this issue still occurs. I didn't compare the headers with each other so I might check those. It a too big of a difference to not look into this.

**Comment by Fredkiss3** [comment]
did you find finally find a solution or figure out the root cause ?
