### ISSUE TITLE
[NEXT-614] Navigation changing just `searchParams` doesn't trigger `loading.tsx`

### ISSUE THREAD

**Issue by jankaifer** [vercel/next.js#46258]
When navigating from foo?page=1 to foo?page=2, the foo/loading.js script is not triggered. Is this normal behavior or a bug?

_Originally posted by @wh5938316 in https://github.com/vercel/next.js/discussions/41745#discussioncomment-4989886_
      

<sub>[NEXT-614](https://linear.app/vercel/issue/NEXT-614/navigation-changing-just-searchparams-doesnt-trigger-loadingtsx)</sub>

**Comment by wh5938316** [comment]
Any updates on this?
It seems that changes to `searchParams` in next.js 13 may not be considered as page changes.
When a Link is clicked and only the `searchParams` are changed, the page does not scroll to the top despite the scroll props being set to `true`.

https://app-dir.vercel.app/snippets/search-params

I'm wondering if this behavior is intentional or a mistake.

**Comment by hoqua** [comment]
Any updates on this?

I guess this feature is must have to consider using the NextJS app dir in production

**Comment by timneutkens** [comment]
On next@canary a fix for the cache key with searchParams was landed: https://github.com/vercel/next.js/pull/47312

However changing searchParams as-is will cause it to match up keys higher up so in some cases you'll have to add a `<Suspense>` boundary that has a `key` where you want to show a boundary if it's changing in a meaningful way.
