### ISSUE TITLE
Turbopack conflicts with Next/Image

### ISSUE THREAD

**Issue by st1ng7ay** [vercel/next.js#46358]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.19.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.27.0
    Relevant packages:
      next: 13.2.1
      eslint-config-next: 13.2.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image), Turbopack (--turbo)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/dreamy-swanson-4uus9p?selection=%5B%7B%22endColumn%22%3A9%2C%22endLineNumber%22%3A20%2C%22startColumn%22%3A7%2C%22startLineNumber%22%3A15%7D%5D&file=%2Fpages%2Findex.tsx

### To Reproduce

switching from <img> to <Image> breaks page

### Describe the Bug

Using Next/Image with Turbopack not work:

- StaticImageData also not generate

- External Image break page with

Error during SSR Rendering
  Error: Invalid src prop 

### Expected Behavior

loading image

### Which browser are you using? (if relevant)

Safari, Chrome

**Comment by limegorilla** [comment]
Might be the same thing I am running into - calls to an S3 bucket using `next/image` are failing:
<img width="2168" alt="image" src="https://user-images.githubusercontent.com/29333568/221165705-80e56d09-0fc4-4891-afec-7165cee15dc7.png">

Working in production though.

To add:
<img width="457" alt="image" src="https://user-images.githubusercontent.com/29333568/221165960-8c979679-13ab-4078-8cef-70dfc25aeafd.png">
Error messages are blank

Site itself gets a 500:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/29333568/221166137-59149dbb-9ebd-40a9-b1bf-a53bba1689e6.png">

I can't expose my project directly, but everything is implemented as standard - `next.config` is setup correctly and no changes have been made to the project since this was working yesterday - including no modifications that I can tell of to my `node_modules`

**Comment by limegorilla** [comment]
Anyone have an update on this?
