### ISSUE TITLE
Router's bug when accessing static html generated by next export.

### ISSUE THREAD

**Issue by shiruco** [vercel/next.js#46376]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.19
      pnpm: 6.32.8
    Relevant packages:
      next: 13.2.1
      eslint-config-next: 13.2.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/shiruco/nextjs_routing_bug

### To Reproduce

Clone repo and run export script:
```
git clone https://github.com/shiruco/nextjs_routing_bug
cd nextjs_routing_bug
pnpm install
pnpm export
```

then, `out` dir is created, so move to `out` dir and start simple http server.
```
cd out
python3 -m http.server 8080
```

and access to `http://localhost:8080/products/search.html`, browser displays content `/products/[id]/index.html`.

### Describe the Bug

Router's bug under certain conditions:

- A rewrites rule is configured in `next.config.js`
- Dynamic routing directory exists on the same directory

### Expected Behavior

browser displays content `/products/search.html`.

### Which browser are you using? (if relevant)

chrome 109.0.5414.87

**Comment by GitRowin** [comment]
What are you expecting to see? `products/search` instead of `products/[id]/index`?

What you are describing is expected behavior. Run the Next.js server instead of the Python server and visit `/products/search.html` and you will get the same result. Next.js does not support the `.html` extension in the request path. Serve the `search.html` file when `/products/search` is requested and it will work.

Also, your rewrite rule makes no difference as far as I can tell. Are you sure it affects anything related to this issue?

**Comment by shiruco** [comment]
@GitRowin 

Thank you for your comment.

> What are you expecting to see? products/search instead of products/[id]/index?

yes

> Next.js does not support the .html extension in the request path. 

I understand about this. However, access to the html file generated through the `next export` command should return the correct content.

> Also, your rewrite rule makes no difference as far as I can tell. Are you sure it affects anything related to this issue?

Please try removing the rewrite rule in `next.config.js`. Then accessing `/products/search.html` will return the correct content.

**Comment by GitRowin** [comment]
I gave it another try and you are right. I must have accidentally tested it with the Next.js server instead of the Python server. Sorry about that.

Seems like your issue is caused by [this if statement](https://github.com/vercel/next.js/blob/69fe4eee39747861bc7bc306ac5ab1a2e5786596/packages/next/src/client/index.tsx#L119). I don't believe this is a bug. As I said before, Next.js does not support the `.html` extension in the request path.

If you must support it for some reason, consider adding this to your `rewrites`:
```js
{
  source: "/:slug*.html",
  destination: "/:slug*",
}
```

**Comment by shiruco** [comment]
> As I said before, Next.js does not support the .html extension in the request path.

Yes, I understand. But why is there a feature `next export`? some users may want to serve the html generated by next export with a simple HTTP server and link directly to the html file. And furthermore, it seems a bit weird that the display of html changes depending on the setting of a completely unrelated rewrites rule. 🤔

**Comment by GitRowin** [comment]
I suppose  `next export` is simply not meant to be used like that. I am using `next export` with a web server that supports serving the HTML files without the `.html` extension in the request path and it works great. A simple web server that can do this is https://github.com/vercel/serve.

Besides, you wouldn't be able to use a simple web server either way because you are using dynamic routes.

**Comment by shiruco** [comment]
> Besides, you wouldn't be able to use a simple web server either way because you are using dynamic routes.

I see. Basically, I understood that html generated by `next export` should not be served on a server such as nginx. Thanks for your comment.
