### ISSUE TITLE
metadata in page.js results in Hydration failed

### ISSUE THREAD

**Issue by alextseitlin** [vercel/next.js#46407]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.2-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-ccnz2u?file=app%2Fpage.jsx

### To Reproduce

add metadata in page.js like it says in the doc result in Hydration failed https://beta.nextjs.org/docs/api-reference/metadata

### Describe the Bug

metadata in page.js like it says in the doc result in Hydration failed

### Expected Behavior

Work

**Comment by huozhi** [comment]
It feels like a stackblitz issue that they inject a script on SSR, but since we don't have it in client it causes mismatch. If you build locally you won't see the hydration errors

<img width="678" alt="image" src="https://user-images.githubusercontent.com/4800338/221362920-9974abb1-94d1-4d50-9f1c-0f79d902d3fa.png">
