### ISSUE TITLE
Unwanted space [Not responsive]

### ISSUE THREAD

**Issue by rohan9024** [vercel/next.js#46768]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
N/A
```

### Link to the code that reproduces this issue

https://nextjs.org/docs/getting-started

### To Reproduce

Visit the link provided and inspect --> select mobile responsive--> select Ipad Air and start scrolling

### Describe the Bug

There is an unwanted space while scrolling 

### Expected Behavior

The search bar and the menu dropdown needs to be shifted upwards .... please assign me

**Comment by ajaysinghpanwar2002** [comment]
Some added an inline css to the class="jsx-8d6c1b2e1604b381 shadow", I can resolve this issue

**Comment by balazsorban44** [comment]
Thanks! I forwarded it to the team responsible.

Tip: You can just report feedback like this using the Feedback button on the website in the future, since this is not a Next.js bug.

![image](https://user-images.githubusercontent.com/18369201/223102591-46150f09-14ef-4e4a-89ad-deb58526fffe.png)
![image](https://user-images.githubusercontent.com/18369201/223102650-ed1c2498-6dce-4811-88c2-ddd87b0ecd58.png)
