### ISSUE TITLE
`crypto` is undefined in API routes (Next13 appDir)

### ISSUE THREAD

**Issue by DominicTobias** [vercel/next.js#46852]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.2
      npm: 9.6.0
      Yarn: 1.22.19
      pnpm: 7.28.0
    Relevant packages:
      next: 13.2.3
      eslint-config-next: 13.2.3
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

http://plz-make-a-appdir-tpl

### To Reproduce

```ts
export async function GET(request: Request) {
  console.log('crypto', crypto)
}
```

### Describe the Bug

`crypto` is undefined in API routes, at least locally when running `dev`. This impacts a lot of things like auth libraries (e.g. oauth would have to use insecure plain code challenge instead of S256). Crypto is a fundamental module for writing secure apps.

### Expected Behavior

Should be able to use `crypto`, it's a browser (V8) supported object.

**Comment by bbsweb** [comment]
I think you should add `export const runtime = 'edge'`

because 'crypto' only work in edge-runtime

**Comment by DominicTobias** [comment]
Thanks that worked! I had no idea Vercel even had a Node runtime. According to the [beta docs](https://beta.nextjs.org/docs/rendering/edge-and-nodejs-runtimes) I put:
`export const runtime = 'experimental-edge'`

**Comment by balazsorban44** [comment]
Keep in mind, Vercel and Next.js are different (although the runtimes should match on both).

Both have however a Node.js runtime, which is the default.

The [Web Crypto API](https://nodejs.org/api/webcrypto.html) in Node.js has been unflagged on `globalThis` since version 19 (so using Node.js 19+ would work in your case, without setting the runtime to edge), in previous versions, you can run the Node.js process with `--experimental-global-webcrypto`, or add the following snippet:

```js
import crypto from "node:crypto/webcrypto"
globalThis.crypto ??= crypto
```

Regarding app repro template, we already have one: https://github.com/vercel/next.js/tree/canary/examples/reproduction-template-app-dir (I'll make sure to add this to the bug report description)
