### ISSUE TITLE
generateStaticParams caches data like forever

### ISSUE THREAD

**Issue by ciruz** [vercel/next.js#47218]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-njkvto?file=app%2F[slug]%2Fpage.tsx,app%2Fpage.tsx

### To Reproduce

In the docs is an example how to use [generateStaticParams](https://beta.nextjs.org/docs/api-reference/generate-static-params) , if you do it like so, the fetched data from this function get really like cached forever.

I made a small reproduction, where I query an API which returns just a simple random number (`https://www.random.org/integers/?num=1&min=1&max=100&col=1&base=10&format=plain&rnd=new`).

I `console.log` this number, if you create a build, you see the random number, if you build again, it will always be the same number, because this data it's somehow cached, by this function. 

![apiresponse](https://user-images.githubusercontent.com/987947/225751270-7760bf7d-23bf-4641-b794-229c150eb24e.gif)

### Describe the Bug

I noticed the bug since I queried some customers, after changing some of their data (slugs), and creating a new build, I immediately got a build error, because next.js tried to request their data with their old and now unvailable  slugs.

### Expected Behavior

Don't cache data.

**Comment by Fredkiss3** [comment]
Hello, it is not the output of generateStaticParams that is cached, but `fetch`, by default `fetch` caches data forever in the new app router for nextjs. 
Like said in the docs : 

> By default, fetch will automatically fetch and [cache data](https://beta.nextjs.org/docs/data-fetching/caching) indefinitely.
> ```js
> fetch('https://...'); // cache: 'force-cache' is the default
> ```

from here : https://beta.nextjs.org/docs/data-fetching/fetching#static-data-fetching

And with the new caching methods coming to nextjs, they will cache the response even between different builds, until revalidated. more on here : https://vercel.com/blog/vercel-cache-api-nextjs-cache#the-next-generation-of-isr-next.js-cache


Anyway the solution to your problem is just to instruct nextjs to not cache the response to fetch by adding a `{  cache: 'no-store'  }` option to the fetch :

```ts
export async function generateStaticParams() {
  const posts = await fetch(
    'https://www.random.org/integers/?num=1&min=1&max=100&col=1&base=10&format=plain&rnd=new', {
      cache: 'no-store' // <==== this is your solution
    }
  ).then((res) => res.json());

  console.error('\n\napi response from generateStaticParams', posts, '\n\n');

  // just that the build don't fail...
  let foobar = ['test'];
  return foobar.map((post) => ({
    slug: post,
  }));
}

```

**Comment by ciruz** [comment]
@Fredkiss3 thank you for clearing things up.
