### ISSUE TITLE
Docs: Release notes should be more concise 

### ISSUE THREAD

**Issue by CodingSpiderFox** [vercel/next.js#47558]
### What is the improvement or update you wish to see?

Next 13.1.2 itself is a very long changelog: https://github.com/vercel/next.js/releases/tag/v13.1.2
Some things could be compacted into single bullet points.
For example: 
chore: improves console warnings related to edge runtime: https://github.com/vercel/next.js/pull/44563
chore: fix typo: https://github.com/vercel/next.js/pull/44761

Could be: 
chore: improves console warnings related to edge runtime and fix typs: #44653 #44761

Also, for the regular developer just using next.js "fix typo" is somewhat irrelevant sometimes.

Also if I got this right, these two lines could just be removed because if that change got reverted, there should be no effect

chore: Update swc_core to v0.53.0: https://github.com/vercel/next.js/pull/44707
Revert "chore: Update swc_core to v0.53.0": https://github.com/vercel/next.js/pull/44760

Also, the canary releases showing up on github are irrelevant to many people. 

Please consider writing a concise changelog on the next.js web page :)

### Is there any context that might help us understand?

I am upgrading dependencies in our monorepo. 
There are a lot of changelogs of different libs I have to read.

**Comment by CodingSpiderFox** [comment]
Just out of curiosity I looked at [v13.0.0](https://github.com/vercel/next.js/releases/tag/v13.0.0)

I would like to have the breaking changes as a separate section: 

Breaking Changes 
* Core: Rename next/image to next/legacy/image & rename next/future/image to next/image: [#41399](https://github.com/vercel/next.js/pull/41399)

Core Changes
* non-breaking changes list

**Comment by Fredkiss3** [comment]
I think release notes are generated automatically and not written by hand, so it is normal that it includes all the commit messages in it.

Certains releases notes, like for `13.2.0`, can be very long because there was many canaries between the versions and many commits in it.

I can assure you that canary releases are very relevant for many people (me  for ex), they contains some bugfixes that are very important for people already using next in production. waiting for fixes between stable releases are sometimes a pain as you want a fix to a bug as early as possible because sometimes some of them can significantly slowdown development time. Stable releases seem to take a long time in the next app router, and many bugfixes are introduced in canaries. 

I suppose when the app router goes out of the beta, there will be less canaries and more stable releases and you won't need to update that often.

**Comment by leerob** [comment]
We recommend reading the release blog posts on https://nextjs.org/blog 🙏
