### ISSUE TITLE
App dir standalone doesn't load statics in monorepo

### ISSUE THREAD

**Issue by aspirisen** [vercel/next.js#47799]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.5.0
      npm: 9.3.1
      Yarn: 1.22.19
      pnpm: 8.1.0
    Relevant packages:
      next: 13.2.5-canary.25
      eslint-config-next: 13.2.5-canary.25
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/vercel/examples/tree/main/solutions/monorepo

### To Reproduce
Add output standalone
Run build in example
Start standalone server `solutions/monorepo/apps/app/.next/standalone/apps/app/server.js`

### Describe the Bug

Because the server is running not in `.next` folder all the assets can't be loaded in browser
![image](https://user-images.githubusercontent.com/3620639/229313237-9bf67c9b-f78a-469f-b37d-d1d4e3015026.png)

### Expected Behavior

Standalone server should load all statics

**Comment by draphikas** [comment]
I have the same issue but with classic repo

**Comment by rusted-love** [comment]
I'm surprised nobody cares about such a weird bug. Our team is stuck on Next@13.4.19; any newer minor version throws a 404 error for static files. We cannot upgrade to Next.js 14.

**Comment by adarnon** [comment]
Are you running an Express server? We ran into this issue when upgrading from 13.4 to 13.5.

Bottom line, I think that was happened was that Next changed some routing behavior to happen async, so putting the Next handler directly in an Express router (like we did before) didn't work. We added the following async wrapper:

```
function expressAsyncHandlerWrapper(handler) {
  function innerHandler(req, res, next) {
    Promise.resolve(handler(req, res, next)).catch(next);
  }

  return innerHandler;
}
```

And then added the Next handler this way:

```
expApp.all(
  '*',
  expressAsyncHandlerWrapper(async (req, res) => {
    const parsedUrl = parse(req.url, true);
    await handle(req, res, parsedUrl);
  }),
);
```

**Comment by rusted-love** [comment]
> Are you running an Express server? We ran into this issue when upgrading from 13.4 to 13.5.

@adarnon We are experiencing such behavior by deploying a "standalone" mode with the `next start` command on DigitalOcean.

**Comment by paolomainardi** [comment]
Sadly, coming here to say that I am facing the same issue with NextJS 14 and a docker container, the local paths seem to be fine, as described here: https://github.com/vercel/next.js/issues/49283#issuecomment-1883541258

**Comment by samcx** [comment]
Hi everyone—

The static files are `404`ing because with `output: 'standalone'`, we automatically create a standalone folder that copies only the necessary files for a production deployment including select files in `node_modules`.

The minimal server does not copy the public or .next/static folders by default as these should ideally be handled by a CDN instead, although these folders can be copied to the standalone/public and standalone/.next/static folders manually, after which server.js file will serve these automatically.

To copy these and then start this local minimal server locally, you can do something like this:

```
pnpm build && cp -r public .next/standalone/ && cp -r .next/static .next/standalone/.next/ && node .next/standalone/server.js
```

- https://nextjs.org/docs/app/api-reference/next-config-js/output#automatically-copying-traced-files

I have also just created a PR to update our documentation with this → https://github.com/vercel/next.js/pull/72432.

I will closing this PR since this is a non-issue (tested with v14 and above).
