### ISSUE TITLE
In version of next 13.3.0, when you build and run with standardone, you will find that you cannot find the file.

### ISSUE THREAD

**Issue by seung-juv** [vercel/next.js#48052]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
    Binaries:
      Node: 16.18.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.0
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Standalone mode (output: "standalone")

### Link to the code that reproduces this issue

https://github.com/kingsky32/next-13-3-0-output-standalone-test

### To Reproduce

npx create-next-app@latest --experimental-app 

then add nextConfig option output standalone in next.config.js

then yarn build

then node ./.next/standalone/server.js

![image](https://user-images.githubusercontent.com/46600342/230517395-93656650-0da2-4a3c-bb6b-26764799519f.png)

### Describe the Bug

In version of next 13.3.0, when you build and run with standardone, you will find that you cannot find the file.

### Expected Behavior

File must be read normally

### How are you deploying your application? (if relevant)

node ./.next/standalone/server.js

**Comment by amerbilic** [comment]
I have the exact same issue in my code. Running standalone creates this problem. Do we know if it's fixed in any of the canary releases?

**Comment by lucasassisrosa** [comment]
I had the exact same issue. What I noticed is that `'standalone'` config started to yield a different structure on `.next` folder. In my case, since it was a monorepo,  `'standalone'` put all monorepo packages inside `.next`

![image](https://user-images.githubusercontent.com/49399224/231865560-59c1852e-72b7-4f46-b372-c95044077bf7.png)

What I did to prevent this issue from happening was using the `outputFileTracingRoot` option: https://nextjs.org/docs/advanced-features/output-file-tracing#caveats

I set it to be `'./'` in my `next.config.js` file. With that, the build did ran, but I ended up having the same issue as this one https://github.com/vercel/next.js/issues/45258
