### ISSUE TITLE
Error Invariant: missing action ID

### ISSUE THREAD

**Issue by UAHector** [vercel/next.js#48204]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.3
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/UAHector/nextjs-bug-report.git

### To Reproduce

Run and navigate to the main page.
Complete and submit the form.

### Describe the Bug

_After upgrading to next 13.3 I get the following error when redirecting from the new route handlers api using NextResponse.redirect_: **Invariant: missing action ID**
<img width="719" alt="image" src="https://user-images.githubusercontent.com/74779764/230958683-c883623b-f13d-40fc-b9b7-6c70905c9850.png">

==========================================
error - Error: Invariant: missing action ID.
    at Object.handleAction (C:\Users\Documents\GitHub\nextjs-bug-report\node_modules\next\dist\server\app-render\action-handler.js:60:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async wrappedRender (C:\Users\Documents\GitHub\nextjs-bug-report\node_modules\next\dist\server\app-render\app-render.js:966:37)
    at async doRender (C:\Users\Documents\GitHub\nextjs-bug-report\node_modules\next\dist\server\base-server.js:936:34)
    at async cacheEntry1.responseCache.get.incrementalCache.incrementalCache (C:\Users\Documents\GitHub\nextjs-bug-report\node_modules\next\dist\server\base-server.js:1059:28)
    at async C:\Users\Documents\GitHub\nextjs-bug-report\node_modules\next\dist\server\response-cache\index.js:83:36 {
  digest: undefined
}

### Expected Behavior

It is expected to be able to redirect to another page from the api
<img width="340" alt="image" src="https://user-images.githubusercontent.com/74779764/230960061-2479b532-c8d8-4afe-bba6-f000c705948b.png">

**Comment by LouisDelbosc** [comment]
I encounter the same issue don't know how to fix this.

**Comment by ram-manthry** [comment]
getting same issue. here's how my route looks:

```
req.nextUrl.pathname = `/success`;
return NextResponse.redirect(req.nextUrl);
```

**Comment by iand675** [comment]
Workaround discovered: use a regular response object.

``` typescript
  return new Response(null, {
    status: 302,
    headers: {
      'location': url.toString(),
    }
  })
```

**Comment by coreydunkin** [comment]
I'm currently experiencing this issue when exposing the response.status code into an error component:

error displays:
`async function getPage(pageId: string) {
    const res = await fetch(PAGE_URL);
    return { status: res.status, page: !res.ok ? undefined: await res.json() };
}`

error doesn't display: 
`async function getPage(pageId: string) {
    const res = await fetch(PAGE_URL);
    return res.json();
}`

However the first option is needed so I can pass through the status for error page handling.

**Comment by ValentineStone** [comment]
@UAHector, people, I found out what the issue is

`NextResponse.redirect` uses `307` HTTP status code, that preserves the `POST` request method that you have in your api route. Thus when you redirect from your api route to a page the nextjs server gets a `POST` request for the page and not a `GET` request, and does not know what to do with it. Heres their rationale why they did so:

https://nextjs.org/docs/api-reference/next/server#why-does-redirect-use-307-and-308

The article above advises for our use case to use the `303` status code, but does not specify how, and in fact i could not find anywhere in the docs how to do it, but after looking through the source code i found out that you can supply a second argument to `NextResponse.redirect` to specify status code. I did it and the issue resolved itself.

Try and edit your route code as follows and see if the fixes your issue:

```typescript
import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const body = await request.formData();
    const movie = body.get("favorite-movie");
    const redirectTo = new URL("/movie/", request.url);
    redirectTo.searchParams.set("favorite", movie.toString());
    return NextResponse.redirect(redirectTo, 303); // <------- here, inserted status code 303 afer url
  } catch (err) {
    console.error(err);
    return NextResponse.json(
      {
        message: "Ups! El servidor no responde, intenta más tarde",
      },
      {
        status: 500,
      }
    );
  }
}
```

As for the error itself, its name is very unintuitive, but basically because you are running a Nextjs server, when it redirects a `POST` request to your page the server sees that the request is not `GET` and thinks that you do not want the page to be served, but insted some internal processing to happen and that the request is some internal nextjs workings, referred to as actions. It looks for the internal id of the action that all internal requests have, but does not find any (because it is not internal request, it is your simple redirect) and anounces the freakout concerning that to you in an error message. When you fix the redirect to do a `GET` request the issue disappers as now nextjs server will just serve the page you requested.

Also when **somebody from nextjs dev team reads this** - add how to use a custom status code in `NextResponse.redirect` to the docs guys, am also pretty sure the second parameter can be an object with a lot of cool keys to customize the redirect, thanks is advace!

**Comment by shuding** [comment]
Thanks for opening the issue, we will have this fixed!
