### ISSUE TITLE
[NEXT-1028] App directory: Next 13.3.x redirect() to page with dynamic data causes fetch to fail in Safari

### ISSUE THREAD

**Issue by pmarsceill** [vercel/next.js#48309]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.5
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/cranky-alex-4xgl9k?selection=%5B%7B%22endColumn%22%3A2%2C%22endLineNumber%22%3A10%2C%22startColumn%22%3A2%2C%22startLineNumber%22%3A10%7D%5D&file=%2Fapp%2Fpage.tsx

### To Reproduce

- Using Next 13.3.x
- In production mode (`npm run build && npm run start`)
- A page has a `redirect('/some/other/page')`
- The target page ('/some/other/page') has server side data fetching via `fetch`

Using the code sandbox above, start the instance in production mode and go to the root page that has has the redirect in the Safari. See the redirect attempt fail causing a cascade of retries via fetch.

### Describe the Bug

IF there is a server-side redirect using `redirect()` and the redirected target page has a `fetch()` with server side dynamic data via `fetch()`, the initial redirect will fail, the RSC will fail to load, and there will an loop of retries. 

https://user-images.githubusercontent.com/896475/231565516-f1bf0687-b417-4277-bacb-decd39319035.mp4

### Expected Behavior

In Safari in production `redirect()` behaves as intended (sends user to the redirected page), even if the redirected page has dynamic data.

### Which browser are you using? (if relevant)

Safari version 16.4 (18615.1.26.11.23)

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-1028](https://linear.app/vercel/issue/NEXT-1028/app-directory-next-133x-redirect-to-page-with-dynamic-data-causes)</sub>

**Comment by chungweileong94** [comment]
Yeah, I thought I was using `redirect()` incorrectly, or some bugs caused by recent Safari update, but it doesn't seem like it. As soon as the `redirect()` hit, an infinite loop will start happening.

FYI, I'm using Next v13.3.0.

**Comment by sophiebits** [comment]
Clues: If you enable "Preserve log" in the developer console, you'll see many errors of the form:

```
Fetch api cannot load /whatever/the/page/is due to access control checks
```

with it falling back to MPA navigation due to being caught here:

https://github.com/vercel/next.js/blob/fa821702e57062ae0323bd05ac2891368eae392e/packages/next/src/client/components/router-reducer/fetch-server-response.ts#L92

Unclear yet why it is failing though. You'd think CORS wouldn't be an issue because it is same-origin.

**Comment by sophiebits** [comment]
I spent a few hours today tracking this down with a debug build of WebKit in lldb 😄. I think I now understand what is happening and it is indeed related to #48438:

1. `/` begins loading
2. `<meta http-equiv="refresh" content="0;url=/redirected/123/"/>` initiates the location change
3. JS initializes and Next's RedirectErrorBoundary calls `router.replace()`
4. As part of the router rerendering, `fetchServerResponse('/redirected/123')` calls `fetch('/redirected/123', {headers: {RSC: '1', ...}, ...})`
5. Safari knows the current page is already unloading and so there's no use in sending new resource requests. It fails the fetch request immediately (_WebKit's `CachedResource::failBeforeStarting` is called because `frameLoader.state() == FrameState::Provisional`, then confusingly `CachedResource::requestResource` sees the response failed synchronously and incorrectly assumes it's an access control error, hence the message in the console_)
6. fetchServerResponse catches the fetch() error and falls back to MPA navigation
7. The router's current state update completes, and it calls `location.replace()` in an effect. This cancels the browser's in-progress redirect and starts a new one.
8. But at the same time, RedirectErrorBoundary has reset itself. So the redirect error is once again thrown (technically, I believe this next throw happens prior to the `location.replace()` effect, as part of the the previous `router.replace(); reset();` transition) and HandleRedirect, which has now mounted anew for another time, triggers a `router.replace()` yet again. Goto step 4. Loop. The browser kinda hangs. Weep.

So fetchServerResponse() fails each time it's called (because the page is already unloading due to the meta redirect and/or location.replace()), but we keep calling location.replace() in a loop, fast enough that it never has a chance to finish (if I'm not mistaken, the JS event loop here never cedes control to the browser).

Unlike in #48438, React's infinite loop failsafe does not kick in, because the rerender is actually asynchronous (the router's logic uses async/await), so this happens in perpetuity forever. (I talked to @acdlite who said we might change React to catch a loop of updates separated by microtasks in the future).

As best I can tell, Chrome, in comparison, does not make fetch() fail on an unloading page, and even if it did, it also throttles location.replace() after a while (crbug.com/1038223).

fyi @timneutkens (hope you don't mind the tag but I thought you'd be interested)

**Comment by pmarsceill** [comment]
@timneutkens Any idea when a fix might hit canary? Trying to figure out if I need to hack together a temple workaround instead of using `redirect()` here.

**Comment by sophiebits** [comment]
@franzwarning I haven't had the chance to look for or find a workaround for this.

---

For whoever works on this, likely worth looking at the same time at #48438 where I detailed a couple other oddities with router redirect handling.

**Comment by chungweileong94** [comment]
Interestingly, I not longer have the issue after upgrading to the latest version🤔

**Comment by iwillwen** [comment]
Same issue on it. This bug will cause iOS Safari refresh many times.

**Comment by iwillwen** [comment]
BTW, if the search params in the url including some unicode char(like Chinese, even URIEncoded).

The method `fetchServerResponse` adds the parsed query object into the headers. And it will cause `Failed to read the 'headers' property from 'RequestInit': String contains non ISO-8859-1 code point.`

**Comment by sophiebits** [comment]
@iwillwen The encoding thing sounds separate so you may want to file a new issue for that.
