### ISSUE TITLE
minimum Node.js version of Next.js 13 is 18?

### ISSUE THREAD

**Issue by KKzLEO** [vercel/next.js#48761]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.0
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

can't reproduce in sandbox

### To Reproduce

nvm use 16.20 or 16.15
yarn build

### Describe the Bug

Thanks for providing such a great framework,

I tried to upgrade Next.js from 12 to 13, but encountered an error when `yarn build` in Next 13, the error is
```
Error occurred prerendering page "{{path}}". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: First parameter has member 'readable' that is not a ReadableStream.
```

after upgrading Node from 16.15 to latest version(18.16), it's fixed. But the migration docs claims the minimum Node.js version of Next.js is 14.18.0. https://nextjs.org/docs/upgrading#v13-summary

is the docs wrong or it's the bug that should be fixed?

### Expected Behavior

yarn build successfully

**Comment by iamnewton** [comment]
Got the same issue as you @KKzLEO

**Comment by stefann42** [comment]
Adding a data point since I came across this issue searching for another problem related to nextjs and `readable` streams. We can run nextjs v.13.0.2 on Node 16.16, but upgrading nextjs past that version produces errors in libraries that depend on `Readable` streams. This may be something related to how nextjs overrides the globals and messes with `fetch` which returns and `Readable` streams and less about Node 16 vs. 18.

**Comment by samcx** [comment]
@KKzLEO Yes, the minimum version for v13+ is **18.17** → https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#nodejs-version.
