### ISSUE TITLE
cache working only client side

### ISSUE THREAD

**Issue by darklight9811** [vercel/next.js#48762]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Mon Apr 24 2023 02:05:22 GMT-0300 (Horário Padrão de Brasília)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 8.2.0
    Relevant packages:
      next: 13.3.1-canary.19
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-bxrgfc?file=app/page.tsx

### To Reproduce

Create a callback function that is wrapped by cache and has primitives as arguments (as spec proposes). Make it server side (app dir).

### Describe the Bug

The method is not cached unless on client side (that actually throws an error saying it wasn't implemented.

### Expected Behavior

The random method return the same value if the arguments are the same.

**Comment by darklight9811** [comment]
Actually something weirder seems to be happening, I don't know if its OS related, but on some computers/situations. Cache seems to work serverside too.

**Comment by samcx** [comment]
@darklight9811 Since the <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> is `404`ing and this issue is likely stale, I will be closing this issue!

If you are still experiencing issues with the latest, please re-submit a [new issue](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml).
