### ISSUE TITLE
Docs: Authentication in App Router

### ISSUE THREAD

**Issue by christianjuth** [vercel/next.js#48988]
### What is the improvement or update you wish to see?

The new app directory feels very intuitive, but I'm uncertain about how to handle data fetching in some cases.

When using Server/Client components, it makes sense that some data should be fetched on the server, while other data should be fetched on the client. This is straightforward for unauthenticated data, but it becomes more complicated when interacting with an authenticated API. I'm curious if the Next.js team has any suggestions for handling authentication in a way that allows authenticated fetch requests to be made from both the user's browser and the server (using await in Server components).

Assuming I'm using cookies to store auth sessions, when a user logs in, I need to set a cookie between my browser and the API host (assuming I'm not using Next.js API routes) and also expose that cookie to my Next.js site for fetching within Server components.

While I could potentially create a workaround that sets dual tokens between the `browser => API`, and the `browser => Next.js => API`, I'm concerned about the security of this approach. I believe this may be a common problem for people creating new Next.js apps, so I thought it might be worth documenting.

Although this isn't a new issue, some clarity would be appreciated.

### Is there any context that might help us understand?

For context, I wan't to be able to fetch data in both ways. I need to expose an auth/session token so both the Server and Client components. 

```javascript
async function ServerComponent() {
  const promise = await fetch(
    // ... request authenticated with cookie
  )
  
  return <span>...do something with data</span>
}
```

```javascript
const promise = await fetch(
  // ... request authenticated with cookie
)

function ClientComponent() {
  const data = use(promise)
  return <span>...do something with data</span>
}
```

<sub>[DX-1815](https://linear.app/vercel/issue/DX-1815/docs-authenticated-data-fetching-in-server-and-client-components)</sub>

**Comment by swve** [comment]
I agree this is truly a blocker for apps that need to reach authenticated API routes.

Most of the time and for security reasons,`HttpOnly` is used when a cookie is set from a backend server to make sure the cookies are not accessed by javascript in the client https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies, however the cookies are still sent with requests which are used by the backend to authenticate requests.

Now that these requests are sent from the Next.js Server, these cookies are no longer sent with the requests and there is no way to send them because it means you have to access cookies from client-side js and you can't because of `HttpOnly`,  sure we can explore using `localStorage` or try to find new techniques to securely authenticate routes but it would take a lot of refactoring updates and possibly breaking changes.

The issue here is that so many features in the App router are now server-only, like dynamically adding a title to a page (metadata) and even if the docs say that you can gradually migrate to App router you just can't, there isn't this modularity anymore that we had with the Pages directory imho.

Now that this is the case I think too that we really need a guide on how to do this properly or at least some help for folks that are going to start their apps using the App Directory

**Comment by gmoniava** [comment]
Just want to add to this. There seems to be missing documentation about authentication in general for the app router. For pages router, there is such doc: https://nextjs.org/docs/pages/building-your-application/routing/authenticating

**Comment by JaffParker** [comment]
It seems that in most cases we can rely on nothing but `headers()` and `cookies()`. I can't find how to create a context on a request. Instead, I guess, we'd need to make server functions to validate a session from a cookie every time. Not terrible, just need to make sure to cache sessions.

**Comment by samcx** [comment]
@christianjuth We have an Authentication section now! → https://nextjs.org/docs/app/building-your-application/authentication
