### ISSUE TITLE
Inconsistent CSS rendering on Next.js v13.4 compared to v13.3"

### ISSUE THREAD

**Issue by rajput-hemant** [vercel/next.js#49380]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Thu, 20 Apr 2023 16:11:55 +0000
Binaries:
  Node: 19.9.0
  npm: 9.5.0
  Yarn: 1.22.19
  pnpm: 8.4.0
Relevant packages:
  next: 13.4.1-canary.2
  eslint-config-next: 13.4.1
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/0uh54e

### To Reproduce

- Access the working sandbox with **Next.js 13.3.0**
- Observe the CSS rendering of the swiper component and pagination bullets, confirming that the CSS is working as intended.
- 
[**CodeSandbox**](https://codesandbox.io/p/sandbox/busy-minsky-yrb32y) &nbsp; **[<kbd>**_Live Demo_**</kbd>](https://yrb32y-3000.csb.app)**

- Access the non-working sandbox with **Next.js 13.4.1**
- Observe the CSS rendering of the swiper component and pagination bullets, noting that the padding of the swiper component is not being considered and the pagination bullets are not changing to the rose-500 color as declared in the `globals.css`  file.
- 
[**CodeSandbox**](https://codesandbox.io/p/sandbox/0uh54e) &nbsp; **[<kbd>**_Live Demo_**</kbd>](https://0uh54e-3000.csb.app)**

### Describe the Bug

When using Next.js version 13.4, there is an issue with the way CSS is rendered, specifically with the use of the swiper component and the global CSS file. In version 13.4, the padding of the swiper component is not being considered, and the pagination bullets are not changing to the rose-500 color as declared in the `globals.css` file."

### Expected Behavior

The CSS rendering in **Next.js 13.4** should be consistent with version **13.3**

**Comment by shuding** [comment]
The change is that in 13.3, the layout's CSS actually takes precedence over the page's CSS: 

<img width="625" alt="image" src="https://github.com/vercel/next.js/assets/3676859/7ef31333-1b68-4928-9a2f-82931ad55bf0">

This is wrong because layout styles are more general, and applied to multiple pages. But a page's styles are specific and should override the layout's if there're any conflicts. In 13.4 it's fixed:

<img width="881" alt="CleanShot 2023-05-24 at 10 23 44@2x" src="https://github.com/vercel/next.js/assets/3676859/4c7f2e94-3188-41fc-a03d-fba1e798df5b">
