### ISSUE TITLE
Docs: Custom server action invocation using startTransition example should use a callback.

### ISSUE THREAD

**Issue by bchilcott** [vercel/next.js#49420]
### What is the improvement or update you wish to see?

I think the [example](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#custom-invocation-using-starttransition) of using startTransition to invoke a server action is incorrect. According to the docs, the correct usage is:
```jsx
return <div onClick={() => startTransition(addItem(id))}>Add To Cart</div>;
```
This code doesn't work. I get the error `TypeError: callback is not a function`. However, the following works for me, and lines up with the startTransition usage described in the React docs:
```jsx
return <div onClick={() => startTransition(() => addItem(id))}>Add To Cart</div>;
```

### Is there any context that might help us understand?

See the React Docs, where startTransition expects a callback, not a function which is called directly:
https://react.dev/reference/react/useTransition#starttransition

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#custom-invocation-using-starttransition

**Comment by sannajammeh** [comment]
Should even be a recommendation to void all output as well:

```tsx
return <div onClick={() => startTransition(() => void addItem(id))}>Add To Cart</div>;
```

Otherwise TS will complain if your action ever returns data.

**Comment by sophiebits** [comment]
This is subtle but it's not correct to add `void`; you need to return the promise. This allows isPending to be true for the duration of the action and ensures that any errors thrown by an action bubble up to the nearest error boundary.

Passing an async function to startTransition is a new feature in experimental builds of React, which is why you are getting a TypeScript error. You can enable the experimental React types [by adding `"types": "react/experimental"` to your tsconfig](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/experimental.d.ts#L7-L22) and that should fix the type error.

**Comment by sannajammeh** [comment]
@sophiebits You're right, thanks :)

**Comment by bchilcott** [comment]
This looks to be solved now, so I'm closing this issue - thanks :)
