### ISSUE TITLE
[NEXT-1229] Error with `cookies.set()` in server actions on edge runtime : `Error: Invariant: Method expects to have requestAsyncStorage, none available`

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#50099]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Tue Apr 25 04:07:22 PDT 2023; root:xnu-8796.121.2~8/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.18
      pnpm: 8.5.0
    Relevant packages:
      next: 13.4.4-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Fredkiss3/next-bug-server-actions-headers-cookies

### To Reproduce

1. Clone the repo, install the deps, run `npm run dev` and open the browser
2. Try clicking on any of the buttons 
3. You will have an error `"Error: Invariant: Method expects to have requestAsyncStorage, none available"`

### Describe the Bug

this issue is the same as  this one #49235, it has been fixed in `next@13.4.2-canary.2`, but it still happens when using edge runtime. 

> Having a component that has the directive 'use client', which then imports an action that has the directive 'use server', will result in an error stating that  `Invariant: Method expects to have requestAsyncStorage, none available`, When invoked from a form.

### Expected Behavior

Using cookies & headers in server actions in edge runtime should work normally

<sub>[NEXT-1229](https://linear.app/vercel/issue/NEXT-1229/error-with-cookiesset-in-server-actions-on-edge-runtime-error)</sub>

**Comment by hanayashiki** [comment]
This bug can be easily repeated. I have the following fixture:

https://github.com/hanayashiki/next-action-headers-fixture

The following access to `cookies()` simple doesn't work if `runtime = "edge"`

```js
'use server';

import { cookies } from "next/headers";

export async function act() {
  return cookies().get('token').value;
}

```

Clicking the button the repro throws the error:

```
- error Error: Invariant: Method expects to have requestAsyncStorage, none available
    at act (./src/app/_actions.js:13:65)
```

After reading the compile result, I find this is because the `requestAsyncStorage` accessed by `cookies` is not the one used in `handleAction()`. This only happens in edge runtime, but works well in node. I suspect there's some wrong webpack config that leads to double instantiation of the singleton `requestAsyncStorage`.

**Comment by chungweileong94** [comment]
Actually, the same error is not limited to `cookie.set()`, it happens with `cookie.get()` too. Plus, it's also not limited to edge runtime, if a server action is using `cookie.set()` or `cookie.get()`, then import in a client component, the error will occur.

Here's the sample code
```tsx
// actions.ts
'use server';
export const someAction = () => {
    const theme = cookieStore.get('theme');
    // ....
}

// client-component.tsx
'use client';
import {someAction} from './actions';

export const ClientComponent = () => {
    const [isPending, startTransaction] = useTransaction();
    
    const onClick = () => {
        startTransaction(async () => {
            // This will throw `Error: Invariant: Method expects to have requestAsyncStorage, none available`
            await someAction();
        })
    }

     return <button onClick={onClick}>Click</button>
}
```

The currency workaround for this is to pass the server action as prop to the client component, instead of importing the server action directly in the client component.

**Comment by chungweileong94** [comment]
I believe this issue #50658 is also related, where `getServerSession` (from `next-auth`) is using `cookie()` internally.

**Comment by manovotny** [comment]
@Fredkiss3 I actually came across the same problem before @delbaoliveira linked me to this issue. 😊 

https://github.com/manovotny/next-server-actions-repro
