### ISSUE TITLE
Docs: searchParams in Server Actions

### ISSUE THREAD

**Issue by ma13gagan** [vercel/next.js#50156]
### What is the improvement or update you wish to see?

Is it possible to have access to searchParams in Server Actions? 

The use case for this would be to access data sent from the response.rewrite() in middleware.

### Is there any context that might help us understand?

searchParams in Server Actions

**Comment by shuding** [comment]
Can you elaborate? E.g. with an example of the usage you'd like to have. Server Actions are async functions that accept any serializable arguments. When they're called you can pass any information you'd like to, including search params.

**Comment by ma13gagan** [comment]
Yes, We can pass any arguments in Server Actions.
But I want to pass some data from middleware when server action is called—something like whether the user is logged in. I cannot pass that data as an argument to Server Actions.

**Comment by shuding** [comment]
Just to confirm that you want to do this:

Client → user triggers an action → middleware modifies the request → action receives the request with extra data from the middleware

You can pass extra information via headers in that case. Server Actions are not bound to a specific page route or a predictable API endpoint, that's by design.

**Comment by ma13gagan** [comment]
Got it. Thanks.
