### ISSUE TITLE
Warning: Prop `xxx` did not match. Server: "aaaaa" Client: "bbbbb"

### ISSUE THREAD

**Issue by Fredo70** [vercel/next.js#50482]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.0
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Fredo70/gemuekiosk

### To Reproduce

I want to display an analogue clock and have selected the component "react-clock" (https://github.com/wojtekmaj/react-clock) for this.
I have replaced the next logo with the clock component. The clock component is wrapped in a separate file so that I can use the "use client" mode.

### Describe the Bug

The clock is displayed but a warning appears in the console.
I'm just not sure if the bug is in next.js or in react-clock. Or somewhere else?

`Warning: Prop 'style' did not match. Server: "transform:rotate(317.52666666666664deg)" Client: "transform:rotate(317.53deg)"
...`

![screenshot_Warning_PropDidNotMatch](https://github.com/vercel/next.js/assets/6943043/6518bbf5-e467-4edd-b9f2-703e19a8d5d4)

### Expected Behavior

The clock is displayed and the clock hand moves every second.

### Which browser are you using? (if relevant)

Version 113.0.5672.127 (Offizieller Build) (64-Bit)

### How are you deploying your application? (if relevant)

npm run dev

**Comment by pawelblaszczyk5** [comment]
Generally speaking React expects the tree to be identical between server-rendering and first client-render after (aka hydration). If you're calling `new Date()` in `useState` initializer you'll get a mismatch between values during server render and hydration. 

You could initialize date in a server component and then pass it as a prop to client component and use it as an initial value. But generally speaking I'm not sure if this approach is the best, because the server can be in a different timezone than the user and it's hard to track. It'd cause flash of incorrect time on the clock for a user. Maybe it'd be the best idea to only client-render it using `next/dynamic`?

**Comment by shuding** [comment]
This is mostly a React hydration requirement as @pawelblaszczyk5 said. Related discussions: https://github.com/vercel/next.js/issues/51393#issuecomment-1603435396
