### ISSUE TITLE
Cannot use server actions inside a React component if "use server" is at top of file

### ISSUE THREAD

**Issue by vedantroy** [vercel/next.js#50550]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
vedant-ThinkPad-T580% npx next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: #202202161442 SMP PREEMPT Wed Feb 16 14:49:20 UTC 2022
    Binaries:
      Node: 18.16.0
      npm: 8.5.0
      Yarn: 1.22.17
      pnpm: 6.32.2
    Relevant packages:
      next: 13.4.5-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vedantroy/nextjs-bug-reproduction-2

### To Reproduce

Run `npm run dev` and go to main page.

### Describe the Bug

Can't use server actions in the same file as a React component if I put "use server" at the top. It gives an error that is misleading / confusing.

### Expected Behavior

Allow me to use server actions inside of a react component with "use server" at the top, or give a clear error message.

**Comment by hesalx** [comment]
You absolutely can use Server Actions inside a component that has `'use server'` at the top.
You just do not mix the two approaches together.

`'use server'` either:
* Marks a function as Server Action;
* Marks the entire file as exporting Server Actions;

If you put `'use server'` at the top there is no point to putting it in a function because everything is a Server Action. If you do not want everything to be Server Actions there is no point to putting `'use server'` at the top of the file.

`'use server'` **is not** a counterpart of `'use client'`. You use `'use client'` for Client Components but you do not use `'use server'` for Server Components, only for Server Actions.

Server Components are Server Components by default. Such as Pages when using the App Router.

Here's you own example modified to work with top-level `'use server'` if that's what you actually wanted:
```tsx
'use server';

// an exported function is a Server Action because of top-level 'use server'
export async function createGame(formData) {
  const obj = Object.fromEntries(formData);
  const gameId = obj["game"];
  console.log(gameId);
}

export default async function() {
  return (
    <>
        {[{id: 1}, {id: 2}, {id: 3}].map((item) => (
        <form action={createGame} key={item.id}>
          <button
            name="game"
            value={item.id}
            type="submit"
            key={item.id}
            className="p-4 hover:bg-gray-100 rounded-lg cursor-pointer"
          >
          </button>
        </form>
      ))}
    </>
  );
}
```

All of the information in this reply was deduced from the documentation: https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions

**Comment by shuding** [comment]
As @hesalx said, you can't mix a component file with a top-level `'use server'` file. The example in the **With Client Components** section of that linked docs above might help. Let us know if you have further questions!
