### ISSUE TITLE
Docs: Medium-style Click to Zoom on Images

### ISSUE THREAD

**Issue by deadcoder0904** [vercel/next.js#50835]
### What is the improvement or update you wish to see?

would love a medium-style zoom image for smaller images on docs.

i use https://github.com/mvoloskov/fast-image-zoom

### Is there any context that might help us understand?

i was reading https://nextjs.org/docs/getting-started/react-essentials#server-components & was under **client components** but couldn't read the code as i found it too small.

instead of zooming in the website, thought it'd be useful to have a zoom image viewer like medium.

<sub>[DX-1614](https://linear.app/vercel/issue/DX-1614/docs-medium-style-click-to-zoom-on-images)</sub>

**Comment by manovotny** [comment]
Thank you for the suggestion. While it might be nice to add at some point, we're currently prioritizing documenting all the latest features of Next.js 13. However, if individual images are too small or unclear, please let us know because we'd like to make them accessible and understandable without needing to enlarge.

**Comment by steven-tey** [comment]
@deadcoder0904 we just shipped this!!

https://twitter.com/steventey/status/1684607625240150016
