### ISSUE TITLE
useParams still returns a string for dynamic catchall routes, for example [...ids]

### ISSUE THREAD

**Issue by cmugla** [vercel/next.js#50856]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.5-canary.6
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/ancient-pond-wk3eu5

### To Reproduce

From the sandbox, go to any route in the browser: `/1/2/3/4` (whatever route you'd like)

### Describe the Bug

See that the value of dynamic route `[...ids]` from the `useParams` hook is a string:

<img width="485" alt="Screenshot 2023-06-06 at 11 08 02 AM" src="https://github.com/vercel/next.js/assets/19141291/c94e16f0-5866-41cd-a8a9-692778fc1d97">

### Expected Behavior

According to the docs, it should be returning an array 🤔 
<img width="671" alt="Screenshot 2023-06-06 at 11 10 45 AM" src="https://github.com/vercel/next.js/assets/19141291/3fd438dc-d2eb-44f8-adee-456ed50e254e">

<sub>[NEXT-1419](https://linear.app/vercel/issue/NEXT-1419/useparams-still-returns-a-string-for-dynamic-catchall-routes-for)</sub>

**Comment by bramvdpluijm** [comment]
I'm also experiencing a similar issue with the edge runtime enabled in app router. With edge runtime disabled the url params that are returned to the page look like `['path-1', 'path-2']`. With edge runtime enabled, the array gets concatenated into a single string `['path-1%2Fpath-2']`. Any help is appreciated.

**Comment by JuniorTour** [comment]
Is it by design? 

According to source code: https://github.com/vercel/next.js/blob/f19b31ad93c313cb86d9a589c931f8f9718a7fb2/packages/next/src/client/components/navigation.ts#L148

And test case:
https://github.com/vercel/next.js/blob/f19b31ad93c313cb86d9a589c931f8f9718a7fb2/test/e2e/app-dir/use-params/use-params.test.ts#L36

Currently, `useParams()` will only return `string`, there is no return `array` logic.

Should we add return `array` logic?

**Comment by cmugla** [comment]
> Currently, useParams() will only return string, there is no return array logic.
> Should we add return array logic?

@JuniorTour The expectation is an array according to the return type (`string | string[]`) & the docs... Its also a bit odd it'd be different from the `params` prop on layout/page's

**Comment by bramvdpluijm** [comment]
Locally (using dev server) a string array is returned correctly. But once deployed, the string array gets concatenated into an array with just 1 string.Op 9 jun. 2023 om 18:30 heeft Celeste Glavin ***@***.***> het volgende geschreven:﻿

Currently, useParams() will only return string, there is no return array logic.
Should we add return array logic?

@JuniorTour The expectation is an array according to the return type (string | string[]) & the docs... Its also a bit odd it'd be different from the params prop on layout/page's

**Comment by bramvdpluijm** [comment]
For the time being I wrote a small conditional that will make sure catch all routes can be used in edge runtime. Locally, the correct string array is returned `['path1', 'path2']`, but in once deployed it will look like this: `['path1%2Fpath2']`. I just split the single string in the array on the delimiter to make it an array again.

```export default async function Page({ params }: { params: { slug: string[] } }) {
  const urlParams = params;
  
  if (params.slug.length === 1 && params.slug[0].includes("%2F")) {
    urlParams["slug"] = params.slug[0].split("%2F");
  }
  ```

**Comment by steve-marmalade** [comment]
I just ran into the same issue, albeit with an async server component instead of the `useParams` hook. The code looks like:

```typescript
export const generateMetadata = async ({
  params: { categories },
}: {
  params: { categories: string[] };
}):
  console.log(categories);
```

In dev, `categories` is an array of strings as expected, but on vercel with edge runtime enabled it is a url-encoded string.

**Comment by ArjobanSingh** [comment]
In my local environment, I am encountering a similar issue with the `useParams` hook. When using the `catch-all` route, the value returned by `useParams` for the catch-all route is a `string` instead of an `array`. However, I have not yet tested this behavior on Vercel with the edge runtime.

After examining the code for the `useParams` function, I found that its returned value is an object where each value is a `string`. 

https://github.com/vercel/next.js/blob/f19b31ad93c313cb86d9a589c931f8f9718a7fb2/packages/next/src/client/components/navigation.ts#L129-L131

However, I am puzzled because the [documentation](https://nextjs.org/docs/app/api-reference/functions/use-params#returns) states that returned value can have both `string` or `string[]`.

**Comment by siffogh** [comment]
I'm getting the same behaviour when accessing the `params` prop from a page component.

**Comment by remorses** [comment]
I created a new reproduction for this issue, it only happens when using the `edge` runtime and deploying to Vercel: https://github.com/vercel/next.js/issues/53849
