### ISSUE TITLE
Hydration error when parsing date with toLocaleTimeString()

### ISSUE THREAD

**Issue by AshotN** [vercel/next.js#51393]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

My local

```bash
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:13 PST 2022; root:xnu-8020.240.14~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.7.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.5
      eslint-config-next: 13.4.5
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.0-dev.20230615
```

Codesandbox VM

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.7-canary.0
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/laughing-roentgen-v32sd2?file=%2Fcomponents%2FHours.tsx%3A10%2C10

### To Reproduce

The sandbox throws the following runtime error

```
Error: Text content does not match server-rendered HTML.

Warning: Text content did not match. Server: "3:24:00 AM" Client: "3:24:00 AM"

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

### Describe the Bug

Parsing a date in a client component with `toLocaleTimeString()` seems to cause a hydration error. Oddly, `toLocaleDateString()` and other methods(haven't tried them all) do not.

### Expected Behavior

There shouldn't be a hydration failure.

### Which browser are you using? (if relevant)

Firefox 114.0.1

**Comment by shehi** [comment]
Shouldn't this kind of issue be an expected case and not SSR'ed? Each client will eventually have a different local time. Adding some kind of `hasMounted` mechanic to your page/component and using local time rendering only when it has mounted (i.e. client side execution) is the way to go. Let SSR just use Zulu time.

**Comment by shuding** [comment]
Yes exactly - every client could have a different situation (local data, time, location, UA settings, …), and that will make hydration to mismatch. React’s hydration requires the markup to be the same between the SSR result and the initial client rendering. This isn’t a specific thing in Next.js but a general requirement by React.

Like @shehi said you can use a hook to make sure the formatted date only gets rendered after hydration.

Related resources: 
- https://www.joshwcomeau.com/react/the-perils-of-rehydration
- https://www.benmvp.com/blog/handling-react-server-mismatch-error/

**Comment by AshotN** [comment]
I understand that a Date object can render to many different strings depending on locale. I'm confused why React is not reconciling two strings that match.
`Server: "3:24:00 AM" Client: "3:24:00 AM"`

But I suppose this isn't a Next issue, and just the way React SSR works.

**Comment by shehi** [comment]
Most probably because internally, it is not these strings that are compared, but a composite hash that is comprised of different stuff, as well as these equal values. Just make sure the "text content" mentioned in the error belongs to the same tag. Potentially, you might be introducing a new child tag somewhere when toLocalString() is being invoked.

Additionally, please note that a "text content" can be multiple nodes that eval to a text, which are children of the same tag. E.g. your `3:24:00 AM` is visually equal to `${"3:24:00"} AM`, but by-value, they are not. Make sure you calculate that string value into a variable, THEN print that variable's final value as a child where it should go. This happens a lot with `<title>` tag in NextJs, and NextJs has dedicated error message specifically for this reason (can't remember the URL for that error, sorry). Hope I could explain properly.
