### ISSUE TITLE
ISR on demande revalidation doesn't work in production nor in vercel 

### ISSUE THREAD

**Issue by nabildroid** [vercel/next.js#51620]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.7-canary.2
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/clever-shape-455pvc

### To Reproduce

run `npm run build` then `npm run start` then visit twice /post/hello you can see the catch `hit` but when calling the API /api/revalidate then revisit /post/hello the data remains invalidated and the cache always `hit` never `miss`

### Describe the Bug

the on-demand revalidation in production doesn't work either by calling `revalidatePath` not by `RevalidateTag` or both of them simultaneously 

### Expected Behavior

when calling /api/revalidate then revisiting /post/hello the page get revalidated and new data will appear, ISR after all!

**Comment by billyberkouwer** [comment]
Same issue here on Next 13.4.5, both locally and when deploying to Vercel. I'm using revalidatePath instead of revalidateTag because I am using the Sanity client to fetch data. The page doesn't revalidate the data on demand, when the webhook sends a post request. I can see the request coming in in the Vercel logs, however there is no update to the data in the front-end.

**Comment by michaelsoriano** [comment]
This is probably the same issue. I'm using **revalidatePath()** on a route.ts (GET). Cache is so sticky - works locally but as soon as deployed (using AWS amplify), cache won't flush.  

Note that I'm not using fetch - instead getting records using Prisma client: 

<img width="699" alt="image" src="https://github.com/vercel/next.js/assets/5881081/1e8e3203-de04-4da4-a91e-2e7c05264480">

Please advise.

**Comment by nabildroid** [comment]
They keep releasing new version without addressing this bug
Since its now production ready, i made project for client based on app Router abd now im in big trouble because when updating nothing happens. Such selly thing is destroying my reputation

**Comment by laktoufik** [comment]
same problem the cache is sattle regardless of the api revalidating the path
nothing work on production or on vercel

**Comment by billyberkouwer** [comment]
Following up on my previous post to share some info that might help people and narrow the issue.

In my tests, I've found that when a Next app (13.4.6) is hosted on Vercel, it fails to revalidate paths if you need to use a client to fetch rather than a Next fetch request that you can pass the new fetch params to.

In my case with @Sanity, I found that using a package like [next-sanity-client](https://www.npmjs.com/package/next-sanity-client)  , which expands Sanity's client so you can pass the params down to the fetch request, gets revalidatePaths (and ofc revalidateTags if you want) working in production on Vercel. In this case, it works ONLY IF you remove the leading '/' from the revalidatePath argument (no idea why). No messing around (e.g. changing api route runtime, path argument syntax, forceCache) could get the Sanity client revalidating in production. Seems like there's an issue with how Next/Vercel are handling the caching of fetch clients that aren't using the Next fetch api.

**Comment by nabildroid** [comment]
this is not a bug, but me not reading the docs and lack of experience on debugging 
this is the solution for me https://github.com/vercel/next.js/discussions/51612#discussioncomment-6250425
by default any route that exposes GET will be static cached route 
and in docs
> path: A string representing the filesystem path associated with the data you want to revalidate. This is **not** the literal route segment (e.g. /product/123) but instead the path on the filesystem (e.g. /product/[id]).

so instead of `revalidatePath` use `revalidateTag`
