### ISSUE TITLE
Nested route unreachable if inside or besides a parallel route

### ISSUE THREAD

**Issue by lu-zen** [vercel/next.js#51805]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Thu, 30 Mar 2023 14:10:04 +0000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.4
    Relevant Packages:
      next: 13.4.8-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/lu-zen/next-parallel-route-bug

### To Reproduce

1. install and start project;
2. navigate to `/nested/misc` and `nested2/misc` paths;

### Describe the Bug

Next returns a 404 error when navigating to a nested route that lives besides or inside a parallel route.

### Expected Behavior

To render the nested route.

**Comment by lu-zen** [comment]
[CodeSandbox](https://codesandbox.io/p/sandbox/green-glitter-2fs2s5) for quick reproduction

**Comment by ztanner** [comment]
I think you might be running into expected behavior when a parallel route reaches an unmatched segment, explained in the docs [here](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#unmatched-routes). Adding a `default.tsx` file to your parallel route will fallback for nested paths that don't have a corresponding parallel segment. Here's your CodeSandbox forked: https://codesandbox.io/p/sandbox/happy-hoover-5plgwq

**Comment by lu-zen** [comment]
Thanks.
