### ISSUE TITLE
Docs: Conflicting info about POST deduping?

### ISSUE THREAD

**Issue by gmoniava** [vercel/next.js#52077]
### What is the improvement or update you wish to see?

At one place it [says](https://nextjs.org/docs/app/building-your-application/data-fetching#automatic-fetch-request-deduping):

> POST requests are not automatically deduplicated

At [another](https://nextjs.org/docs/app/building-your-application/data-fetching/caching#post-requests-and-cache):

> POST requests are automatically deduplicated when using fetch – unless they are inside of POST Route Handler or come after reading headers()/cookies()

These two seem to somewhat contradict, no? Or at least I would have written the first so that it is more aligned with the second. 

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

See links above.

<sub>[DX-1753](https://linear.app/vercel/issue/DX-1753/docs-conflicting-info-about-post-deduping)</sub>

**Comment by SonMooSans** [comment]
The first tip was wrong, `POST` requests are automatically deduplicated (I've tested) unless it's called inside of a POST route handler or a dynamically rendered page. For example, a page with `getServerSession()` or `cookies()`.

This is the correct one: https://nextjs.org/docs/app/building-your-application/data-fetching/caching#fetch

**Comment by darshanjain-entrepreneur** [comment]
I will be able to solve this issue

**Comment by SonMooSans** [comment]
Pretty much similar, but it is confusing for beginners. 
I think we need a clear definition, sending a `POST` request isn't different from others such as `GET` and `DELETE`. 

Requests are not cached If: 
1. Dynamic methods are used in the page/route, for example: `cookies()`
2. It is called inside a `POST` Route Handler
3. Default settings are configured to do so

Those types of pages won't be cached because it's different for every user. 
The definition here is very detailed: https://nextjs.org/docs/app/building-your-application/data-fetching/caching#fetch (as I mentioned in my [PR](https://github.com/vercel/next.js/pull/52100))
