### ISSUE TITLE
Cannot set NODE_ENV to development to use non-minified react in next build

### ISSUE THREAD

**Issue by Raynos** [vercel/next.js#52452]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
$ ./node_modules/.bin/next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: #202303130630~1679424972~22.04~4a8cde1~dev-Ubuntu SMP PREEMPT_DY
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: N/A
      pnpm: 8.6.6
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.2.4", newest: "13.4.10-canary.0".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Link to the code that reproduces this issue or a replay of the bug

NA

### To Reproduce

I try to run next build where I set NODE_ENV in my next config.js

```js
{
  env: {
    IS_STAGING_SNAPSHOT: process.env.IS_STAGING_SNAPSHOT,
    // NODE_ENV: DEPLOY_ENVIRONMENT,
  },
};
```

### Describe the Bug

When I run `next build` I get

```
> Build error occurred
Error: The key "NODE_ENV" under "env" in next.config.js is not allowed. https://nextjs.org/docs/messages/env-key-not-allowed
```

### Expected Behavior

I expected it to build my website and use the non-minified version of react.

**Comment by Raynos** [comment]
I get this error message https://nextjs.org/docs/messages/env-key-not-allowed and it's very frustrating, terrible user experience.

**Comment by balazsorban44** [comment]
Since Next.js 9.4 though, there is a more convenient way to set environment variables other than `next.js.config#env`, see	https://nextjs.org/docs/app/building-your-application/configuring/environment-variables

I believe we allow overriding `NODE_ENV`

https://github.com/vercel/next.js/blob/cf08f600772b17d692081c6302c254e4d68151fe/packages/next/src/bin/next.ts#L86-L98

but it might have other unforeseen consequences, as a lot of optimization is based on this value. I would suggest opening a new issue/feature request why would you need to ship to production with unminified React instead, so we can maybe address this in a different way.

**Comment by Raynos** [comment]
Setting `NODE_ENV=development next build` also does nothing. The docs says

![image](https://github.com/vercel/next.js/assets/479538/ac3834bd-56e9-4995-93bb-13254b4b0744)

I cannot get the build artifact to use the non-minified version of react, and the issue is that `next build` does not respect the `NODE_ENV` I set as the user no matter what i try to do.
