### ISSUE TITLE
nextjs api routes not excepting body more than 1MB

### ISSUE THREAD

**Issue by manjunath-nuveb** [vercel/next.js#52457]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.16.0
      npm: 9.8.0
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.10-canary.0
      eslint-config-next: 12.3.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/s/next-with-api-forked-6cs9k8?file=/pages/api/test.js

### To Reproduce

Use the link https://codesandbox.io/s/next-with-api-forked-6cs9k8?file=/pages/api/test.js to reproduce

### Describe the Bug

I am trying to build a react image uploader application with nextjs api routes.

API is throwing error whenever the request body size is more than 1MB

tried the following config, still not working 
`
export const config = {
  api: {
    bodyParser: {
      sizeLimit: "25mb",
    },
  },
}
`

### Expected Behavior

API should be able to handle any request body size

**Comment by AlexApiko** [comment]
Even more, it says  `"export const config" in ... is deprecated. Please change "runtime" property to segment export config. See https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config`

But there is no options to extend request body size limit.

**Comment by DaX-523** [comment]
Well unfortunately, it's because how next.js works that even after you configure the API the maximum size of the uploaded file accepted will be 4mb. If you really want bigger files in size to be accepted you should consider storing those assets in a dedicated media host and make them retreivable with a presigned URL that contains access control policies directly in the URL.

See https://vercel.com/guides/how-to-bypass-vercel-body-size-limit-serverless-functions

**Comment by shuding** [comment]
Please take a look at this option:

https://nextjs.org/docs/pages/building-your-application/routing/api-routes#custom-config

**Comment by manjunath-nuveb** [comment]
@shuding  I tried the options mentioned there, but it does not work.

**Comment by shuding** [comment]
@manjunath-nuveb I just downloaded your sandbox and verified that it works locally. It errors on the CodeSandbox website because of they have a body size limit (as you can see that error came from Nginx).

<img width="888" alt="CleanShot 2023-07-20 at 17 38 24@2x" src="https://github.com/vercel/next.js/assets/3676859/91a6e4b5-5af0-4b7a-b6aa-3cca8d55083b">

Note that book.pdf is ~10MB.

**Comment by luisjuniorj** [comment]
> Please take a look at this option:
> 
> https://nextjs.org/docs/pages/building-your-application/routing/api-routes#custom-config

- warn `export const config` in "" is deprecated. Please change `runtime` property to segment export config. See https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config

**Comment by luisjuniorj** [comment]
The test provided is cleary in pages api, on routes api, there is no documentation on how to increase upload body size limit.

Is there any workaround?
