### ISSUE TITLE
Typescript transpiles conditional chaining incorrectly

### ISSUE THREAD

**Issue by carmelc** [vercel/next.js#52585]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.10-canary.4
      eslint-config-next: 13.4.10-canary.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC transpilation

### Link to the code that reproduces this issue or a replay of the bug

npx create-next-app --example with-turbopack

### To Reproduce

1. Add the following code:
```
const test: any = {};
  console.log('My test returned::: ', test?.a.b);
```

### Describe the Bug

When the first condition in the chain returned undefined the whole chain should stop.
See MDN - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
it should be test && test.a.b which doesn't crash.

### Expected Behavior

should print `My test returned:::undefined`

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Locally

**Comment by P4sca1** [comment]
Similar problem here. Starting from version 13.4.8, I can no longer use the optional chaining ? operator.

```
- error ./src/translations/utils.ts
Module parse failed: Unexpected token (22:35)
| export const LOCALE_COOKIE_NAME = "sayhy-locale";
| export function detectLocaleFromRequest(request) {
>     const localeFromCookie = this?.;
```

Source code:
```ts
 const localeFromCookie = request.cookies.get(LOCALE_COOKIE_NAME)?.value
 ```

Works fine with 13.4.7.

**Comment by balazsorban44** [comment]
The current behavior is correct. You can test it by pasting your code into the above-mentioned MDN docs interpreter, and it will throw the same error:

![image](https://github.com/vercel/next.js/assets/18369201/d7a5ce5f-1a3e-4982-895b-950cf4ad11c1)

Chrome:
![image](https://github.com/vercel/next.js/assets/18369201/c3cc3d98-535c-4330-beb7-36507ae1b530)

Node: 
![image](https://github.com/vercel/next.js/assets/18369201/0f2b25fe-e1e4-4fd0-baee-3c15a4552123)

Since `test` is an object, the accessing of properties won't short-circuit. You'll need to write it as `test.a?.b` instead. Your code would only guard if `test` is `null` or `undefined`.

@P4sca1 please open a new issue with a full (but minimal) reproduction instead of a snippet, thanks.

**Comment by MarttiR** [comment]
@balazsorban44 FWIW, @P4sca1 is reporting a different issue.

I think I'm running into it too, but have yet been unable to reproduce it in a clean build.

For me, the issue is happening on a large v13.4.12 build that has been maintained all the way from Next.js v8.

Input (simplified):
```jsx
export const SomeReactComponent = () => {
  // ...
  const sortParams = query.sort?.split(":") ?? [];
  // ...
}
```

Broken output 1 (from server-side error in console):
```jsx
export function SomeReactComponent() {
  // ...
  const sortParams = (_this_ = this.) !== null && _this_ !== void 0 ? _this_ : []
  // ...
}
```

Broken output 2 (from error in browser):
```jsx
export function SomeReactComponent() {
  // ...
  const sortParams = this. ?? [];
  // ...
}
```

**Comment by P4sca1** [comment]
For me the issue was, that I used a [SWC plugin](https://github.com/lingui/swc-plugin), which was incompatible with the version of next.

**Comment by MarttiR** [comment]
@P4sca1 Thank you, that was the issue for me as well.

Looks like we're stuck with v13.4.8 for the time being.
