### ISSUE TITLE
Slow UI updates when using location query params as state

### ISSUE THREAD

**Issue by JakeElder** [vercel/next.js#52870]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 20:57:23 PDT 2022; root:xnu-8020.121.3~2/RELEASE_ARM64_T8110
    Binaries:
      Node: 18.15.0
      npm: 9.7.1
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.11-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/JakeElder/slow-qs-ui

### To Reproduce

Open the page. Press a button. Observe that interface updates are blocked until a complete request is made to the server

https://codesandbox.io/p/github/JakeElder/slow-qs-ui/main

### Describe the Bug

Changing query params using `router.push()` results in slow UI updates when using query params as state.

I've tried updating state on the client, rather than using `push`, but this results in broken back/forward buttons.

I have set a delay of 1 second to illustrate the problem. I know I can optimise reload speed by using Suspense etc.

But for UI changes, it needs to be instant like when using the pages router.

I have tried using various combinations of using client side state `useState` and updating the url using `router.push()` at different stages, but whatever I try seems to result in some kind of problem.

What is the recommended approach for updating query params, keeping the UI and window location in sync?

### Expected Behavior

I would like a way of having the UI instantly updated based on changes to the query string, while using `next.js` principles

**Comment by Fredkiss3** [comment]
This is only slow in DEV mode, because it runs a full server. You marked your page as static, so if you run on build, it will be much much faster.

But if you made your page dynamic (ex: for fetching data on the server based on search params) then you'd have to use `Suspense` instead because it would need to make the request to your server to know what to show you, if your data source is that slow then there is nothing else you could do to make it faster but using a `Suspense` to show a fallback while your data is loading. This is because you are using a `router.push` to make a request, by default next tries to make your app faster by prefetching links that are visible in the viewport, making page transitions faster, but here there is not possibility for next to prefetch your data, and next is obliged to make a request to get what to show you. 

One thing though, if you use `Suspense` simply or use `loading.tsx` for dynamic pages with search params the first request to your page will show the fallback but not subsequent requests if you update the query params, for that to show every time, you need to use `Suspense` and encode the searchParams to pass it as a key to the `Suspense`. 

Something like this : 

```tsx
import * as React from "react";

export default function Page(props: {
  searchParams?: Record<string, string | undefined>;
}) {
  // this is for examples purposes, you can encode any way you want, we just need a different key for each searchparams change 
  const keyString = `b1=${props.searchParams?.["button-1-pressed"]}&b1=${props.searchParams?.["button-2-pressed"]}`;
  return (
     <React.Suspense key={keyString} fallback={<>loading data...</>}> 
       <AsyncComponent /> 
     </React.Suspense>
  );
}

async function AsyncComponent({search}: {search: string}) {
  const resolved = await new Promise((resolve) => setTimeout(resolve(search), 1000));
  return <div> Resolved: {resolved} </div>
}
```

This is because `router.push()` is executed in a transition (to let you interact with the UI while a request is made in the background), and transitions keep the old page visible while loading the new page in the background, only showing the suspense fallback the first time a page is navigated to : https://react.dev/reference/react/Suspense#resetting-suspense-boundaries-on-navigation .   

I used something similar in [my app](https://vercel-streaming-bug.vercel.app/?wait=on&search=) (a simple app to search pokemons by name) to always show the fallback on a page with search params : https://github.com/Fredkiss3/vercel-streaming-bug/blob/4f6a356f67fd0a034d9f148e8588dcb0319e0e45/app/page.tsx#L21-L28

**Comment by rnodal** [comment]
I'm experiencing the same behavior in an app I recently migrated from Pages router to App router. Under Pages router everything was instant but with App router I experience the same behavior as in this bug report. Sometimes even on PROD after the app has been idle (tab has been out of focus for example). My expectation would be, at the very least, that the URL updates instantly when I use router.push() to update the URL. I'm using SWR to fetch my data and I'm handling the loading state myself. Why does route.push require a request to the server? Is this a behavioral difference between App router and Pages router?

**Comment by timneutkens** [comment]
I posted a reply on this other thread that is asking for something similar: https://github.com/vercel/next.js/discussions/48110#discussioncomment-6481618

Shallow routing is not supported yet, but something like it will be added in the future.

Going to close this issue as it's asking for the same feature as #481105 and the proposal for it is already being tracked 👍

**Comment by JakeElder** [comment]
Thanks @timneutkens . For now I reverted to pages router for this route. After some changes in my architecture everything works great. I learnt a lot about Next figuring this out. All the best
