### ISSUE TITLE
LangCode Missing zh-Hans and zh-Hant

### ISSUE THREAD

**Issue by rocerchen** [vercel/next.js#52898]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 20.4.0
      npm: 9.7.2
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.10
      eslint-config-next: 13.4.10
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Metadata (metadata, generateMetadata, next/head)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/blob/f5272acbe5628164257ef8e584c8a469a4af5cb8/packages/next/src/lib/metadata/types/alternative-urls-types.ts#L419

### To Reproduce

Missing "zh-Hant" and "zh-Hans"

### Describe the Bug

Simplified Chinese: zh-Hans ⊃ zh-cn ⊃ zh-sg ⊃ zh-my
Traditional Chinese: zh-Hant ⊃ zh-tw ⊃ zh-hk ⊃ zh-mo

### Expected Behavior

"zh-Hant" and "zh-Hans" can be use in generateMetadata > alternates > languages

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

next dev

**Comment by shuding** [comment]
The lang code type here only contains valid `[language]-[region]` combinations, not `[language]-[script]`. This is because there're too many valid options according to the spec - and it breaks TypeScript (which has a limitation on the union type size). One solution might be adding `| string` by the end so it technically accepts any string, but the unions before it will still provide autocompletion.

cc @huozhi for consideration.
