### ISSUE TITLE
Parallel Routes in Root Folder

### ISSUE THREAD

**Issue by rizki5411** [vercel/next.js#53122]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
"dependencies": {
    "@headlessui/react": "^1.7.15",
    "@heroicons/react": "^2.0.18",
    "@types/node": "20.4.2",
    "@types/react": "18.2.15",
    "@types/react-dom": "18.2.7",
    "autoprefixer": "10.4.14",
    "eslint": "8.45.0",
    "eslint-config-next": "13.4.10",
    "flowbite": "^1.7.0",
    "flowbite-react": "^0.4.11",
    "next": "13.4.10",
    "postcss": "8.4.26",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-loading-skeleton": "^3.3.1",
    "react-multi-carousel": "^2.8.4",
    "swiper": "^10.0.4",
    "tailwindcss": "3.3.3",
    "typescript": "5.1.6"
  },
```

### Which example does this report relate to?

-

### Describe the Bug

I try to user Parallel Routes in Root Folder and get bad experience.

So I want to create my home page (root folder) with Parallel Routes feature

![image](https://github.com/vercel/next.js/assets/31713769/7941b376-c93a-4467-9806-3680e44ab0cc)

But, because Parallel Routes requires using Layout.tsx, my Layout Root looks like this

![image](https://github.com/vercel/next.js/assets/31713769/9290662c-df25-49a2-9980-2228661850c0)

With a concept like this, my @slot renders on all child pages, which should only be done on the homepage.

### Expected Behavior

@slot can be rendered on the homepage only

### To Reproduce

My @slot renders on all child pages, which should only be done on the homepage becuse Parallel Routes should be use Layout.tsx

**Comment by ShubhamRavindraDesai** [comment]
I have reproduced this issue but as per the  NextJS official docs and the routing behaviour the working behaviour is the right one because you have provided the children and also the parallel route in the layout.tsx file, which means it will create a wrapper around the main page.tsx and always shows the children and the @folder page.tsx. 
--Layout.tsx
---Your children components
---@folder's-page.tsx
--Layout.tsx

Here Children components have their own routing and your @folder has it's own 
So technically it's not an issue there might be something wrong in your implementation.
Correct me if I am wrong.

**Comment by mvahedii** [comment]
I have the same issue, in the official Next.js documentation, there is an example that doesn't work for me.
<be />
```js
export default function Layout(props: {
  children: React.ReactNode
  analytics: React.ReactNode
  team: React.ReactNode
}) {
  return (
    <>
      {props.children}
      {props.team}
      {props.analytics}
    </>
  )
}
```
and when I navigate to the homepage or /setting (refer to the doc ) I see a 404 page.

**Comment by samcx** [comment]
@mvahedii The `404` is likely because you are missing a `default.ts` file (required) → https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#reload.

A good visualization of why it's required is also shown in our App Router Playground → https://app-router.vercel.app/parallel-routes/impressions.
