### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by felipe-b-oliveira** [vercel/next.js#53310]
### What is the improvement or update you wish to see?

A grammatical correction in the README.md of github-pages example.

### Is there any context that might help us understand?

In the subtitle is writing the setence 'This example supports deloying a ...' instead of 'This example supports deploying a ...'

### Does the docs page already exist? Please link to it.

https://github.com/vercel/next.js/blob/canary/examples/github-pages/README.md

**Comment by balazsorban44** [comment]
Fixed in https://github.com/vercel/next.js/pull/53311, thanks! :green_heart:

_@felipe-b-oliveira TIP: If you add "Fixes #53310" to the PR description, when merged, it will automatically close the corresponding issue. (See: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)_
