### ISSUE TITLE
Close http server in cleanup

### ISSUE THREAD

**Issue by Meemaw** [vercel/next.js#53661]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.3.1
      npm: 9.6.7
      Yarn: 1.22.18
      pnpm: 7.29.3
    Relevant Packages:
      next: 13.4.13-canary.18
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Standalone mode (output: "standalone")

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Meemaw/next-server-shutdown-reproducer

### To Reproduce

1. yarn build
2. yarn start
3. Visit http://localhost:3000
4. Close the server before the page renders
5. Get a "This site can’t be reached" error

### Describe the Bug

NextJS doesn't gracefully handle inflight HTTP server connections. There is a cleanup code
https://github.com/vercel/next.js/blob/498692b69812a096178eaabfea766f4d8fa82413/packages/next/src/server/lib/start-server.ts#L262

, but it doesn't call `server.cleanup()`.

There also seems to be a `teardown` function defined https://github.com/vercel/next.js/blob/498692b69812a096178eaabfea766f4d8fa82413/packages/next/src/server/lib/start-server.ts#L500)

, which does the correct thing, but is never called?

### Expected Behavior

`server.cleanup()` should be called & awaited so any inflight requests are gracefully handled.

<sub>[NEXT-1961](https://linear.app/vercel/issue/NEXT-1961/close-http-server-in-cleanup)</sub>

**Comment by redbmk** [comment]
It looks like the code has change a bit but the issue is still there. To add to this, it looks like the standalone `server.js` file that gets generated has it's own conflicting code that immediately kills the server.

https://github.com/vercel/next.js/blob/e9757175bc759842a1e82b9fdc5c20fad248077c/packages/next/src/build/utils.ts#L2029-L2034

https://github.com/vercel/next.js/blob/e9757175bc759842a1e82b9fdc5c20fad248077c/packages/next/src/server/lib/start-server.ts#L283-L287

So as I understand this, the standalone `server.js` will run `process.exit(0)` unless you have the `NEXT_MANUAL_SIG_HANDLE` flag set, but then it calls `startServer` which will run `server.close` and then `process.exit` unless you set the same variable.

I would think since `start-server` has this code, we actually shouldn't have it in `server.js`
