### ISSUE TITLE
Server Action variables from parent function not available

### ISSUE THREAD

**Issue by leonschwanitz** [vercel/next.js#54061]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.17.1
      npm: 9.6.7
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: {
	experimental: {
		appDir: true,
		serverActions: true
	}
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, TypeScript (plugin, built-in types)

### Link to the code that reproduces this issue or a replay of the bug

https://stackoverflow.com/questions/76906463/nextjs-13-server-action-variables-from-parent-function-not-available

### To Reproduce

```typescript
export default async function MyPage({ prisma, texts } : MyPageProps) {
    "use server"

    const test = "Hello"

    const fun1 = async () => {
        "use server";

        console.log(test) // This is undefined
    }

    const fun2 = async () => {
        console.log(test) // This is defined, but i cannot pass it into the client page.
    }

    fun1()
    fun2()

    return <RegisterPage registerFunc={fun1} />
}

```

### Describe the Bug

The challenge arises when executing fun1(), which results in the test variable being undefined. On the other hand, executing fun2() (without the "use server" directive) successfully defines the variable, but I'm facing difficulty in passing it to the RegisterPage component due to the asynchronous nature of server actions and the use of the "use server" attribute.

### Expected Behavior

test is defined

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Local / next run dev

**Comment by shuding** [comment]
First of all, there're two ways to create Server Actions:

### 1 - annotate your function with `"use server"` in its body inside a Server Component file

```js
async function action() {
  "use server"
}
```

The `action` function will be a Server Action.

### 2 - put `"use server"` on top of a file

```js
"use server"

export async function action() {
}
```

All exports, including the `action` function will be Server Actions.

---

Now let's take a look at your example:

```js
export default async function MyPage({ prisma, texts } : MyPageProps) {
    "use server"

    const test = "Hello"

    const fun1 = async () => {
        "use server";

        console.log(test) // This is undefined
    }

    const fun2 = async () => {
        console.log(test) // This is defined, but i cannot pass it into the client page.
    }

    fun1()
    fun2()

    return <RegisterPage registerFunc={fun1} />
}
```

Function `fun2` will NOT be a Server Action because it doesn't follow the rule 1 or 2 above. It will be just a normal function and you can't pass that to a Client Component.

And also, you annotated `MyPage` with `"use server"`, but that should be a Component, not a Server Action.

`fun1` looks good so you should probably do the same to `fun2`.

Let me know if you have other questions!
