### ISSUE TITLE
Response headers in next.js config are not applied to standalone/_next/static (when i18n is configured)

### ISSUE THREAD

**Issue by cosieLq** [vercel/next.js#54159]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 3.6.1
      pnpm: N/A
    Relevant Packages:
      next: 13.4.17-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: standalone
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Standalone mode (output: "standalone")

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/cosieLq/exampleApp_nextjs/tree/reproduction-missing-headers

### To Reproduce

- Run `yarn install` and then `next build`
- Copy .next/static and /public assets to the .standalone folder as mentioned here: https://nextjs.org/docs/pages/api-reference/next-config-js/output#:~:text=Additionally%2C%20a%20minimal,serve%20these%20automatically.
- Run the standalone server.js
- Go to the browser dev tools and check the response headers for .next/static and /public assets

### Describe the Bug

The headers (Cache-Control and other options mentioned here: https://nextjs.org/docs/pages/api-reference/next-config-js/headers#options) are correctly set for /public.

But they are missing for .next/static.

### Expected Behavior

Headers in next.config are applied to .next/static as well.

**Comment by michaelangeloio** [comment]
+1

**Comment by cosieLq** [comment]
When will this issue be triaged?

**Comment by ztanner** [comment]
Hi, as per the docs [here](https://nextjs.org/docs/app/api-reference/next-config-js/headers#headers-with-i18n-support), if you don't specify `locale: false` on these headers, each source is automatically prefixed to handle the configured locales. Since `/_next/static` is not locale specific, these files won't be matched unless you make this configuration change.

Going to close this out but feel free to ping if it seems like this is still not working after making this change!
