### ISSUE TITLE
The useSearchParams() and useParams() hooks behave inconsistently between app and page router

### ISSUE THREAD

**Issue by alvarlagerlof** [vercel/next.js#54242]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:49:43 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 20.1.0
      npm: 9.6.4
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.18-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/alvarlagerlof/next-test-params

### To Reproduce

1. Run the linked repro or open https://next-test-params.vercel.app/
2. Click the links and compare the rendered return value of the hooks between them.

For example:
https://next-test-params.vercel.app/pages/foobar
<img width="244" alt="image" src="https://github.com/vercel/next.js/assets/14835120/94da2ed0-6067-4303-8713-abc9db7262a0">

vs

https://next-test-params.vercel.app/app/foobar
<img width="248" alt="image" src="https://github.com/vercel/next.js/assets/14835120/67b47e1c-5f85-47cd-8126-705776469870">

The `DemoComponent` component is rendered for all of the links, so the the user code is the same for all of the links.

### Describe the Bug

In the pages router, `useParams()` cannot be used to extract a `/[slug]` from a URL. But using `useSearchParams()` does not return the information.

In the app router, `useParams()` must be used to extract a `/[slug]`, and `useSearchParams()` does not return the information.

This is problematic if you want to have components that work in both the pages router and the app router.

### Expected Behavior

The return values are consistent across the app and pages router. Or at least, the same hook is used to extract `/[slug]`,

<sub>[NEXT-1536](https://linear.app/vercel/issue/NEXT-1536/the-usesearchparams-and-useparams-hooks-behave-inconsistently-between)</sub>

**Comment by icyJoseph** [comment]
Hi,

I think this is somewhat expected. 

The first premise being that `next/navigation` is designed for App Router, but has a thin compatibility layer for Pages Router.

For example: 

> If an application includes the /pages directory, useSearchParams will return ReadonlyURLSearchParams | null. The null value is for compatibility during migration since search params cannot be known during pre-rendering of a page that doesn't use getServerSideProps

For the App Router:

- useParams, returns an object containing the current route's filled in [dynamic parameters](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes).
- useSearchParams, returns a read-only version of the [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) interface, which includes utility methods for reading the URL's query string

In `https://next-test-params.vercel.app/app/foobar`, given the route `app/[slug]/page.tsx`, it makes sense to see, an object with a key named slug, and value `foobar`, and empty searchParams, because there's no queries on the URL.

What I think happens is that in Pages Router. The `[slug]` bit is taken as a query too. With this much, it makes sense that useSearchParams is doing that. Why does `useParams` return `null`? Well because there's an early escape in the `useParams` implementation that detects Pages Router, and skips doing any work at all, by just returning `null`.

Since you are using TS, when you run your project there'll be a file called, `next-env.d.ts`:

```ts
/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference types="next/navigation-types/compat/navigation" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/basic-features/typescript for more information.

```

Now your `useParams` hook has a signature that returns `null` in pages router.

However, I think the bigger issue here is that in Pages Router, url params and actual queries, were all under `Router.query`, which could be potentially problematic, whereas, in the App Router, we finally get them separately.

So maybe what you want to do is merge both and mimic the old Router.query behavior?

```tsx
import { useMemo } from "react";
import { useParams, useSearchParams } from "next/navigation";

export function DemoComponent() {
  const params = useParams();
  const searchParams = useSearchParams();

  const oldQueries = useMemo(
    () => ({
      ...Object.fromEntries(searchParams?.entries() ?? []),
      ...params,
    }),
    [params, searchParams]
  );

  return (
    <div>
      <h2>Old queries</h2>

      <pre>{JSON.stringify(oldQueries, null, 2)}</pre>

      <h2>useParams()</h2>
      <pre>{JSON.stringify(params, null, 2)}</pre>

      <h2>useSearchParams()</h2>
      <pre>
        {JSON.stringify(
          Object.fromEntries(searchParams ? searchParams.entries() : []),
          null,
          2
        )}
      </pre>
    </div>
  );
}
``` 

Something like that... I am not sure it works 100% of the time though.

**Comment by alvarlagerlof** [comment]
> The first premise being that next/navigation is designed for App Router, but has a thin compatibility layer for Pages Router.

The thing is that if there's at least not some level of similarity of the return values, it's not feasible to do an incremental navigation. Something that has been clearly promoted as possible and recommended to do.

When we started migrating to the app router, we first did things to increase compatibility of the existing codebase and components to the app router. Since `next/router` is completely unsupported on it, we actually moved everything to `next/navigation`. This was before anything at all was on the app router. When doing that, we made use of `useSearchParams()´.

We've got a bunch of modals that render from `_app.tsx` as well as `layout.tsx`. The some of the modals read `/[slug]` and use that for some behaviour. They probably shouldn't but this is some legacy code that won't be gone in a while. Incremental navigations cannot ignore cases like this I think. It will be the reality for a bunch of codebases. It's a luxury to be able to know that all of the code on a layout + page will only run on the app router or only pages router.

So when we started migrating pages to the pages router, we ran into this difference in the hook behaviour. They components in the modals depending on `/[slug]` do have to work in both of the routers while the code is the same. I strongly believe that Next.js should support this usecase without user-space hacks.

> So maybe what you want to do is merge both and mimic the old Router.query behavior?

I thought of this too after writing this issue. Something like this is probably what we'll have to until (hopefully) the api changes to have more similarity between the routers.
