### ISSUE TITLE
calling router.refresh in a parallel route breaks routing without any error messages

### ISSUE THREAD

**Issue by akomm** [vercel/next.js#54723]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.20-canary.12
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/wild-browser-3yjcn4

### To Reproduce

- Open the sandbox. 
- Navigate using the links on the page.
- goto /create
- click the "break" button
- try goto /

### Describe the Bug

Routing stops working, both router and Link after router.refresh().

### Expected Behavior

Routing should work.

**Comment by akomm** [comment]
It appears the bug also happens, when you call `router.refresh()` outside the parallel route, but while one is either 1. active or 2. soft-active, means you navigated away from it softly, but the "page" is still mounted. The router breakage happens at the route tree where router.refresh was called all the way down, but seem to continue working upwards.

**Comment by tsnieman** [comment]
Ran into this issue today on `13.5.6` (the codesandbox linked in OP is @ `13.4.20-canary.35`).

My issue presents the same way as described / in the codesandbox:
- I have a parallel route (a modal)
- The modal renders a `"use client";` component which calls `router.refresh()`
- After calling `router.refresh()`:
  - the parallel route data does not refresh in the browser (though I _can_ see the refreshed data in my CLI output via `console.log`)
  - the router breaks entirely and i cannot navigate anywhere

I don't have a solution, but I do have a workaround: instead of `router.refresh()`, i call ```router.push(`?${new Date().valueOf()}`);``` to append a querystring which, effectively, refreshes the parallel route data as expected. Unintuitive, but it works.

I'd really like to see some acknowledgement and progress on this issue, as **breaking the router when `router.refresh()` is used** seems pretty serious.

**Comment by flsilva** [comment]
I recreated this issue with Next v14.0.4-canary.14 and I could only reproduce it on localhost, on Vercel it does work.

While it's great to have it working on Vercel, we need it working on localhost too as that's where we build and test apps most of the time.

Link to Vercel deployment (can't reproduce):

https://next-v14-router-refresh-issue-1.vercel.app/

Link to GitHub repo (can reproduce on localhost):

https://github.com/flsilva/next-v14-router-refresh-issue-1

**Comment by tsnieman** [comment]
I found several related issues.

This one is probably most notable:
https://github.com/vercel/next.js/issues/54173#issuecomment-1847825539

[The link above](https://github.com/vercel/next.js/issues/54173#issuecomment-1847825539) is to my own reproduction in `next@14.0.5-canary.2`, but you'll also find multiple videos of this issue and other reproductions.
