### ISSUE TITLE
Build with fetch failed while prerender dynamic page...

### ISSUE THREAD

**Issue by lwt09** [vercel/next.js#55042]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/lwt09/next-demo

### To Reproduce

here is my code below
<img width="782" alt="image" src="https://github.com/vercel/next.js/assets/105496554/212ffc9a-cf02-4699-a224-57550c12e47b">
<img width="688" alt="image" src="https://github.com/vercel/next.js/assets/105496554/2e5975eb-d54e-487d-a5e7-c123ad094ab3">

i am trying to get data from next-api-route.And i works well with dev env.
but it throw err while `npm run build`..
<img width="930" alt="image" src="https://github.com/vercel/next.js/assets/105496554/a7d6ca19-2931-4e8c-874d-c09f83e30107">

I had add cache: "no-stroe" into fetch option(request ) .Document point out it will convert  page into dynamic route which will not preRender in building. why so？

in addition ， if i add `export const dynamic = 'force-dynamic' into current page , i would not throw err

### Current vs. Expected behavior

i think it's correct to run with no-cache running time both in dev and prod..

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020
    Binaries:
      Node: 20.5.1
      npm: 9.8.0
      Yarn: N/A
      pnpm: 8.6.12
    Relevant Packages:
      next: 13.4.12
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Data fetching (gS(S)P, getInitialProps)

### Additional context

local env..

**Comment by lwt09** [comment]
i have replace localhost with 127.0.0.1 ，it still don't work with build.

but if i add `export const dynamic = 'force-dynamic'` and 127.0.0.1 ， it works! why 

why no-store doesn't work

**Comment by icyJoseph** [comment]
This is happening because, _during build time_, `next build`, there's no server to handle the `/api/test-cache` route. 

Another way to see this is that you are trying to fly a request out to the internet and back to your server, but you are right in the middle of building that server.

When you do `force-dynamic`, you are telling next.js to not build this page during `next build`, and it'll only try to reach to `/api/test-cache` when doing receiving a request for this page during `next start`

And that's not very optimal, because you are already on the server. You don't need to reach for an API route, just get the data you need from its source.

**Comment by lwt09** [comment]
> This is happening because, _during build time_, `next build`, there's no server to handle the `/api/test-cache` route.
> 
> Another way to see this is that you are trying to fly a request out to the internet and back to your server, but you are right in the middle of building that server.
> 
> When you do `force-dynamic`, you are telling next.js to not build this page during `next build`, and it'll only try to reach to `/api/test-cache` when doing receiving a request for this page during `next start`
> 
> And that's not very optimal, because you are already on the server. You don't need to reach for an API route, just get the data you need from its source.

thanks for reply.

while learning from docs api, i thought that whether build static page or not depends on the server component is static render or dynamic render [switch to dynamic](https://nextjs.org/docs/app/building-your-application/rendering/server-components#switching-to-dynamic-rendering)

and i opened no-cache option is order to switch to dynamic ..

all thinking above is correct or not ? ...
next13 break a lot from 12, i confused about this just for learning next13-cache-system...

and if i don't use api to connet to database, i should just use dataBase-connection instance to get data from database in page?
thank you

**Comment by icyJoseph** [comment]
This has nothing to do with Next 13 (I think you mean App Router), rather is something that developers often overlook.

I've helped people with this issue in Pages Router, inside getStaticProps or getServerSideProps many times.

Take for example from getServerSideProps documentation:

- https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props#getserversideprops-or-api-routes
> It can be tempting to reach for an [API Route](https://nextjs.org/docs/pages/building-your-application/routing/api-routes) when you want to fetch data from the server, then call that API route from getServerSideProps. This is an unnecessary and inefficient approach, as it will cause an extra request to be made due to both getServerSideProps and API Routes running on the server.

The root problem here being that you are trying to reach for an endpoint that doesn't exist, yet... because you are building the server.

Also, IIRC, POST requests are not cached either? I might be wrong on that one. As I am saying that's not the issue here, but that you are reaching for an endpoint that is not yet running.

And yes, you should just connect to your DB from that page. It is a server component, so no client side JavaScript bundle will exist for it. 

Look at this demo: https://how-is-this-not-illegal.vercel.app/ and source: https://github.com/rauchg/how-is-this-not-illegal, they literally query the DB inside the Server Component. That's one of the main benefits of them!

**Comment by lwt09** [comment]
> This has nothing to do with Next 13 (I think you mean App Router), rather is something that developers often overlook.
> 
> I've helped people with this issue in Pages Router, inside getStaticProps or getServerSideProps many times.
> 
> Take for example from getServerSideProps documentation:
> 
> * https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props#getserversideprops-or-api-routes
> 
> > It can be tempting to reach for an [API Route](https://nextjs.org/docs/pages/building-your-application/routing/api-routes) when you want to fetch data from the server, then call that API route from getServerSideProps. This is an unnecessary and inefficient approach, as it will cause an extra request to be made due to both getServerSideProps and API Routes running on the server.
> 
> The root problem here being that you are trying to reach for an endpoint that doesn't exist, yet... because you are building the server.
> 
> Also, IIRC, POST requests are not cached either? I might be wrong on that one. As I am saying that's not the issue here, but that you are reaching for an endpoint that is not yet running.
> 
> And yes, you should just connect to your DB from that page. It is a server component, so no client side JavaScript bundle will exist for it.
> 
> Look at this demo: https://how-is-this-not-illegal.vercel.app/ and source: https://github.com/rauchg/how-is-this-not-illegal, they literally query the DB inside the Server Component. That's one of the main benefits of them!

Thank you I seem to understand ..
