### ISSUE TITLE
Invalid ERR_INVALID_ARG_TYPE on SIGINT

### ISSUE THREAD

**Issue by Yovach** [vercel/next.js#55605]
### Link to the code that reproduces this issue

https://github.com/Yovach/nextjs-sigint

### To Reproduce

1. Install Node.js 20 (I din't tried 18)
2. Start the application with `pnpm dev`
3. Press CMD/CTRL + C

### Current vs. Expected behavior

Current :
 X uncaughtException: TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('SIGINT')
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at process.exit (node:internal/process/per_thread:188:24)
    at process.cleanup (/home/quentin/labs/reproduction-app/node_modules/.pnpm/next@13.5.1-canary.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/start-server.js:208:29)
    at process.emit (node:events:526:35) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Following the previous step, the `next dev` server should gracefully stop without error like in `13.4.19`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Mon Aug 7 19:01:48 UTC 2023
    Binaries:
      Node: 20.7.0
      npm: 10.1.0
      Yarn: 1.22.19
      pnpm: 8.7.6
    Relevant Packages:
      next: 13.5.1-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A


warn  - Latest canary version not detected, detected: "13.5.1-canary.1", newest: "13.5.1".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app)

**Comment by vanpham1986** [comment]
GitHub - Yovach/nextjs-sigint 
  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
GitHub - Yovach&#47;nextjs-sigint
 
Contribute to Yovach&#47;nextjs-sigint development by creating an account on GitHub.
  |   |

  |

  |

  


Được gửi từ Yahoo Mail cho iPhone


Vào Thứ Tư, tháng 9 20, 2023, 1:49 SA, Quentin ***@***.***> đã viết:




Link to the code that reproduces this issue

https://github.com/Yovach/nextjs-sigint

To Reproduce
   
   - Start the application with pnpm dev
   - Press CMD/CTRL + C

Current vs. Expected behavior

Current :
X uncaughtException: TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('SIGINT')
at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
at process.exit (node:internal/process/per_thread:188:24)
at process.cleanup ***@***.******@***.******@***.***/node_modules/next/dist/server/lib/start-server.js:208:29)
at process.emit (node:events:526:35) {
code: 'ERR_INVALID_ARG_TYPE'
}

Following the previous step, the next dev server should gracefully stop without error like in 13.4.19

Verify canary release
   
   -  I verified that the issue exists in the latest Next.js canary release

Provide environment information
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Mon Aug 7 19:01:48 UTC 2023
    Binaries:
      Node: 20.7.0
      npm: 10.1.0
      Yarn: 1.22.19
      pnpm: 8.7.6
    Relevant Packages:
      next: 13.5.1-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A


warn  - Latest canary version not detected, detected: "13.5.1-canary.1", newest: "13.5.1".
        Please try the latest canary version (`npm install ***@***.***`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
Which area(s) are affected? (Select all that apply)

CLI (create-next-app)

Additional context

No response

**Comment by ovflowd** [comment]
Can confirm and reproduce

**Comment by DaKheera47** [comment]
Same issue here! for me this happens when i `ctrl + c` to close the dev server

**Comment by peter-kuhmann** [comment]
❌ I get the same error with Node.js v20.3.1.

✅  But with Node.js v18.18.0 the problem does not occur.

**Comment by Yovach** [comment]
> ❌ I get the same error with Node.js v20.3.1.
> 
> ✅ But with Node.js v18.18.0 the problem does not occur.

Have you tried the latest version ? https://github.com/vercel/next.js/releases/tag/v13.5.2

**Comment by peter-kuhmann** [comment]
Ah yes, 13.5.2 fixes it! Thanks @Yovach 🙂
