### ISSUE TITLE
[Bug] Not found not working with Route groups

### ISSUE THREAD

**Issue by theoludwig** [vercel/next.js#55717]
### Link to the code that reproduces this issue

https://github.com/theoludwig/nextjs-bug-not-found-in-route-groups

### To Reproduce

1. `npx create-next-app@latest`
2. Create a [Route Group](https://nextjs.org/docs/app/building-your-application/routing/route-groups): `(dashboard)` in the App directory.
3. Remove the default page in `app/page.tsx`.
4. Create a [not-found](https://nextjs.org/docs/app/api-reference/file-conventions/not-found) page inside the route group: `app/(dashboard)/not-found.tsx`.
5. `npm run dev`
6. Go to <http://127.0.0.1:3000/404>, and notice that the not found page is the default one, and not the one defined in `app/(dashboard)/not-found.tsx`.

### Current vs. Expected behavior

Inside Route Groups, we should be able to define Not found pages.

Currently when defining a not found page in a route group, it is ignored.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Wed, 13 Sep 2023 08:37:40 +0000
Binaries:
  Node: 20.7.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: 8.7.0
Relevant Packages:
  next: 13.5.3-canary.0
  eslint-config-next: 13.5.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

<sub>[NEXT-1650](https://linear.app/vercel/issue/NEXT-1650/[bug]-not-found-not-working-with-route-groups)</sub>

**Comment by tomferez** [comment]
Same here

**Comment by joulev** [comment]
The global 404 file *must* be `app/not-found.tsx` with nothing in between, whether it's a route group, a normal route, or anything.

If you want to add a 404 file in any custom directories, you can use a catch-all route

```ts
app/
  (dashboard)/
    page.tsx
    [...not-found]/
      page.tsx
```

**Comment by theoludwig** [comment]
> The global 404 file _must_ be `app/not-found.tsx` with nothing in between, whether it's a route group, a normal route, or anything.
> 
> If you want to add a 404 file in any custom directories, you can use a catch-all route
> 
> ```ts
> app/
>   (dashboard)/
>     page.tsx
>     [...not-found]/
>       page.tsx
> ```

@joulev Okay, thanks for your answer, and the workarounds you provided, but isn't the expected behavior that `not-found.tsx` should work in Route Groups like it works in "normal" routes?

**Comment by joulev** [comment]
@theoludwig `not-found` works like this:

* For a normal `not-found`, it catches `notFound()` calls – this is kinda like the *explicit* not found.

* For the root `not-found`, i.e. `app/not-found.tsx` with *no folders in between*, other than catching the `notFound` in e.g. `app/(group)/page.tsx`, it also catches unmatched routes (*implicit* not found), making it the global 404.

* There is no built-in mechanism to catch unmatched routes *starting with a particular directory* (e.g. `app/en/*` go to `app/en/not-found`); but you can implement your own catcher very easily with a catch-all route as I explained above &ndash; IMO that's _not_ a workaround, [SvelteKit documents that as a valid way to handle custom 404's](https://kit.svelte.dev/docs/advanced-routing#rest-parameters-404-pages).

**Comment by theoludwig** [comment]
**Note:** The reproduction repo is as minimal as possible to reproduce the issue, but not the issue itself I encountered in my production code. However, I can't share the "real" code, not open source.

To explain further my issue:

I would like to use the Layout from the dashboard for the `not-found` error (`app/(dashboard)/layout.tsx`), so `not-found.tsx` must be in this Route Group. I tried to put `not-found.tsx` at the root, `app/not-found.tsx`, however even if that now "works", it doesn't use the layout defined in `app/(dashboard)/layout.tsx`.

The reason, that I put routes inside the `(dasboard)` route group, is that my application is basically made up of the `/login` route and a bunch of "dashboard" routes only accessible to authenticated users (and with admin role), so I do the verification of the authentication inside `app/(dashboard)/layout.tsx` + basic layout not needed/wanted in `/login`.

**Comment by joulev** [comment]
Well as I explained above, your `not-found` is not the *root* `not-found` so that cannot work automagically. That's just not the designed behaviour of the root `not-found`.

Now say we lived in a world where `app/(routegroup)/not-found.tsx` could assume the role of the global 404. We have this folder structure:

```
app/
  not-found.tsx (1)
  (group1)/
    layout.tsx
    page.tsx
    not-found.tsx (2)
    folder1-1/page.tsx ...
    folder1-2/page.tsx ...
  (group2)/
    layout.tsx
    not-found.tsx (3)
    folder2-1/page.tsx ...
    folder2-2/page.tsx ...
```

and the user navigates to `/folder3`. What `not-found` file should be displayed? It's unclear.

The only `not-found` file that can take the role of the 404 page is the very root `not-found` file, whose path *must* be `app/not-found.tsx`. Any folders standing between "app" and "not-found" are not allowed – they would make the `not-found` file become a regular `not-found` file and only triggered on `notFound`. If you want to implement a custom catcher, you need to make a catch-all route.

---

Now you can say those `not-found.tsx` might "conflict" with each other (just like you can't have `app/(group2)/page.tsx`). In that case, I would imagine Next.js `not-found` to work like this:

1. User navigates to `/random/route/nonexistent`
2. `/random/route/nonexistent/not-found.tsx` is displayed
3. If above is not available, `/random/route/not-found.tsx` is displayed
4. If above is not available, `/random/not-found.tsx` is displayed
5. If above is not available, `/not-found.tsx` is displayed
6. If above is not available, default 404 is displayed

(Current behaviour doesn't have the steps 2–5). I agree this would be a sensible approach, but it would be a breaking change for the app router and IMO, only bring more confusion to the way the router works.

UX would not be too good either. The global 404 is supposed to display to the user that "the pathname you entered is wrong, please check the *entire* pathname". `https://github.com/settings/123` doesn't display the left sidebar that all valid `https://github.com/settings/*` routes display.

---

**Disclaimer:** I'm not part of the team and only answer here based on the way I understand the current app router design. I support this design and consider any changes to the current `not-found` structure to just make it confusing – though the team might think otherwise.

**Comment by theoludwig** [comment]
Closing, as the use case is not as straightforward as we might think, and the behavior of Next.js about 404 not found handling is good enough in many cases. :+1:
Thanks again for your help and responses.
