### ISSUE TITLE
PageNotFoundError: Cannot find module for page: /

### ISSUE THREAD

**Issue by supercoolx** [vercel/next.js#55815]
### Link to the code that reproduces this issue

https://github.com/supercoolx/REX-Protocol/actions/runs/6273810642/job/17038178995

### To Reproduce

I want to export next app.
But the export command give me errors.
```
info  - using build directory: E:\works\rex\flowbite-next-starter\.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "E:\works\rex\flowbite-next-starter\next.config.js". Generating map from "./pages"
info  - Launching 7 workers
info  - Copying "public" directory
info  - Exporting (2/2)
PageNotFoundError: Cannot find module for page: /
    at Object.getPagePath (E:\works\rex\flowbite-next-starter\node_modules\next\dist\server\require.js:77:15)
    at E:\works\rex\flowbite-next-starter\node_modules\next\dist\export\index.js:375:48
    at Array.map (<anonymous>)
    at E:\works\rex\flowbite-next-starter\node_modules\next\dist\export\index.js:366:69
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (E:\works\rex\flowbite-next-starter\node_modules\next\dist\trace\trace.js:79:20) {
  code: 'ENOENT'
}
```
How can I fix this issue?

### Current vs. Expected behavior

I don't know how to fix this issue.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Node.js version: 18.16.1
Next.js version: 13.0.6
OS: Windows 10
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

Project structure
![image](https://github.com/vercel/next.js/assets/94512319/d770bd6f-45fa-40c0-bf0d-1214d4bcd1b3)

**Comment by FerrariAndrea** [comment]
Your repository is not accessible, we can't read it, it is a 404, maybe is private.
Anyway, it is really strange that your build command is looking for './pages' meanwhile you have an './app' structure, try to check your next.js version.

Read the documentation looking for the differences between the 'pages' and 'app' versions:
https://nextjs.org/docs
(in the left corner you can switch between them)

Last stuff, did you try with 'next build' or 'next dev'  instead of 'next export'?
