### ISSUE TITLE
'404 Not Found' for all resources

### ISSUE THREAD

**Issue by batazor** [vercel/next.js#56215]
### Link to the code that reproduces this issue

https://github.com/shortlink-org/shortlink/tree/main/ui/nx-monorepo

### To Reproduce

1. Upgrade to the latest version nextjs (or > 13.4.6)
2. cd ./package/next
3. npm run start

### Current vs. Expected behavior

Success starting my project

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64
    Binaries:
      Node: 20.2.0
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: 8.6.1
    Relevant Packages:
      next: 13.5.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: export
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

The application is successfully built, but in development mode for some reason it cannot find the built files

**Comment by batazor** [comment]
<img width="959" alt="Screenshot 2023-09-29 at 16 36 22" src="https://github.com/vercel/next.js/assets/1643797/68474dbc-901f-4841-b2c0-47baeeb06c20">

**Comment by khalilsarwari** [comment]
This is happening for us in production when leaving the landing page for the following resource:

_next/static/chunks/webpack-8147f10d25df47dc.js
Request Method:
GET
Status Code:
404 Not Found

**Comment by joshuamanns** [comment]
This seems related to https://github.com/vercel/next.js/issues/47799 which is a problem with the mime types of static files in standalone builds for some reason.

**Comment by paolomainardi** [comment]
Having the same issue as described here: https://github.com/vercel/next.js/issues/49283#issuecomment-1883541258

**Comment by samcx** [comment]
Hi everyone—

This issue has become stale but the behavior is expected—the static files are `404`ing because with `output: 'standalone'`, we automatically create a standalone folder that copies only the necessary files for a production deployment including select files in `node_modules`.

The minimal server does not copy the public or .next/static folders by default as these should ideally be handled by a CDN instead, although these folders can be copied to the standalone/public and standalone/.next/static folders manually, after which server.js file will serve these automatically.

To copy these and then start this local minimal server locally, you can do something like this:

```
pnpm build && cp -r public .next/standalone/ && cp -r .next/static .next/standalone/.next/ && node .next/standalone/server.js
```

- https://nextjs.org/docs/app/api-reference/next-config-js/output#automatically-copying-traced-files

I have also just created a PR to update our documentation with this → https://github.com/vercel/next.js/pull/72432.

I will closing this PR since this is a non-issue!
