### ISSUE TITLE
Route "app/api/auth/[...nextauth]/route.ts" does not match the required types of a Next.js Route - "authOptions" is not a valid Route export field.

### ISSUE THREAD

**Issue by nicitaacom** [vercel/next.js#56832]
### Link to the code that reproduces this issue

https://github.com/nicitaacom/acc2-auth_form_next_supabase_1/blob/development/app/api/auth/%5B...nextauth%5D/route.ts

### To Reproduce

1. Open reproduction link
2. Make git clone
3. open terminal with ctrl+` and type `pnpm build`

### Current vs. Expected behavior

I wait no error during build - but got the error
```
app/api/auth/[...nextauth]/route.ts
Type error: Route "app/api/auth/[...nextauth]/route.ts" does not match the required types of a Next.js Route.
  "authOptions" is not a valid Route export field.
```
I tried this solution - it also doesn't work  
![image](https://github.com/vercel/next.js/assets/39565703/521287eb-e18e-47e7-977d-0d80784e00ab)

I use this guide but for faceit provider - https://www.youtube.com/watch?v=md65iBX5Gxg&t=379s&ab_channel=JackHerrington

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
pnpx --no-install next info
/home/kali/.local/share/pnpm/store/v3/tmp/dlx-118272:
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/--no-install: Not Found - 404

This error happened while installing a direct dependency of /home/kali/.local/share/pnpm/store/v3/tmp/dlx-118272

--no-install is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

Which area(s) are affected? (Select all that apply)
next/auth

**Comment by balazsorban44** [comment]
NOTE: This issue is unrelated to Next.js, but I will answer as I maintain `next-auth` as well. (Next.js and NextAuth.js - albeit the name - are unrelated projects.)

The place for `authOptions` in `[...nextauth]/route.ts` was just a convention. It came from before when the restriction for Next.js was introduced to only allow certain experts from Route Handlers. But you can put that config in a different file, any other place.

In fact, our official example now recommends a top-level auth.ts file instead. See: https://github.com/nextauthjs/next-auth-example/blob/main/auth.ts
