### ISSUE TITLE
Module not found: Can't resolve './my-app/app/favicon.ico?__next_metadata__'

### ISSUE THREAD

**Issue by PierreLepagnol** [vercel/next.js#57216]
### Link to the code that reproduces this issue

https://github.com/PierreLepagnol/test_nextjs

### To Reproduce

1. Create a new app with : ` pnpm create next-app@latest`
2. Go to the created app : `cd my-app`
3. Run the dev server `pnpm dev` 

### Current vs. Expected behavior

Following the step from the previous section we should not have any error and should be able to run the dev server normally BUT HERE we got : 

`(base) lepagnol@chmtlp61:~/Documents/0#Perso/apps/my-app$ pnpm dev

> my-app@0.1.0 dev /home/lepagnol/Documents/0#Perso/apps/my-app
> next dev

  ▲ Next.js 13.5.6
  - Local:        http://localhost:3000

 ✓ Ready in 4.8s
 ○ Compiling /page ...
 ⨯ ./
Module not found: Can't resolve '/home/lepagnol/Documents/0#Perso/apps/my-app/app/favicon.ico?__next_metadata__'

https://nextjs.org/docs/messages/module-not-found
 ⨯ ./
Module not found: Can't resolve '/home/lepagnol/Documents/0#Perso/apps/my-app/app/favicon.ico?__next_metadata__'

https://nextjs.org/docs/messages/module-not-found
 ⨯ ./
Module not found: Can't resolve '/home/lepagnol/Documents/0#Perso/apps/my-app/app/favicon.ico?__next_metadata__'

https://nextjs.org/docs/messages/module-not-found
`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #181-Ubuntu SMP Fri Sep 1 13:41:22 UTC 2023
Binaries:
  Node: 20.5.1
  npm: 10.2.1
  Yarn: 3.6.1
  pnpm: 8.9.2
Relevant Packages:
  next: 13.5.6
  eslint-config-next: 13.5.6
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app), Metadata (metadata, generateMetadata, next/head)

### Additional context

- node --version : v20.5.1
- pnpm --version : 8.9.2

**Comment by daxegrand** [comment]
I have the same issue.

**Comment by L968** [comment]
Same here...

**Comment by charleskwame** [comment]
Currently staring at an error like this, and I am tired...

**Comment by huozhi** [comment]
The reproduction is 404 for me, can you make it public? Or anyone having this problem can share the reproduction here? Thanks

**Comment by charleskwame** [comment]
SOLUTION ---
Check the folders in the project, if they have special characters in their names like (#) it'll cause this error. It took me hours but yeah that's the problem

**Comment by charleskwame** [comment]
> The reproduction is 404 for me, can you make it public? Or anyone having this problem can share the reproduction here? Thanks

SOLUTION ---
Check the folders in the project, if they have special characters in their names like (#) it'll cause this error. It took me hours but yeah that's the problem

**Comment by itz-Me-Pj** [comment]
@timneutkens I can work on this bug/issue. But how you will like me to approach it?
should I add validations for project naming conventions or add something in error like make sure the folder structure doesn't include special characters like ("#")?

**Comment by balazsorban44** [comment]
We could not detect a valid reproduction link. **Make sure to follow the bug report template carefully.**

### Why was this issue closed?

To be able to investigate, we need access to a reproduction to identify what triggered the issue. We need a link to a **public** GitHub repository ([template for App Router](https://github.com/vercel/next.js/tree/canary/examples/reproduction-template), [template for Pages Router](https://github.com/vercel/next.js/tree/canary/examples/reproduction-template-pages)), but you can also use these templates: [CodeSandbox: App Router](https://codesandbox.io/s/github/vercel/next.js/tree/canary/examples/reproduction-template) or [CodeSandbox: Pages Router](https://codesandbox.io/s/github/vercel/next.js/tree/canary/examples/reproduction-template-pages).

The bug template that you filled out has a section called "Link to the code that reproduces this issue", which is where you should provide the link to the reproduction.

- If you did not provide a link or the link you provided is not valid, we will close the issue.
- If you provide a link to a private repository, we will close the issue.
- If you provide a link to a repository but not in the correct section, we will close the issue.

### What should I do?

Depending on the reason the issue was closed, you can do the following:

- If you did not provide a link, please open a new issue with a link to a reproduction.
- If you provided a link to a private repository, please open a new issue with a link to a public repository.
- If you provided a link to a repository but not in the correct section, please open a new issue with a link to a reproduction in the correct section.

**In general, assume that we should not go through a lengthy onboarding process at your company code only to be able to verify an issue.**

### My repository is private and cannot make it public

In most cases, a private repo will not be a sufficient **minimal reproduction**, as this codebase might contain a lot of unrelated parts that would make our investigation take longer. Please do **not** make it public. Instead, create a new repository using the templates above, adding the relevant code to reproduce the issue. Common things to look out for:

- Remove any code that is not related to the issue. (pages, API routes, components, etc.)
- Remove any dependencies that are not related to the issue.
- Remove any third-party service that would require us to sign up for an account to reproduce the issue.
- Remove any environment variables that are not related to the issue.
- Remove private packages that we do not have access to.
- If the issue is not related to a monorepo specifically, try to reproduce the issue without a complex monorepo setup

### I did not open this issue, but it is relevant to me, what can I do to help?

Anyone experiencing the same issue is welcome to provide a minimal reproduction following the above steps by opening a new issue.

### I think my reproduction is good enough, why aren't you looking into it quickly?

We look into every Next.js issue and constantly monitor open issues for new comments.

However, sometimes we might miss one or two due to the popularity/high traffic of the repository. We apologize, and kindly ask you to refrain from tagging core maintainers, as that will usually not result in increased priority.

Upvoting issues to show your interest will help us prioritize and address them as quickly as possible. That said, every issue is important to us, and if an issue gets closed by accident, we encourage you to open a new one linking to the old issue and we will look into it.

### Useful Resources

- [How to Contribute to Open Source (Next.js)](https://www.youtube.com/watch?v=cuoNzXFLitc)
- [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
- [Reporting a Next.js bug](https://github.com/vercel/next.js/blob/canary/.github/ISSUE_TEMPLATE/1.bug_report.yml)
- [Next.js Triaging issues](https://github.com/vercel/next.js/blob/canary/contributing/repository/triaging.md)
