### ISSUE TITLE
Two copies of react-dom are added to bundle

### ISSUE THREAD

**Issue by nfiacco** [vercel/next.js#57733]
### Link to the code that reproduces this issue

https://github.com/vercel/next.js/issues/51508

### To Reproduce

Same issue as https://github.com/vercel/next.js/issues/51508

### Current vs. Expected behavior

There should only be one version of react-dom bundled.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 19.7.0
  npm: 9.7.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 13.5.6
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by zortos293** [comment]
+1

**Comment by zortos293** [comment]
i get 
Import trace for requested module:
./node_modules/next/dist/shared/lib/bloom-filter.js
./node_modules/next/dist/shared/lib/router/router.js

./node_modules/next/dist/shared/lib/escape-regexp.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:

**Comment by icyJoseph** [comment]
This is a `non-issue`, that just happens to be slightly annoying.

It is a `non-issue` because your users will NOT download react-dom twice. If they are in app router pages, they download the special react-dom bundle, and if they are in pages router pages, they download the other one.

The Next.js team, will eventually, drop one of them depending on the build structure.

- https://github.com/vercel/next.js/issues/56400#issuecomment-1747051290
- https://github.com/vercel/next.js/issues/56063#issuecomment-1737229090
