### ISSUE TITLE
Undefined env config values cause validation warnings

### ISSUE THREAD

**Issue by michaldudak** [vercel/next.js#57755]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/xenodochial-antonelli-9x7v6w?file=%2Fnext.config.js%3A8%2C1

### To Reproduce

1. Run `next dev`
2. See the warnings in the console

### Current vs. Expected behavior

Prior to 13.5.5, an env object with undefined values would not cause any validation warnings. In 13.5.5 (and higher) a message is shown saying
```
⚠ Invalid next.config.js options detected: 
⚠     "env.FOO" is missing, expected string
```

In our case, we set some env vars in the CI environment and leave them out in local development.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.17.0
  npm: N/A
  Yarn: N/A
  pnpm: 8.6.12
Relevant Packages:
  next: 13.5.6
  eslint-config-next: 13.5.6
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

I believe the bug was introduced with https://github.com/vercel/next.js/pull/56383

**Comment by michaldudak** [comment]
I just verified: updating the config schema in https://github.com/vercel/next.js/blob/v13.5.5/packages/next/src/server/config-schema.ts#L219 to `z.record(z.string(), z.union([z.string(), z.undefined()])).optional(),` does solve the issue.

**Comment by timneutkens** [comment]
Feel free to open a PR with a test 👍

**Comment by oliviertassinari** [comment]
Oh, interesting, I landed here by luck, wondering why there are warnings for undefined variables.
It's to be noted that it's only because Next.js raises warnings for undefined variables, I could spot dead env variables: https://github.com/mui/mui-x/pull/11181. But yeah, there are env variables that are only relevant when in a preview environment, e.g. COMMIT_REF to link the right CodeSandbox CI npm dependency PR build, so raising warnings in a local environment mode feels off. 

👍 to change this.
