### ISSUE TITLE
Docs: Next Learn -ch 15 Authentication - customer images not showing 

### ISSUE THREAD

**Issue by graemen16** [vercel/next.js#57801]
### What is the improvement or update you wish to see?

After adding auth per chapter 15 I noted customer images are not showing after deploying to Vercel. 
![image](https://github.com/vercel/next.js/assets/69542103/316db09d-5c36-45b8-a0db-8ff7ad831410)

### Is there any context that might help us understand?

I believe this is due to the matcher regex expression in middleware.ts. The customer icon images are in public/customers folder. This folder is not excluded by the regex expression. I resolved by adding customers to the expression:
```
export const config = {
	// https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher
	matcher: ['/((?!api|_next/static|_next/image|customers|favicon.ico).*)'],
};
```
The issue was not apparent on localhost; only after deploying.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/dashboard-app/adding-authentication

**Comment by jeromemeichelbeck** [comment]
I've had the same issue.

Even on localhost.

Yet the url seems right:

http://localhost:3000/**_next/image**?url=%2Fcustomers%2Fdelba-de-oliveira.png&w=32&q=75

**Comment by mukham12** [comment]
@graemen16,

If this issue is still unresolved, I suggest moving it to the [next-learn](https://github.com/vercel/next-learn) repository since that is where the code for this is written. In fact, I already have an open issue there. If you would like to help keep things organized, you can comment about this matter issue under my [existing issue](https://github.com/vercel/next-learn/issues/336).

**Comment by graemen16** [comment]
Hi @mukham12 , thanks for pointing me to next-learn repository. I found issue 337 over there is on the same issue so I'll close this.
