### ISSUE TITLE
Expected a non-empty string

### ISSUE THREAD

**Issue by Tajmirul** [vercel/next.js#57826]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/great-waterfall-7g854p?file=%2Fpages%2Findex.tsx%3A9%2C19

### To Reproduce

I'm trying to migrate next js 14. but Image component is produce an issue. 
```TypeError: Expected a non-empty string```

If i comment out the Image component then application runs fine.

Here is the code:
```
                                    <Image
                                        src={user?.avatar!}
                                        alt={user?.name!}
                                        className="rounded-full"
                                        height={32}
                                        width={32}
                                    />
```

i also tryed like this:
```
                                    {user?.avatar && (
                                        <Image
                                            src={user?.avatar!}
                                            alt={user?.name!}
                                            className="rounded-full"
                                            height={32}
                                            width={32}
                                        />
                                    )}
```

it also does not work.

The error:
![image](https://github.com/vercel/next.js/assets/62275307/6bcb1556-ae34-48d3-8bd4-91a665840aa3)

Currently using:
Next js: `14.0.1`
typescript: `5.2.2`

### Current vs. Expected behavior

it should render the image. but it's throwing an error

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
Binaries:
  Node: 18.18.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.2-canary.1
  eslint-config-next: 13.4.19
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Image optimization (next/image, next/legacy/image)

**Comment by liolle** [comment]
Hi, after check your example, it seems like the error is coming from the way you define the remote pattern configuration. 

You have a TypeError: Expected a non-empty string because you have defined pathname as an empty string in your remotePatterns config.

Next, expect the pathname to either be undefined or a non empty string.

Setting pathname as follwow should work.

All path
-  pathname:"**"

Specific path
- pathname: "/a/ACg8ocK4Ob6kWU4aUcKL8eGlfh-ppMFNRKibNCiJLL20MODsqtE=s96-c"

[Reference](https://nextjs.org/docs/app/api-reference/components/image#remotepatterns)
