### ISSUE TITLE
revalidatePath() does not target only specified route

### ISSUE THREAD

**Issue by codeforkdev** [vercel/next.js#57914]
### Link to the code that reproduces this issue

https://github.com/codeforkdev/next-issue

### To Reproduce

1. Start the application using npm run dev
2. Take note of the timestamps on each page Home, results-1, results-2, results-3
3. On the home page click the "update results-1" button.

### Current vs. Expected behavior

After following these steps I would expect only the /results-1 page timestamp to update, but instead all routes including the home page's data(timestamp) is updated.

It appears revalidatePath("/results-1") is not just revalidating the /results-1 route but all routes within the app.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: windows 11
  Version: 22H2
Binaries:
  Node: v20.9.0
  npm: 10.2.2
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

**Comment by codeforkdev** [comment]
@nikhilsnayak I have not :/. At the moment I'm using raw <a /> tags for pages which I don't want cached.

**Comment by timneutkens** [comment]
When you call `revalidatePath` it currently clears the entire client-side router cache. In the future this will be more granular but right now it's the expected behavior, similar to `revalidateTag`. Note that it only clears the client-side cache, server-side caching is not affected, for server-side caching it only invalidates the specified path.
