### ISSUE TITLE
`redirect` function not respecting `basePath` while used in `server action` (app router)

### ISSUE THREAD

**Issue by fwcontact** [vercel/next.js#58570]
### Link to the code that reproduces this issue

https://github.com/vercel/next.js

### To Reproduce

1. make a route named like "/cart"
2. make a server action, and call "redirect('/cart')" at last
3. deploy the app to a non-root directory like "sample-domain.com/demo"
4. invoke the server action at path like "/demo/test"
5. client browser will actually navigate to the right place, i.e., now at "/demo/cart"
6. but the page will just show the default 404 content

I then tried to change the redirect call to "redirect('/demo/cart')", now the redirection worked, the browser is showing the correct content instead of the 404 page, however, the browser address bar will show the wrong path, which would be "/demo/demo/cart"

### Current vs. Expected behavior

1. make a route named like "/cart"
2. make a server action, and call "redirect('/cart')" at last
3. deploy the app to a non-root directory like "sample-domain.com/demo"
4. invoke the server action at path like "/demo/test"
5. client browser will actually navigate to the right place, i.e., now at "/demo/cart"
6. but the page will just show the default 404 content

Expected:

client browser should navigate to the correct path, and show the correct content, with out having to hard-code the `basePath` in the `redirect` function. meaning, the server action should take `basePath` into consideration automatically.

I also found that the `redirect` function works if called in a `page` or other server components. it's failing only when used in a server action.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.3
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by pedrorebelocosta** [comment]
a similar behavior can be observed when redirecting from server components, I'm not sure if I should open a ticket for that given this one.

**Comment by dev-intermedes** [comment]
Hi, Any new about a fix ?
Thanx

**Comment by coltonehrman** [comment]
I have reproduced the issue here - https://stackblitz.com/edit/stackblitz-starters-usvxxe?file=server.js

The issue is hard to "see", but can be noticed when looking at the network tab.

Here is an example of a "correct" redirect, when the basePath conflicts with Next.js.

<img width="1800" alt="Screenshot 2024-01-04 at 10 51 40 AM" src="https://github.com/vercel/next.js/assets/12456288/9e319af7-519d-44a5-95ad-e2a66dbea4bb">

Here is an example of an "incorrect" redirect, when the basePath does not conflict with Next.js
<img width="1800" alt="Screenshot 2024-01-04 at 10 53 25 AM" src="https://github.com/vercel/next.js/assets/12456288/a9751f3b-ef8d-4a59-b1c8-3a8a1f7fd024">

Notice in this example a full page load happens, you can see this from the network call loading a document page for `/nextapp`.

Here is a recording to see the full redirect.


https://github.com/vercel/next.js/assets/12456288/da3d30e1-5dce-49ca-afca-9d51896b2517
