### ISSUE TITLE
Progressively enhanced forms not working (405: not allowed) when deployed on vercel

### ISSUE THREAD

**Issue by timoclsn** [vercel/next.js#58814]
### Link to the code that reproduces this issue

 https://github.com/timoclsn/next-forms-app

### To Reproduce

1. Visit examaple deployment: https://next-forms-app-beryl.vercel.app/
2. Disable JavaScript in browser
3. Submit the form

### Current vs. Expected behavior

Submitting the p.e. form with JavaScript disabled doesn't work (405: not allowed).

This should work when deployed on Vercel.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.17
  pnpm: 8.9.2
Relevant Packages:
  next: 14.0.4-canary.11
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

This happens when deployed on Vercel. It works locally (in dev and production mode).

**Comment by stevenmunro** [comment]
I'm chiming in because I'm encountering the same problem and I'm keen to stay updated on this discussion. It's imperative that we resolve this swiftly. It's not just about catering to users without JavaScript enabled; it's also about ensuring the integrity of our code. There's a chance there's an issue with my code, and I want to address it promptly to avoid potential future complications.
