### ISSUE TITLE
`TypeError: Roboto is not a function` When Testing Next Fonts With Vitest

### ISSUE THREAD

**Issue by mo-fouad** [vercel/next.js#59701]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
You are using Node.js 18.12.1. For Next.js, Node.js version >= v18.17.0 is required.
```

### Which example does this report relate to?

with-vitest

### What browser are you using? (if relevant)

Google Chrome Version 119.0.6045.159 

### Describe the Bug

I having an Issue in Testing with Vitest, 
I just imported Roboto as flowed.
`import { Roboto } from "next/font/google"; `

I got a `TypeError: Roboto is not a function`. with Vitest Tests.

![Screenshot 2023-12-17 at 01 31 28](https://github.com/vercel/next.js/assets/24290379/1e31baaa-a7a9-43bf-aa1b-ac5d2d6ed25a)

### Expected Behavior

I think it should now have any problem reading next fonts.

### To Reproduce

just import any Google/local font with any page in the example, 
`import { NextFont } from 'next/dist/compiled/@next/font'`
`import { Roboto } from 'next/font/google'`

you can find the issue with Vitest.

**Comment by waigel** [comment]
Hey @mo-fouad,

I think you need to mock the font loader from `next/font/google` in your vitests.
You can do it this way:

```ts
vi.mock('next/font/google', () => ({
  Roboto: () => ({
    style: {
      fontFamily: 'mocked',
    },
  }),
}))
```

**Comment by samcx** [comment]
@waigel Thank you for sharing a possible solution!

@mo-fouad Since there is no public repository or CodeSandbox, I will be closing this issue. Please re-submit a [bug report](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml) with the required <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> so we can take a closer look!
