### ISSUE TITLE
Next App Router Revalidation Issue

### ISSUE THREAD

**Issue by enijar** [vercel/next.js#60120]
### Link to the code that reproduces this issue

https://github.com/enijar/next-app-router-revalidation-issue

### To Reproduce

1. Open http://localhost:3000/
2. Click the first "Test" link
3. Make a note of the date value on /test (e.g. 1704206776517)
4. Click "Back"
5. Click the first "Test" link again
6. Note the date value on the /test page is the same, and has not changed (e.g. 1704206776517)

### Current vs. Expected behavior

Following step 5 (clicking on the same link again), I expect step 6 to show a different value, to revalidate the page I clicked on. I do not expect to see what currently happens, where the same value is shown, and not revalidated.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64
Binaries:
  Node: 18.17.0
  npm: 10.2.1
  Yarn: N/A
  pnpm: 7.29.1
Relevant Packages:
  next: 14.0.5-canary.34
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Additional context

I have a dynamic page that I expect code to be evaluated on every request, but it's not. Even with `export const dynamic = "force-dynamic";` and `export const revalidate = 0;` set, the page value remains cached and only gets revalidated when refreshing the browser manually, or by using the hack below:

```jsx
<button
  type="button"
  onClick={() => {
    router.push("/test");
    router.refresh();
  }}
>
  Test
</button>
```

Here's a demonstration of the reproduction:

https://github.com/vercel/next.js/assets/5284715/3864c445-4bc0-41bc-9ec5-168ac20e9ebf

**Comment by enijar** [comment]
FYI, adding `"use client"` to the top of [src/app/test/page.tsx](https://github.com/enijar/next-app-router-revalidation-issue/blob/main/src/app/test/page.tsx) fixes this issue, but I'm not sure why. This page is a server only page, so not sure why `"use client"` is needed there.

**Comment by rshaul** [comment]
Yeah this has been a topic of much debate over in #54075

The nextjs team has mentioned they are reevaluating the whole caching situation in the app router

but here are the current docs in the meantime

https://nextjs.org/docs/app/building-your-application/caching#router-cache

**Comment by zce** [comment]
My current temporary solution is to bypass the router cache through different query parameters

**Comment by leerob** [comment]
This is working as expected, but heard we can make this behavior more clear. I [just made a video](https://www.youtube.com/watch?v=VBlSe8tvg4U) walking through caching that hopefully will help explain a little bit more. In the instance of the example you provided, a couple things I wanted to mention.

First, rather than using the route segment config options, prefer to use functions like `noStore()` or `cookies()` / `headers()` etc for opt-ing the page into dynamic rendering. This is more commonly how your application will be structured – e.g. this can be a nested component, not necessarily at the top level of the page or layout.

```js
import React from 'react';
import Link from 'next/link';
import { unstable_noStore as noStore } from 'next/cache';

export default function Page() {
  noStore();
  return (
    <main>
      <h1>A: {Date.now()}</h1>
      <Link href="/">Back</Link>
    </main>
  );
}
```

Second, if you want to see a new date value on transition here, you can use `<a>` instead:

```js
export default function Home() {
  return (
    <main>
      <section>
        <a href="/test">Test</a>
      </section>
    </main>
  );
}
```

I understand the date example is commonly used to try and reason about how the system works (that's what I used in my video, too!) but more commonly, there will be some change to your underlying data (whether that's a `fetch` or some database call that you wrap with `unstable_cache`) and you'd use the Next.js APIs to invalidate the cache (`revalidateTag` and `revalidatePath`) which would ensure that new data is fresh on the page transition. Hope this helps! And as mentioned above, there's a [bunch more detail here](https://github.com/vercel/next.js/discussions/54075), as well as the docs, and we're exploring some further options to customize caching.
