### ISSUE TITLE
Date toLocaleString is outputting different on both server and client 

### ISSUE THREAD

**Issue by sandrinjoy** [vercel/next.js#60302]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/flamboyant-waterfall-6x95ny?file=%2Fapp%2Fpage.tsx%3A5%2C38

### To Reproduce

``` 
const date = new Date(message.timestamp).toLocaleString("default", {
    month: "short",
    day: "2-digit",
    year: "numeric",
    minute: "2-digit",
    hour: "2-digit",
  });

```
  
  here is my date in a 'use client' component.
  
 **Warning: Text content did not match. Server: "Jan 06, 2024, 12:30 PM" Client: "06 Jan 2024, 12:30"**

Server is sending a one format, and client function is outputting in another format. 

It seems both server and browser implementation of Date has some differences resulting different outputs.

This is even possible without any configs.

```
const date = new Date(message.timestamp).toLocaleString("default");

```

**Warning: Text content did not match. Server: "1/6/2024, 12:30:36 PM" Client: "06/01/2024, 12:30:36"**

### Current vs. Expected behavior

Current: 
**Warning: Text content did not match. Server: "1/6/2024, 12:30:36 PM" Client: "06/01/2024, 12:30:36"**

expected:

Same output. 
This is not the case, where server has a different time, and client has different one. 
This is about different formatting.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020
Binaries:
  Node: 20.8.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

**Comment by michael-harvey** [comment]
This article answers this situation perfectly - https://www.bugpilot.io/guides/en/how-to-fix-text-content-mismatch-errors-nextjs-0a2e#2-use-of-non-deterministic-javascript

```js
'use client'

import { useState, useEffect } from 'react';

export default function Home() {
  const [date, setDate] = useState('');

  useEffect(() => {
    setDate(new Date(1704526638000).toLocaleString("default"));
  }, []);
  
  return date
}

```

**Comment by vordgi** [comment]
But everything is logical here!

You have `'use client'`, which means that the component is built on the server and then embedded in react dom on the client side _(and if there are any differences, it is re-rendered_).

So, the component was built on the server and this method was executed under the server environment (_apparently en-US_). Then you visit on the client side, React builds the component in the client environment (_let's say en-DE_). That's why different versions are displayed in different environments.

I would suggest fixing the locale and timezone:

```js
const date = new Date(1704526638000).toLocaleString("en-DE", {
    month: "short",
    day: "2-digit",
    year: "numeric",
    minute: "2-digit",
    hour: "2-digit",
    timeZone: 'Australia/Sydney'
  });

```

The risk is that even with completely identical settings, this method may produce different results in different browsers due to implementation differences (*and you will see this error in some browsers, especially in outdated ones*). The most reliable option is not to use this method (*write the solution yourself or use an existing one*).

Alternatively, you can only work with it on the client side, as described in the previous response (*or vice versa, only on the server side if possible*).

**In general, there is no bug in Next.js here!**

**Comment by sandrinjoy** [comment]
@vordgi Thanks for clarifying.
