### ISSUE TITLE
revalidatePath doesn't clear cache for client-side navigation

### ISSUE THREAD

**Issue by jroitgrund** [vercel/next.js#61184]
### Link to the code that reproduces this issue

https://github.com/jroitgrund/nextjs-back-button-bug

### To Reproduce

1. Start the application in production mode (`pnpm build && pnpm start`) and go http://localhost:3001/page to OR go to https://nextjs-back-button-bug.vercel.app/page
1. Refresh the page and note that the displayed number changes
1. Click "clear cache"
1. Click "other page" to navigate away
1. On the other page, click "clear cache" again
1. Use either the back button or the 'back to home' link to come back to the first page.
1. Note that the displayed number doesn't change

### Current vs. Expected behavior

`/page` is a `force-dynamic` page with a server component displaying the current number of seconds. No server caching is happening, as evidenced by the seconds changing after a hard refresh.

The two 'clear cache' links trigger a `DELETE` request to `/api/cache`, which in turn calls `revalidatePath(/page)`.

Because the router cache is manually cleared (see https://nextjs.org/docs/app/building-your-application/caching#invalidation-1), I expected that when navigating back to `/page`:
1. the correct number of seconds would be displayed
2. there would be a network request to fetch the server component payload again

Instead, a stale version of the page was displayed (number of seconds doesn't change and no new network request happens).

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.6.0: Thu Nov  9 00:38:19 PST 2023; root:xnu-8020.240.18.705.10~1/RELEASE_X86_64
Binaries:
  Node: 20.9.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.1.1-canary.12 // Latest available version is detected (14.1.1-canary.12).
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next start (local), Vercel (Deployed), Other (Deployed)

**Comment by redbmk** [comment]
I think `revalidatePath` only works in server components and server actions.

It looks like you're [using a plain `fetch` call](https://github.com/jroitgrund/nextjs-back-button-bug/blob/main/src/components/cache-clear.tsx#L7) rather than a server action. You would need to export an async function in a file that has `"use server"` at the top and then call that instead.

See if this works:

```tsx
"use client";

import { clearCache } from "@/actions/clear-cache";

export default function CacheClear() {
  return (
    <a className="underline cursor-pointer" onClick={clearCache}>
      Clear Cache
    </a>
  );
}
```

**@/actions/clear-cache.ts**
```tsx
"use server";

import { revalidatePath } from "next/cache";

export async function clearCache {
  revalidatePath("/page");
}
```

**Comment by jroitgrund** [comment]
The docs say you can use revalidatePath is route handlers.

https://github.com/jroitgrund/nextjs-back-button-bug/blob/main/src/app/api/cache/route.ts is a route handler.

https://nextjs.org/docs/app/building-your-application/caching#revalidatepath

<img width="671" alt="Screenshot 2024-02-21 at 06 11 44" src="https://github.com/vercel/next.js/assets/1767394/33637d4f-2c11-408e-a134-fd08594a67be">

**Comment by redbmk** [comment]
Hmm, OK but that's related to the server's Data Cache. Since you're using `fetch` from the frontend, I don't think Next has a way to tell the frontend it needs to revalidate its cache.

The [Router Cache](https://nextjs.org/docs/app/building-your-application/caching#router-cache) is the frontend cache, and specifically [this section](https://nextjs.org/docs/app/building-your-application/caching#invalidation-1) mentions that you need to use a server action or `router.refresh` to invalidate it.

The other page you linked to I think is talking about the [Full Route Cache](https://nextjs.org/docs/app/building-your-application/caching#full-route-cache) which is the server-side cache.

**Comment by jroitgrund** [comment]
Looks like I misread, ty ! :)
