### ISSUE TITLE
Not able to load remote pdf in nextjs

### ISSUE THREAD

**Issue by krishnaacharyaa** [vercel/next.js#61288]
### Link to the code that reproduces this issue

https://github.com/krishnaacharyaa/pdf-render-error

### To Reproduce

Just try rendering
<iframe src={"https://www.bseindia.com/bseplus/AnnualReport/532540/68468532540_25_05_21.pdf"}></iframe>

### Current vs. Expected behavior

PDF should have been rendered. But says refuse to connect
<img width="435" alt="image" src="https://github.com/vercel/next.js/assets/116620586/7c881547-1661-46e7-a70b-40d30a8defd3">

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103
Binaries:
  Node: 21.0.0
  npm: 10.2.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Data fetching (gS(S)P, getInitialProps), Image optimization (next/image, next/legacy/image)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I tried changing the next.config.js and allowed the domain, hard luck :(
```
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "bseindia.com",
        port: "",
      },
    ],
    domains: ["www.bseindia.com"],
  },
};

module.exports = nextConfig;```

**Comment by ryozm** [comment]
The error message you're encountering,
```
Refused to frame 'https://www.bseindia.com/' because an ancestor violates the following Content Security Policy directive: 'frame-ancestors 'self'.
```
indicates that the target website https://www.bseindia.com/ has a Content Security Policy (CSP) in place, restricting the framing of its content in iframes.

Specifically, the CSP directive frame-ancestors 'self' in the error message means that only the same origin (same domain, protocol, and port) is allowed to frame the content of the target website.

Since your webpage is attempting to embed content from https://www.bseindia.com/ within an iframe, and this action violates the CSP directive of the target website, the browser refuses to load the iframe and reports the mentioned error.

Solutions:
1. Coordinate with the target website: If you have the appropriate permissions and are legitimately embedding content from the target website, you can contact the administrators of the target website and request to add your webpage to the whitelist in their CSP.
2. Use a backend proxy: Proxy the requests for the target PDF file through your own server and pass the proxy's result to your frontend. This way, the target website won't be directly loaded in the iframe, and the request will be made from your domain, bypassing the CSP restrictions of the target website.
Keep in mind that the second solution requires server-side configuration and handling.

In Next.js, you can resolve the issue by configuring `rewrites` in `next.config.js.`
```ts
// next.config.js
module.exports = {
  async rewrites() {
    return [
      {
        source: '/bseindia/:path*',
        destination: 'https://www.bseindia.com/:path*',
      },
    ]
  },
}
```
page.tsx: `https://www.bseindia.com` => `/bseindia`
```diff
export default function Home() {
  return (
    <iframe
      src={
+        "/bseindia/bseplus/AnnualReport/532540/68468532540_25_05_21.pdf"
-       "https://www.bseindia.com/bseplus/AnnualReport/532540/68468532540_25_05_21.pdf"
      }
    ></iframe>
  );
}
```

**Comment by krishnaacharyaa** [comment]
Thank you @ryozm, it worked :)
