### ISSUE TITLE
Tailwind CSS variables misbehaving on Chromium on client side

### ISSUE THREAD

**Issue by zamachnoi** [vercel/next.js#61693]
### Link to the code that reproduces this issue

https://github.com/zamachnoi/viewthis/tree/css-issue/client

### To Reproduce

1. start server with `bun dev`
2. go to localhost:3000
3. make sure on dark mode (click button in top right)
4. scroll up and down
5. You will see a difference in the colors
![image](https://github.com/vercel/next.js/assets/28397411/ec495df5-f3fb-41b1-ab94-dcebdd0d5e83)

Also viewable with this link: https://viewthis-imlxyug38-zamachnoi.vercel.app/

### Current vs. Expected behavior

Expected behaviour is to have the same background color throughout the screen because I have a tailwind variable setting the background var to an hsl.

Works correctly on firefox 

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:33:31 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8112
Binaries:
  Node: 20.4.0
  npm: 9.8.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.36 // Latest available version is detected (14.1.1-canary.36).
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), Vercel (Deployed)

### Additional context

I tested with canary and the latest regular build. It could just be on my machine, but I dont see it being an issue in chrome? Works on firefox though. Also wasn't happening on windows for some reason. Just on my mac.

Chromium Engine Version 121.0.6167.139

**Comment by davelin18yufan** [comment]
Hey, I cloned your repo and it worked as expected, both on Firefox and Chrome.
You might check the plugin if there is any to interfere the style.
My Chromium version is 121.0.6167.139

**Comment by Durgaprasad-Budhwani** [comment]
@zamachnoi -  I am reproducing this issue on the `client-issue` branch and the root cause of this issue is the dark background

https://github.com/zamachnoi/viewthis/blob/214656aad2cb98f80f1f0a229dabb7fd2cd60832/client/src/app/globals.css#L39

```css
      --background: 222.2 84% 4.9%;    
```

The solution is to change from `84%` to `100%`

----------
"Let's make the digital world smaller! Connect with me across the web on these social platforms and let's create, share, and inspire together." ✨🌐 #StayConnected

[![LinkedIn](https://img.icons8.com/color/48/000000/linkedin.png)](https://www.linkedin.com/in/durgaprasad-budhwani/) [![Twitter](https://img.icons8.com/color/48/000000/twitter.png)](https://twitter.com/DurgaprasadDP)

#### Solved 02

**Comment by zamachnoi** [comment]
@Durgaprasad-Budhwani - Thanks for looking into it! That is the background that I want! That is the background showing up at the but, but the other background at the bottom is something else.

@davelin18yufan Thanks for looking into it as well!
Seems like this is a Chromium issue and not anything the Next team can fix!

https://github.com/tailwindlabs/tailwindcss/discussions/12361
https://issues.chromium.org/issues/40076254

Thanks everyone :D
