### ISSUE TITLE
HMR Not Working

### ISSUE THREAD

**Issue by regisrex** [vercel/next.js#61775]
### Link to the code that reproduces this issue

https://github.com/regisrex/next14-issues-repro

### To Reproduce

1. Start the application in dev mode
2. try to change something in either `apps/web` or `apps/dashboard`

### Current vs. Expected behavior

Nothing changes in the browser and there's this error log in the  browser console
![image](https://github.com/vercel/next.js/assets/94565752/9c0692a1-e07b-4d18-a201-8c55ff32b7d3)

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.42 // Latest available version is detected (14.1.1-canary.42).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by ztanner** [comment]
Hi @regisrex, can you clarify what your app is doing? Upon installing it and running it, and visiting localhost:3000, I see that it's making a fetch call to another app that doesn't have the endpoint that's being called, and it's also using the wrong port (5000 rather than 4000). So I'm immediately hit with fetch errors. 

If I remove that fetch call, the app & HMR seems to be working as expected

**Comment by regisrex** [comment]
Here's a new repro: https://github.com/regisrex/next-14-issues-repro2 .
Sorry about the other one

**Comment by regisrex** [comment]
And you can check steps on how to reproduce in the readme

**Comment by ztanner** [comment]
@regisrex please ensure that your root `layout.tsx` contains a `<body>` tag. Currently it just has a `main` tag. `body` is required per https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#root-layout-required.

**Comment by regisrex** [comment]
Adding the `body` in the root layour solved it thanks @ztanner 🙏🏿.
But another problem came.

Hitting `/p/analytics` turns out to be not found when I refresh the page. It only works well when I pass through `/p`  and click on a link to `/p/analytics`.

check the images 👇🏿 

![image](https://github.com/vercel/next.js/assets/94565752/74538b33-d913-42e7-8696-916b63ad386f) |
![image](https://github.com/vercel/next.js/assets/94565752/82b1c0dd-2e5f-4e6f-8c62-d24a04ab1629) |

**Comment by ztanner** [comment]
This is happening because your parallel slots (`@headerBar` and `@navbar`) don't contain `default.tsx` files. When navigating to a route that uses parallel routes but has no match for the sub-path you're on, the current behavior is to 404. In other words, `/p/analytics` 404s because there's no `@headerBar/p/page.js` nor `@headerBar/default.js`. You can read more about this behavior here: https://nextjs.org/docs/app/api-reference/file-conventions/default

I'm going to close this issue as it seems like there isn't a bug here. Feel free to post in [Discussions](https://github.com/vercel/next.js/discussions) in case you have any follow-up questions about these features!

**Comment by regisrex** [comment]
Thanks for your help @ztanner
