### ISSUE TITLE
Requests to `/%` result in 400 HTTP response or the server failing

### ISSUE THREAD

**Issue by MarwanAlsoltany** [vercel/next.js#62775]

**Comment by terrymun** [comment]
Only if you bothered to google for it: a `%` character not followed by a hex code is considered a malformed URL and therefore a 400 response is appropriate: https://superuser.com/questions/759959/why-does-the-percent-sign-in-a-url-cause-an-http-400-bad-request-error

This is by design and not a Nextjs bug.
