### ISSUE TITLE
Dynamic Routes with generated segment values containing characters that need to be URI encoded return 404 in dev

### ISSUE THREAD

**Issue by wesnolte** [vercel/next.js#63002]
### Link to the code that reproduces this issue

https://github.com/wesnolte/nextjs-dynamic-param-bug

### To Reproduce

1. Start the application in dev mode
2. Attempt to navigate to http://localhost:3000/sticks%20%26%20stones or http://localhost:3000/sticks & stones
3. Note 404 error is return

If you instead build the app and start it e.g. yarn run start, there is no error. This is a blocking issue during dev.

### Current vs. Expected behavior

Current:

In dev 404 errors are returned for dynamic routes that contain characters that should be URI encoded in the path. You can work around this by URI encoding the path in generateStaticParams, but doing so will break your build in production i.e. prod and dev have different behaviours.

Expected:

The dev environment should work the same way as the prod environment i.e. either both need you to encode params in generateStaticParams, or neither need you to.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Thu Oct 5 21:02:42 UTC 2023
  Available memory (MB): 15955
  Available CPU cores: 20
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 14.2.0-canary.6 // Latest available version is detected (14.2.0-canary.6).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

**Comment by devjiwonchoi** [comment]
Hi, I spent a decent amount of time investigating this, and I am sorry to inform you that I couldn't find a feasible solution.

### Cause of the Error 

I assume this issue is because `generateStaticParams` is triggered on demand on the dev server, the URL is already starting to be loaded before building the static paths.

> During `next dev`, generateStaticParams will be called when you navigate to a route.

#### Under the Hood

1. input path as `/sticks & stones` to the browser
2. path encoded by the browser as `/sticks%20&%20stones`
3. `generateStaticParams` triggered, set param as `/sticks & stones`
4. the two paths do not match, trigger `not found`

On the other hand, the production servers are running on the build output, which is already the `sticks & stones.html`, and the route has been built.

I suspect this is why it is not thrown on the production server.

### Possible Fix

We could modify `generateStaticParams` to encode slug paths, but the additional operation per slug and its edge cases isn't worth the benefit, since this issue is not critical for production.

### Workaround

For a workaround but a pretty reasonable approach, I suggest you:

```tsx
export const dynamicParams = process.env.NODE_ENV === 'production'
```

This won't break either your production nor development.

### Reference

- [generateStaticParams](https://nextjs.org/docs/app/api-reference/functions/generate-static-params)

**Comment by wesnolte** [comment]
Thanks for the workaround. It isn't a production issue, but is an issue on the path to production. So any developer unaware of the workaround will wonder why code that works elsewhere doesn't work with particular dynamic routes. They'll have to debug to uncover the issue, then figure out how to work around it until they deploy. When they deploy - depending on the workaround - they'll might realise their code is broken outside of dev e.g. if they decode the param in `generateStaticParams` to get it to work in dev.

**Comment by siraisisatoru** [comment]
In my use case, I try to create a file-based site where I can pass the content within the markdown file for some operations. I ran into this exact case last night and have a similar observation that @devjiwonchoi mentioned in `under the hood` part.
Based on my understanding, `export const dynamicParams = process.env.NODE_ENV === 'production'` does not affect the URL decode/encoding but rather routing. For example, a non-existing URL in production will now return code 500 if this workaround is used. In my case, I think implementing `generateStaticParams` changes would be more effective in this instance.

Here is the working example I am using which inspired by the workaround.
```tsx
// app/[...slug]/page.tsx
export async function generateStaticParams(): Promise<Params[]> {
    const postsDirectory = path.join(process.cwd(), "Notes");
    const fileNames = fs.readdirSync(postsDirectory, { recursive: true });
    const paths = fileNames
        .filter((fileName) => fileName.toString().endsWith(".md")) // Filter only markdown files
        .map((fileName) => {
            // Construct slug from file path
            const slug = fileName
                .toString()
                .replace(/\.md$/, "") // Remove file extension
                .split(path.sep) // Split path by separator
                .filter(Boolean)
                .map((segment) => {
                    if (process.env.NODE_ENV === "production") {
                        return segment;
                    } else {
                        return encodeURIComponent(segment);
                    }
                });
            return { slug };
        });
    return paths;
}
export const dynamicParams = false;
``` 

This technically working in my case but I would like to know whether this will cause other problems (in terms of performance).

**Comment by winstonyin** [comment]
I'd like to bump this, since it is an obstacle on the way to production, as @wesnolte pointed out. I'm developing a blog-like static website that compiles and renders text files, using their file names (often with spaces) as the page slug. If routing works in dev but not in build (or vice versa), that seems to me like a serious flaw of the dev mode. This caused me to add/remove URI escape code multiple times in multiple places throughout the website before I found out about this issue. I suspect this experience is not uncommon.

If this issue is not resolved, I believe there should at least be a known issue written down in the docs somewhere to guide developers.

**Comment by stefanprobst** [comment]
another repro: https://github.com/stefanprobst/issue-next-uri-encoded-path-segments/blob/main/app/tests/%5Bid%5D/page.tsx

current workaround is rather annoying (because i always forget):

```ts
export async function generateStaticParams() {
  const ids = []

  return ids.map((id) => {
    /** @see https://github.com/vercel/next.js/issues/63002 */
      return { id: process.env.NODE_ENV === "production" ? id : encodeURIComponent(id) };
    });
}
```

@samcx is somebody already looking into this issue? or do you have any pointers where to start digging? thanks!

**Comment by samcx** [comment]
@stefanprobst I can definitely still replicate this in development.

We will be taking a look!

**Comment by samcx** [comment]
@wesnolte @stefanprobst a fix incoming!

**Comment by stefanprobst** [comment]
@samcx thanks for fixing this!

**Comment by wesnolte** [comment]
@samcx thank you!
