### ISSUE TITLE
next/link leads to a cached page

### ISSUE THREAD

**Issue by One041** [vercel/next.js#63898]
### Link to the code that reproduces this issue

https://github.com/One041/next_demo

### To Reproduce

1. Start the app in development mode (next dev).
2. Open the home page in your browser (http://localhost:3000/)
3. Check the random number on the page.
4. Click the "Go to some page" button
5. When second page loaded click "Go to home page" button
6. Check again the random number on the page

### Current vs. Expected behavior

Current behavior: the random number is the same
Expected behavior: the random number should change because this is SSR page

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.18.2
  npm: N/A
  Yarn: N/A
  pnpm: 8.15.3
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

### Additional context

There is deployed demo app: https://next-demo-pi-three.vercel.app/

**Comment by ztanner** [comment]
Hi, this is expected behavior, and you can learn a bit more about it in the [Router Cache docs](https://nextjs.org/docs/app/building-your-application/caching#router-cache).

The router will cache the RSC data for your route for 30s. We're currently working on an experimental flag that will let you disable this feature which we hope to land soon. 

Keep an eye on https://github.com/vercel/next.js/pull/62856 which will soon let you specify how long the router cache will consider this data "reusable" for (a value of 0 would re-fetch the data every navigation).
