### ISSUE TITLE
server action redirect() with parallel/intercepting routes not work

### ISSUE THREAD

**Issue by NavOrange** [vercel/next.js#64433]
### Link to the code that reproduces this issue

https://github.com/NavOrange/redirect-in-server-action-with-parallel-intercepting-routes.git

### To Reproduce

1. clone https://github.com/NavOrange/redirect-in-server-action-with-parallel-intercepting-routes.git
2. pnpm install && pnpm dev
3. click form link
4. click dialog submit

### Current vs. Expected behavior

Current: since 14.2 server action redirect not work, route not change
Expected behavior: redirect work, dialog close

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64
  Available memory (MB): 16384
  Available CPU cores: 12
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: N/A
  pnpm: 8.15.6
Relevant Packages:
  next: 14.2.1 // Latest available version is detected (14.2.1).
  eslint-config-next: 14.2.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

**Comment by ztanner** [comment]
Hi @NavOrange! Thank you for the report.

I took a look at the provided reproduction, and I believe the behavior you're seeing is because your `@form` slot doesn't have a root level Page component (ie `@form/page.tsx`). 

When you first load the `/` page, since there's no `@form/page.tsx` file, it uses `@form/default.tsx` instead. However, on a soft-navigation (such as when using `redirect(...)` or clicking a `<Link />`), the router's behavior is to try and match a Page component on the requested URL. If it can't find one, it will keep around whatever was previously rendered. We fixed a fair number of parallel routes bugs in 14.2, so it's quite possible the behavior was incorrectly working previously.

Here's a video where I took your reproduction and added a `@form/page.tsx` component that just renders `null`:

https://github.com/vercel/next.js/assets/1939140/ecc223bd-8653-4706-b98c-53214175f184

More about this behavior can be found [here](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#active-state-and-navigation).

Please let me know if you're not able to get this to work and I can re-open this issue. Thank you!
