### ISSUE TITLE
NextJS production and dev builds take >20 minutes

### ISSUE THREAD

**Issue by imprakharshukla** [vercel/next.js#64899]
### Link to the code that reproduces this issue

https://codesandbox.io/p/github/imprakharshukla/rapid/csb-kyjsmz/draft/heuristic-newton

### To Reproduce

1. Install the packages with `pnpm install`
2. Start the production build with `pnpm build --filter demo`

### Current vs. Expected behavior

The build runs for over 25 minutes (local and on Vercel).

It should not take that long.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.11.0
  npm: 8.19.2
  Yarn: 1.22.17
  pnpm: 8.5.1
Relevant Packages:
  next: 14.2.2 // Latest available version is detected (14.2.2).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

### Additional context

I am currently using `ver. 14.1.1` but `ver. 14.2` makes no difference.
This is also not limited to this project as well. It is the same for another project I am working on.

I suspect a pnpm internal package to do this but I cannot access the build logs and since `--debug` does not display anything. I am at my wits end.

**Comment by gokul-afk** [comment]
Unable to access this workspace
It is likely that you are not a member of the team that this project belongs to. To be able to access the web editor of this repository and edit the code, you need to be invited to the team.

**Comment by imprakharshukla** [comment]
@gokul-afk Weird, the devbox is public. I tried using stackblitz and replit but there's some or the other error.

You can try cloning the repo and running the install and build commands or a codespace.

**Comment by timneutkens** [comment]
The linked reproduction does not run indeed. Was able to find https://github.com/imprakharshukla/rapid, is that the same?

**Comment by imprakharshukla** [comment]
@timneutkens yes, it is the same!

**Comment by imprakharshukla** [comment]
Here's the webpack-analyzer report:
https://coffee-drucie-88.tiiny.site/

**Comment by timneutkens** [comment]
Checked the reproduction and found the reason it's so slow is not related to Next.js, it's related to the Tailwind configuration used. In particular you added `"../../packages/ui/**/*.{js,ts,jsx,tsx}"` which means "anything in `packages/ui` *including node_modules* so Tailwind is scanning all node_modules, in your case that means tens of thousands of files as `node_modules` in `packages/ui` includes e.g. lucide-react, next.js, typescript and many more dependencies.
If you change it to e.g. `"../../packages/ui/src/**/*.{js,ts,jsx,tsx}"` the issue is solved (keep in mind you currently still have a `index.ts` file in the `packages/ui` directory root as well, that wouldn't be caught.
