### ISSUE TITLE
PPR (Partial Prerendering) renders page twice in prod mode

### ISSUE THREAD

**Issue by sedlukha** [vercel/next.js#65368]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/beautiful-forest-53svph?file=%2Fnext.config.js%3A4%2C15

### To Reproduce

1 - build
2 - start
3 - open any page (`/test` for example)

### Current vs. Expected behavior

The whole page renders twice when `ppr` is enabled, and once when it's disabled. It is expected that the page will be rendered only once.

By the way, in dev mode (`next dev`), the page renders only once.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.3.0-canary.38 // Latest available version is detected (14.3.0-canary.38).
  eslint-config-next: 14.3.0-canary.38
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Partial Prerendering (PPR)

### Which stage(s) are affected? (Select all that apply)

next build (local), next start (local)

**Comment by wyattjoh** [comment]
This appears to be rendering twice because we perform two renders when a page is being statically generated.

In your example, the code only renders once when PPR is disabled because without a `generateStaticParams` export from the page, we actually interpret the page as dynamic, and therefore, don't generate the flight data for client navigations as we do during static generation.
