### ISSUE TITLE
Router cache does not revalidate

### ISSUE THREAD

**Issue by Saman-Safaei-Dev** [vercel/next.js#66118]
### Link to the code that reproduces this issue

https://github.com/Saman-Safaei-Dev/router-cache-bug

### To Reproduce

1- Start the development server and open the web app.
2- Navigate to the dashboard or any random page to be redirected to the sign-in page (use the link provided on the home page).
3- Sign in to the website to set a cookie.
4- Close the browser and reopen the web page.
5- Click on the link you previously clicked to observe the bug.

### Current vs. Expected behavior

I expect to dashboard get opened but nothing happens. router cache not revalidated on cookies().set and I redirected to signin page and then redirected to home. ( redirect chain )

### Provide environment information

```bash
Operating System:
  Platform: Windows 11
  Arch: x64
  Version: 23H2
Binaries:
  Node: 18.20.2
  npm: 10.5.0
Relevant Packages:
  next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.3
```

### Which area(s) are affected? (Select all that apply)

Middleware, Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

**Comment by icyJoseph** [comment]
Is the issue here that you redirect with a 301? I haven't had time to run your app, but here:

```ts
    if (isProtectedRoute && !isException) {
      const newUrl = new URL(`/auth/signin?path=${pathname}`, request.url);
      return NextResponse.redirect(newUrl, { status: 301 });
    }
```

If you have an unauthenticated user, and the route is protected, and not an excepted route, then you do a 301 to signin, and the browser saves those. Could you try using 302 instead? First clear your browser cache though, since those 301's are saved by it. https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache

**Comment by Saman-Safaei-Dev** [comment]
The issue is resolved with this solution. I thought it's a bug. Thanks for your solution.

**Comment by icyJoseph** [comment]
Nice, could you close the issue then? :)
