### ISSUE TITLE
Docs: Versioned Documentation

### ISSUE THREAD

**Issue by sos0** [vercel/next.js#66357]
### What is the update you wish to see?

Since Next.js is constantly being updated at breakneck speed, it'd be immensely helpful for developers if we had "versioned documentation". For example, documentation corresponding to Next 12, Next 13, Next 14, and Next 15 can be separately made available for developers, alongside recommendations to upgrade to certain versions, just as the Pages Router documentation includes a recommendation to migrate to the App Router.

### Is there any context that might help us understand?

Considering not all developers choose to migrate to latest/newest versions of Next.js, "versioned documentation" would be the ideal source of information relevant to each developer. A developer utilizing a lower versioned product can no longer rely on the current documentation since the current documentation may contain new features incompatible with old versions.

**Comment by delbaoliveira** [comment]
Hey @sos0 👋🏼 I maintain the Next.js docs, versioning is something I'd like to have as well. 

Historically, I've prioritized writing content because there were so many new _breakneck speed_ App Router features to document. But as APIs in the App Router evolve, we need a way to make it clearer which features are experimental, stable, or not available in x version, etc. 

Versioning could solve many of these problems, but I don't have a clear, sustainable long-term implementation yet. Especially when it comes to the maintenance burden / accuracy of older versions - something that's hard to control with open-source docs. 

But tldr, it's cooking 😊
