### ISSUE TITLE
Nested parallel routes slot rendered after navigating back

### ISSUE THREAD

**Issue by jer-k** [vercel/next.js#66502]
### Link to the code that reproduces this issue

https://github.com/jer-k/graphql-rsc-dashboard

### To Reproduce

Same issue as https://github.com/vercel/next.js/issues/60541 but that is closed and can't be commented on anymore. Tagging @ztanner as I hope this reproduction helps https://github.com/vercel/next.js/issues/60541#issuecomment-2077604839

I came across the above issue as I was searching around to try to understand why the slot isn't falling back to the default on subsequent navigation.

In my repository above 

* Start on the home page (`/`)
  * You will see in the logs `rendering in default { params: {}, searchParams: {} }` from [default.tsx#4](https://github.com/jer-k/graphql-rsc-dashboard/blob/4f2c5760b430105309529e3456f8ad97ba8b2ae7/app/%40breadcrumbs/default.tsx#L4)
* Click the `RSC (No Delay)` button in the header to navigate to `/books`
  *  You will see in the logs `rendering in @breadcrumbs / BreadcrumbSlot [ 'books' ]` from [page.tsx#11](https://github.com/jer-k/graphql-rsc-dashboard/blob/4f2c5760b430105309529e3456f8ad97ba8b2ae7/app/%40breadcrumbs/%5B...catchAll%5D/page.tsx#L11)
* Click `Home` in the header
  * No log from either the `default.tsx` or `page.tsx` shows up. The breadcrumbs still show `Home | books` instead of just `Home`.  

### Current vs. Expected behavior

* Current: Navigation to a page that does not match a path in the slot does not revert back to the default
* Expected: Navigation to a page that does not match path in the slot reverts back to the default

### Provide environment information

```bash
npx --no-install next info

Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64
  Available memory (MB): 16384
  Available CPU cores: 12
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 9.0.6
Relevant Packages:
  next: 15.0.0-rc.0 // Latest available version is detected (15.0.0-rc.0).
  eslint-config-next: 14.2.3
  react: 19.0.0-rc-6f23540c7d-20240528
  react-dom: 19.0.0-rc-6f23540c7d-20240528
  typescript: 5.4.5
Next.js Config:
  output: N/A
```
```


### Which area(s) are affected? (Select all that apply)

Parallel & Intercepting Routes

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

_No response_

**Comment by ztanner** [comment]
Hi @jer-k -- this is expected behavior with catch-all routes.

A catch-all route will match all routes except for the "index" route that it's defined in. Meaning /foo, /bar, /foo/bar, ...etc, but not /.

With parallel routes, during a soft navigation (ie when clicking a Link) the router will attempt to match the page to a corresponding parallel route. If one doesn't exist, it'll keep whatever was previously in that slot, until you refresh the page. You can learn about that behavior [here](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#active-state-and-navigation).

For your use-case, since you want the index route to render the same component as your catch-all component, you could add a `@breadcrumbs/page.tsx` that simply does:

```
export { default } from "./default";
```

(Or it could be the catch-all component if you prefer -- either one).

We have a task to support _optional_ catch-all routes (ie `[[...catchAll]]`) which also matches the index. That issue is being tracked here: https://github.com/vercel/next.js/issues/61206

**Comment by jer-k** [comment]
Awesome, thank you for the info!
