### ISSUE TITLE
Modal by parallel routing on slow connection not working. Clicking on Link before hydration causes full reload instead of showing modal

### ISSUE THREAD

**Issue by a-k-kord** [vercel/next.js#66524]
### Link to the code that reproduces this issue

https://github.com/a-k-kord/nextgram-with-img

### To Reproduce

1. Start local: bun run dev
2. Enable Slow 3G Throttling
3. reload page
4. while scripts are loading click on any image
5. the new page with image url will be loaded instead of modal window
6. go back and wait until full hydration
7. click on any image again
8. modal is shown as expected 

Demo
https://github.com/vercel/next.js/assets/76525701/86e0e208-8e18-4b0c-bb35-31890668b9f4

### Current vs. Expected behavior

Modal made by parallel routing on slow connection is misleading. 
The Link without full hydration is acting like tag \<a href="/photos/[id]"> that leads to new url with full page reload.
Which means that either making a modal with parallel routing is a bad idea 
or 
Link behaviour without hydration has to ignore clicks
  

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #117~20.04.1-Ubuntu SMP Tue Apr 30 10:35:57 UTC 2024
  Available memory (MB): 31710
  Available CPU cores: 8
Binaries:
  Node: 20.13.1
  npm: 10.5.2
  Yarn: 1.22.22
  pnpm: 9.1.2
Relevant Packages:
  next: 15.0.0-rc.0 // Latest available version is detected (15.0.0-rc.0).
  eslint-config-next: N/A
  react: 19.0.0-rc-f994737d14-20240522
  react-dom: 19.0.0-rc-f994737d14-20240522
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Parallel & Intercepting Routes

### Which stage(s) are affected? (Select all that apply)

next dev (local), Vercel (Deployed)

### Additional context

Tested against 
14.0.5-canary.65
14.2.3-stable
15.0.0-rc.0

**Comment by ztanner** [comment]
Hi @a-k-kord --

As you noted, custom Link interactivity relies on JavaScript, which means React has to hydrate first. This means that even a regular Link click will trigger an MPA navigation until hydration occurs. 

> Which means that either making a modal with parallel routing is a bad idea

I'm not sure I necessarily agree with this, since I suspect that being able to click the link and view the final page data is better than clicking the link and nothing happening.  But nonetheless, this is still something you can control in your app.

One example of a way to deal with this is to disable SSR on the cards so that it waits for hydration, and specify a `Loading` component to use in the meantime. Under the hood, this makes use of `React.lazy` and `Suspense` to render a fallback UI until hydration. eg:

```tsx
const LazyCardWithLink = dynamic(() => import("../CardWithLink"), {
  ssr: false,
  loading() {
    const id = React.useContext(CardIdContext);

    return (
      <Image
        width={200}
        height={200}
        src={`https://picsum.photos/id/${value}/200/300`}
        alt="alt"
        className="rounded-lg shadow-lg"
        priority
      />
    );
  },
});
```

This would render the `Image` and after hydration, it'll swap to `CardWithLink` which is essentially the image wrapped in a Link. But you could also choose to render a more generic fallback instead.
