### ISSUE TITLE
Partial Prerendering does a full fetch of the whole page on every page view? 

### ISSUE THREAD

**Issue by Ventanas95Dev** [vercel/next.js#66697]
### Link to the code that reproduces this issue

https://github.com/Ventanas95Dev/next-partial-prerendering

### To Reproduce

Build the project on vercel. 

Then open the website in the browser and you will se the date update on every refresh. 

I just added a fetch request to the worldtimeapi to fetch the current date. 
![Screenshot 2024-06-10 at 10 48 56](https://github.com/vercel/next.js/assets/98022026/da73aedd-8ee1-4cca-b6c0-ad7926dfd063)

![Screenshot 2024-06-10 at 10 49 36](https://github.com/vercel/next.js/assets/98022026/28b18c21-b703-4b9e-ba8a-0c4e1a23101e)

Demo here: https://next-partial-prerendering-swart.vercel.app/

### Current vs. Expected behavior

Current : I first se the cached/static html result. But then it gets updated with the new date current date.

 Expected: The date should be cached in the static html and not update on every request.
 
 

### Provide environment information

```bash
"next": "15.0.0-rc.0",
"react": "19.0.0-rc-cc1ec60d0d-20240607",
"react-dom": "19.0.0-rc-cc1ec60d0d-20240607"

Deploy to Vercel with node 20
```

### Which area(s) are affected? (Select all that apply)

Partial Prerendering (PPR), Runtime

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

### Additional context

Deployed to vercel. 

I first tried with 15.0.0-rc.0 and then 15.0.0-canary.21. Same behaviour on both.

It feels a little weird that all calls on the page are rerun and not just those within a supspene? or is this how PPR should work? I know it is possible to cache the calls, but our caches are so large that it becomes expensive to use Next.js data cache as they calculate that a call is 8kb and our fetches are around 1.5mb. It quickly becomes quite a lot.

**Comment by wyattjoh** [comment]
This is actually working as intended. Partial prerendering, explained briefly, is really all about a two pass render. The first pass creates a static shell, which includes all the HTML that can be generated statically before any dynamic API's are used. The second pass, still starts the render from the root, where every component is rendered again. This is why the date changes after the hydration.

Instead of caching the entire fetch call, instead, you can cache the computed result using the `unstable_cache` API instead. This gives you more flexibility so that an expensive (1.5mb for example) fetch call where you only need a small property off of it (5b for example) will only be stored in the cache.
