### ISSUE TITLE
Docs: "Edit this Page on Github" Button links to nonexistent paths on some pages

### ISSUE THREAD

**Issue by LorisSigrist** [vercel/next.js#66756]
### What is the update you wish to see?

On some pages the `Edit this page on Github` Button links to markdown files that do not exist; Not on the `canary` or the `main` branch. 

### Is there any context that might help us understand?

Pages where I observed this:
- https://nextjs.org/docs/app/building-your-application/routing/middleware
- https://nextjs.org/docs/app/building-your-application/routing/route-handlers
- https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating

**Comment by delbaoliveira** [comment]
Hey @LorisSigrist, thank you for catching this! The issue is because the docs in the repo are the latest (canary) and the ones in the Next.js site are the latest **stable** version 14.2.3 (see https://rc.nextjs.org/docs for 15 RC docs). We recently updated some paths that are not reflected on the site. But no worries, it's an easy fix, should be landing soon! 

Worth noting that v14.2.3 is attached to a tag. Github doesn't allow you to edit tags on the site. So if you want to edit the page, you'll need to fork repo, checkout and create a branch from the tag.

**Comment by LorisSigrist** [comment]
Thanks for the explanation that makes a lot of sense 🙏
