### ISSUE TITLE
ReferenceError: HTMLElement is not defined when running in dev

### ISSUE THREAD

**Issue by zZHorizonZz** [vercel/next.js#70502]
### Link to the code that reproduces this issue

https://github.com/zZHorizonZz/nextjs-bug-01

### To Reproduce

1. Start the application using `npm run dev`
2. Go to the application URL
3. After the page is rendered see the error in the console it should say ReferenceError: HTMLElement is not defined

### Current vs. Expected behavior

Currently, when using web components (I'm for example using material-web) in Next.js, it results in a ReferenceError: HTMLElement is not defined error when running in development mode. However, when building and running the production application, this error does not occur (or is ignored and not shown in default application log?). This issue occurs even if you put 'use client' on top of the page.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Enterprise
  Available memory (MB): 32394
  Available CPU cores: 8
Binaries:
  Node: 18.20.4
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.13 // Latest available version is detected (14.2.13).
  eslint-config-next: 14.2.13
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience, Runtime, Testing, Webpack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I have tested against multiple stable and canary versions and the error occurs in all of them.

**Comment by icyJoseph** [comment]
`use client` doesn't mean the component runs only client side, it means that the JS will be shipped to the client.

However, these components are also SSR'd, https://github.com/reactwg/server-components/discussions/4, and that means that if the component doesn't account for also running server side, errors will happen, such as the one you are seeing. 

See this similar resolved discussion: https://github.com/vercel/next.js/discussions/68779#discussioncomment-10311996

 My guess here is that SSR hasn't been a priority of this framework, or that, some components don't support SSR. You might have to opt-in to dynamic/lazy loading of these.

I'll however, try to take a look at your repository. Build time is probably erroring, and then the runtime opts-in to CSR, because of the server error.

**Comment by zZHorizonZz** [comment]
Corrected grammar:

So the library I'm using is just a wrapper for [Material Web Components](https://github.com/material-components/material-web), which uses [Lit](https://github.com/lit/lit/). Lit has support for SSR if you add the '@lit-labs/nextjs' library and include it in your Next.js configuration: 

```javascript
// next.config.js
const withLitSSR = require('@lit-labs/nextjs')();

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Add your own config here
  reactStrictMode: true,
  swcMinify: true,
};

module.exports = withLitSSR(nextConfig);
```

It should work because there's a 'use client' on top of each of these components in the wrapper library, as required by the Next.js Lit plugin. So if you don't think there's anything wrong in Next itself, I'll go ask the Lit team if they have any insights.

**Comment by icyJoseph** [comment]
> It should work because there's a 'use client' on top of each of these components

The 'use client' directive only means that this JavaScript is bundled for the client. It doesn't prevent this component from being SSR'd.

I went to lit's and found this issue, https://github.com/lit/lit/issues/4771 - perhaps that's it?

**Comment by zZHorizonZz** [comment]
> I went to lit's and found this issue,  - perhaps that's it?

Maybe that's it. I wonder if that's a new thing or not because it's weird that I wouldn't have noticed it until now. Thanks for the help.
