### ISSUE TITLE
`NEXT_REDIRECT` internal error making it to the client

### ISSUE THREAD

**Issue by kevinmitch14** [vercel/next.js#71831]
### Link to the code that reproduces this issue

https://github.com/kevinmitch14/redirects2

### To Reproduce

Start application
Click buttons
Observe Network tab

### Current vs. Expected behavior

With new changes introduced in https://github.com/vercel/next.js/pull/69945, it seems that the internal `NEXT_REDIRECT` error will now leak into client code, where before it did not. 

So basically with an action using `redirect()`, a `NEXT_REDIRECT` error will be thrown, to let next.js know that a redirect needs to happen. This will be handled, doing the redirect, and then the error will also now leak to the client code as of v15.0.0-canary.160. Even when this `NEXT_REDIRECT` error is caught in the try/catch block, the redirect will still have already been handled. So I don't really see the purpose of this internal error reaching the client in the first place.

I was told to use `unstable_rethrow()` to "fix" this issue. So basically to rethrow the internal error that made it to client code, but the problem is, next.js already handled the redirect, and this error is serving no purpose on the client (i think).

But anyway, I tried to use `unstable_rethrow()` and this results in 2 requests being made in the redirect process. The intended redirect process and then when `unstable_rethrow()` rethrows the error, it is causing another network request to fetch the RSC payload (which has already been fetched and rendered)

> From https://github.com/vercel/next.js/pull/69945 - This allows the redirect to be handled in a single request rather than requiring a second request to fetch the RSC payload on the URL being redirected to.

So what happens is AFAICT:
1. Invoke server action
2. Server action redirects
3. In the UI is redirected
4. The `NEXT_REDIRECT` error is caught in the catch block and rethrown
5. The payload for the redirect destination is requested again

Whereas, if the `NEXT_REDIRECT` is simply swallowed on the client, only one request will be fired.

```tsx
<form
  onSubmit={async (e) => {
    try {
      e.preventDefault();
      await action();
    } catch (error) {
      unstable_rethrow(error);
    }
  }}
>
  <button>Click me</button>
</form>
```
**Swallowed Error**
<img width="600" alt="Screenshot 2024-10-24 at 17 41 56" src="https://github.com/user-attachments/assets/9b3d95a7-27c2-425f-8322-2e77c8078fc9">

**Using unstable_rethrow**
<img width="600" alt="Screenshot 2024-10-24 at 17 40 44" src="https://github.com/user-attachments/assets/efba04e3-0742-47d9-bd54-c9126243b723">

It looks like the commit that caused this regression is aiming at fixing issues with `useActionState`, but the reality is, this is a very new, not mature API. And many will not be touching it. Many are using for libraries such as react-hook-form, where onSubmit is used as opposed to the action prop.

Here is another example: Here, this success toast will never fire, actually the error toast will fire. Previously, the success toast would fire, along with the redirect. And error toast would only fire when an error is thrown in the action (not internal errors)

```tsx
<form
  onSubmit={async (e) => {
    try {
      e.preventDefault();
      await action();
      toast("Success")
    } catch (error) {
      toast("Error")
      console.log(error);
    }
  }}
>
  <button className="bg-blue-200">
    Click me to try swallowed redirect error 1 request
  </button>
</form>
```
Previous issue that was closed pretty quickly... https://github.com/vercel/next.js/issues/71740

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 22.8.0
  npm: 10.8.2
  Yarn: 1.22.19
  pnpm: 8.15.1
Relevant Packages:
  next: 15.0.2-canary.5 // Latest available version is detected (15.0.2-canary.5).
  eslint-config-next: 15.0.1
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation, Runtime

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

**Comment by rodeyseijkens** [comment]
I'm running into the exact issue like the one described with the toaster.
I needed to roll back to next 14 for the specific case.

**Comment by rodeyseijkens** [comment]
To describe it a bit more into detail is that I have a try catch also, but I don't have a success toaster of course because there is when the redirect happens. I have an addItemAction.
And that has two scenarios on success it will redirect the user to the overview page.
But on a error I want it to just show the error message to the user with a toast.
The problem is that because its in a try catch the redirect no longer happening.

```tsx
<form
  onSubmit={async (e) => {
    try {
      e.preventDefault();
      await addItemAction();
    } catch (error) {
      toast("Error unable to add item because of reason");
    }
  }}
>
  <button className="bg-blue-200">
    Click me to try swallowed redirect error 1 request
  </button>
</form>
```

**Comment by ztanner** [comment]
Hi @kevinmitch14 (and others!),

Thank you for the report! I've written a lengthy reply below explaining the behavior by walking through Next.js/React internals. If you'd like to just skip to the solution, the following change to your code will have the result you're looking for:

```tsx
import { useTransition } from 'react'

const [isPending, startTransition] = useTransition();
return (
  <form
    onSubmit={async (e) => {
      startTransition(async () => {
        e.preventDefault();

        try {
          await action();
        } catch (err) {
          unstable_rethrow(err);
          // do other stuff for unrelated errors
        }
      });
    }}
  >
    <button className="bg-blue-200">Submit</button>
  </form>
);
```

Now for an explanation of the different behaviors you're observing:

> So basically with an action using redirect(), a NEXT_REDIRECT error will be thrown, to let next.js know that a redirect needs to happen. This will be handled, doing the redirect, and then the error will also now leak to the client code as of v15.0.0-canary.160. Even when this NEXT_REDIRECT error is caught in the try/catch block, the redirect will still have already been handled. So I don't really see the purpose of this internal error reaching the client in the first place.

The server communicates to the client router that it needs to perform the redirect by rejecting the server action promise with a known error. If instead the server handled the redirect, you'd get a "hard"/MPA-style navigation to the destination URL. We throw an error because it needs to be caught by the client in an error boundary to both handle the redirect & remount the React subtree to reset any potential stale state (like was intended with the `useActionState` fix in the PR you linked). 

> I was told to use unstable_rethrow() to "fix" this issue. So basically to rethrow the internal error that made it to client code, but the problem is, next.js already handled the redirect, and this error is serving no purpose on the client (i think).

What's happening here is that the error is happening out-of-band from the React render. With `useActionState`, the form action is automatically wrapped in a React [Transition](https://react.dev/reference/react/useTransition#usetransition). Similarly, Next.js is using `startTransition` in all router events, such as a server action. This is the [canonical way](https://react.dev/reference/react/useTransition#displaying-an-error-to-users-with-error-boundary) of bubbling errors to an error boundary, and as previously described Next.js uses an error boundary to handle the redirect. 

When you catch the internal redirect signal & rethrow it, and it's _not_ caught by our error boundary (because it happened outside of transition), it's going to be handled by our top-level unhandled error listener: if it sees an uncaught internal Next.js navigation error, it'll manually trigger a `router.push` to the target URL.

The reason this leads to another request to the destination page relates to some changes we made in Next 15 to the client router cache. Specifically, for dynamic routes, we no longer cache the React Server Component data for these pages on the client at: every navigation will fetch new data from the server. You can read about this change in our Next 15 blog [here](https://nextjs.org/blog/next-15#client-router-cache-no-longer-caches-page-components-by-default).  

Because the navigation is happening out of band, React is not able to batch the server action & navigation together: they're happening as discrete router events. And because of the caching change above, the navigation event to a dynamic page is going to require fetching new data from the server because the default dynamic staleTime is `0`. 

If you were to modify the client router staletime via the [config](https://nextjs.org/docs/app/api-reference/next-config-js/staleTimes), eg:

```ts
module.exports = {
	experimental: {
		staleTimes: {
			dynamic: 1 
		}
	}
} 
```

You'll see only 1 request, because the delta between when the server action finished and when the navigation occurred falls within that 1 second time period where you've explicitly indicated you'll tolerate stale data.

Similarly, if you were to remove the `await headers()` call in your root layout (which is opting the entire application into [dynamic rendering](https://nextjs.org/docs/app/building-your-application/caching#static-and-dynamic-rendering)), you'd see only a single request with `next start` without making any configuration changes, because the staleTime for static pages is 5 minutes. 

I'm going to close this as I believe it's working as expected. I hope the solution above works for you and the explanation clarifies the behavior better to make an informed decision about how to approach this, but don't hesitate to reply if you have any follow-up questions.
