### ISSUE TITLE
Error: cacheLife() can only be called inside a "use cache" function.

### ISSUE THREAD

**Issue by tomdohnal** [vercel/next.js#71900]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/nostalgic-khorana-klzrhl?file=%2Fapp%2Fpage.tsx%3A11%2C1

### To Reproduce

1. Start the application and preview it

### Current vs. Expected behavior

I expect a blank page to be rendered w/o any errors but an error overlay saying "Error: cacheLife() can only be called inside a "use cache" function." is shown.

The docs show examples of the `cacheLife` function being used at the top level (https://nextjs.org/docs/canary/app/api-reference/directives/use-cache#caching-entire-routes-with-use-cache), not only inside of functions

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 15.0.2-canary.7 // Latest available version is detected (15.0.2-canary.7).
  eslint-config-next: N/A
  react: 19.0.0-rc-1631855f-20241023
  react-dom: 19.0.0-rc-1631855f-20241023
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by delbaoliveira** [comment]
Thank you for raising this @tomdohnal, we've updated it here: https://github.com/vercel/next.js/pull/72081

**Comment by MGSimard** [comment]
Why is this issue being closed when it's still persisting?

<img src="https://i.imgur.com/ndejxaj.png" alt="Image"/>
<img src="https://i.imgur.com/bVWyAK7.png" width=500 alt="Image"/>

<hr/>

**According to the v15.0.3-canary.2 docs, this should be possible.**
https://nextjs.org/docs/canary/app/api-reference/directives/use-cache#use-cache-directive
<img src="https://i.imgur.com/XM6Q53E.png" width=500 alt="Image"/>
<img src="https://i.imgur.com/l4UADva.png" width=500 alt="Image"/>

**Additionally, this example's Page() isn't even defined as a function.**
https://nextjs.org/docs/canary/app/api-reference/directives/use-cache#examples
<img src="https://i.imgur.com/7sJid8m.png" width=500 alt="Image"/>

You people should probably _run_ your snippets, and only insert into docs once proven working. Rather than dumping broken untested code straight into the doc file. This wouldn't even get past the most basic in-editor linting.

<hr/>

Also, in that docs example, Page isn't async, which would throw this error:

<img src="https://i.imgur.com/Cud173m.png" width=500 alt="Image"/>

For anyone questioning the initial test format differing from that one busted docs snippet:
<img src="https://i.imgur.com/KAI9p9i.png" alt="Image"/>

I understand this is Canary, but why push easily demonstrably nonfunctional examples, then pretend/reinforce the idea that they work by proofing them with unchecked & broken code snippets that wouldn't pass even basic in-editor linting? Not only that, but going on to close issues which clearly aren't resolved?

**Comment by samcx** [comment]
@MGSimard The docs take a moment to update once pushed up. The documentation no longer show the incorrect examples.

**Comment by MGSimard** [comment]
> @MGSimard The docs take a moment to update once pushed up. The documentation no longer show the incorrect examples.

You've got your timeline confused. Doc deployments after push don't take 12 hours _(time between closure and my comment)_, nor were the corrected snippets proposed, committed, merged or deployed by the time of my comment while making those observations.

**[Oct 30, 12:22 EDT](https://github.com/vercel/next.js/issues/71900#event-15011867224)**
- Issue is Closed/Completed, commit still hasn't even been reviewed. 
- Related commit does not contain fix for issue, caught by review later.

**[Oct 30, 23:58 EDT](https://github.com/vercel/next.js/issues/71900#issuecomment-2448966752)** _(11hrs 36min later )_
- My comment is sent regarding issue being closed too early, fix not being included and docs still being wrong.
- Commit still does not contain actual snippet fix, not even reviewed yet. Let alone approved, pushed or deployed.

**[Oct 31, 06:17 EDT](https://github.com/vercel/next.js/pull/72081#discussion_r1824211804)** _(6hrs 19min later - 17hrs 55min after closure)_
- Commits are reviewed by user **Molebox**.
- Commits still contained the incorrect example of top-level cacheLife() which this issue referenced, despite being some 18 hours after this issue was incorrectly closed and marked as completed.
- Actual fix is proposed by reviewer.
![image](https://github.com/user-attachments/assets/ec1e288e-bfc2-4acb-9d21-ba08794902ba)

**[Oct 31, 09:53 EDT](https://github.com/vercel/next.js/pull/72081#pullrequestreview-2408050981)** _(3hrs 36min later - 20hrs 31min after closure)_
- Changes are approved.

**[Oct 31, 09:57 EDT](https://github.com/vercel/next.js/pull/72081#event-15036686301)** _(4min later - 20hrs 35min after closure)_
- Changes are merged.

This means that **the issue was closed 18 hours prior to an actual fix being proposed through Molebox's review**. Said review finally introducing docs fix 6 hours 19 minutes **after my comment**. Therefore I reiterate that I was correct in saying it had not been fixed at the time of my comment.

Finally, solution was merged and deployed 20hrs 35min after issue closure. This means it was pushed **10 hours after my comment**. So no, it wasn't a matter of docs taking time to update. My point still stands that this issue was incorrectly closed too early.

Also, two snippets with incorrectly defined Layout & Page function declarations remain, despite emphasizing that very specific thing in my initial comment.

https://nextjs.org/docs/canary/app/api-reference/directives/use-cache#examples
![image](https://github.com/user-attachments/assets/d0ed1183-b2d3-4ab1-b51a-324184768ab0)

Mistakes are normal, but please don't just blatantly lie about easily verifiable information when someone bothers being this thorough in reporting these problems. Preferably stop closing issues earlier than when they are actually resolved as well.

**Comment by samcx** [comment]
@MGSimard Thank you for the clarification and callout! I 100% agree mistakes were made.

> please don't just blatantly lie about easily verifiable information when someone bothers being this thorough in reporting these problems.

Not trying to! There's always a level of trust when you're working with teammates, and we make mistakes. 

> Preferably stop closing issues earlier than when they are actually resolved as well.

Noted! 🫡. There may have been an issue with the build causing the delay in the change. Nevertheless, we'll make sure to verify the changes before closing an issue.
