### ISSUE TITLE
Cache is always stale on startup for dynamic ISR pages

### ISSUE THREAD

**Issue by PeterGardenas** [vercel/next.js#72020]
### Link to the code that reproduces this issue

https://github.com/PeterGardenas/next-dynamic-isr-stale-on-startup

### To Reproduce

1. npm run build
2. Start next on port 3000 & 3001
3. Visit localhost:3000/bar and localhost:3001/bar

### Current vs. Expected behavior

Current behavior:
1. Initial request to /bar shows the same date. For the later of the requests `x-nextjs-cache`  header is  STALE
2. /bar is revalidate
3. When refreshing localhost:3000/bar and localhost:3001/bar will display different dates

Expected:
1. Initial request to /bar shows the same date. For the later of the requests `x-nextjs-cache`  header is  HIT
2. /bar is not modified
3. When refreshing localhost:3000/bar and localhost:3001/bar will display same dates

The expected behavior works when doing the sample example for /foo as it is provided in generateStaticParams

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Enterprise
  Available memory (MB): 32466
  Available CPU cores: 16
Binaries:
  Node: 20.15.0
  npm: N/A
  Yarn: N/A
  pnpm: 8.15.4
Relevant Packages:
  next: 15.0.2-canary.10 // Latest available version is detected (15.0.2-canary.10).
  eslint-config-next: N/A
  react: 19.0.0-rc-02c0e824-20241028
  react-dom: 19.0.0-rc-02c0e824-20241028
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Performance

### Which stage(s) are affected? (Select all that apply)

next build (local), next start (local)

### Additional context

This issue exists in Next 14 as well.
Using a custom cache handler such as [redis-handler](https://github.com/vercel/next.js/tree/canary/examples/cache-handler-redis) resolves the issue of diverging content, the content is still unnecessarily revalidate, causing redundant computation.

A naive debugging attempt indicates that https://github.com/vercel/next.js/blob/97153cc838d24c58c13f583f1d88f21b30a8621a/packages/next/src/server/lib/incremental-cache/index.ts#L223 always return 1 as this.revalidateTimings is not set for isr dynamic routes

**Comment by luckyswd** [comment]
up

**Comment by malmgren** [comment]
Experiencing the same issue

**Comment by dtno-bashar-alqaysi** [comment]
bump

**Comment by sragneau** [comment]
up, same problem

**Comment by ztanner** [comment]
Hi,

As described in the ISR docs, when running `next start` locally, the cache is persisted to disk. This means that both Next.js instances are sharing the same incremental cache, which is unsupported without implementing a custom cache handler. [Docs](https://nextjs.org/docs/app/building-your-application/data-fetching/incremental-static-regeneration#customizing-the-cache-location):

> You can configure the Next.js cache location if you want to persist cached pages and data to durable storage, or share the cache across multiple containers or instances of your Next.js application. [Learn more](https://nextjs.org/docs/app/building-your-application/deploying#caching-and-isr).

When running the application in a single instance, it appears to work correctly.

https://github.com/user-attachments/assets/dc1a3c76-d255-42b7-aa85-f7f3a3afbef0

**Comment by PaulLadyman** [comment]
Hi. Sorry to comment on a closed issue but I wanted to call out a specific detail mentioned by @PeterGardenas :

> Using a custom cache handler such as [redis-handler](https://github.com/vercel/next.js/tree/canary/examples/cache-handler-redis) resolves the issue of diverging content, **_the content is still unnecessarily revalidate, causing redundant computation_**.

We're seeing the same behaviour where the first time an instance handles a page that is valid in the cache it responds with a STALE and triggers a revalidation of the page, where it should have simply returned a HIT because the page was valid. This is causing a lot of extra traffic to our back end services and creating performance problems.

We see this behaviour with or without a custom cache handler. We see it when adding a new instance into a cluster or simply restarting a single instance locally.

I have the impression that even with a custom cache handler each instance maintains a record of cached objects in memory (despite us setting `cacheMaxMemorySize: 0`), which it uses to decide whether to revalidate the page or not. A new instance is capable of retrieving an object from the cache, hence the STALE instead of a MISS, but is not sure whether it has expired or not so decides to trigger a revalidation just in case.

Happy to create a new issue with an example if necessary but wanted to ask first if this was an expected behaviour of Next or not?
