### ISSUE TITLE
Delete Props type Api Route

### ISSUE THREAD

**Issue by AbolfazlAdhami** [vercel/next.js#72549]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:13 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8112
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 20.17.0
  npm: 10.9.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.2 // There is a newer version (15.0.3) available, upgrade recommended! 
  eslint-config-next: 15.0.2
  react: 19.0.0-rc-02c0e824-20241028
  react-dom: 19.0.0-rc-02c0e824-20241028
  typescript: 5.6.3
Next.js Config:
  output: standalone
 ⚠ There is a newer version (15.0.3) available, upgrade recommended! 
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which example does this report relate to?

Api Route

### What browser are you using? (if relevant)

Chrome 100.0.4878.0

### How are you deploying your application? (if relevant)

local

### Describe the Bug

// this is my function 
export async function DELETE(req: NextRequest, { params }: Props) {
  const news = await prisma.news.findUnique({ where: { id: parseInt(params.id) } });
  if (!news) {
    return NextResponse.json({ message: "Data Not Found" }, { status: 404 });
  }
  await prisma.news.delete({ where: { id: parseInt(params.id) } });
  return NextResponse.json({ message: "Data Deleted" }, { status: 200 });
}

 
// and this is my problem when use npm run build
Type error: Route "app/api/news/[id]/route.ts" has an invalid "DELETE" export:
  Type "PropsDelete" is not a valid type for the function's second argument.

### Expected Behavior

run successfully

### To Reproduce

Type error: Route "app/api/news/[id]/route.ts" has an invalid "DELETE" export:
  Type "PropsDelete" is not a valid type for the function's second argument.

**Comment by abhiya492** [comment]
error you were seeing occurred because the Props type wasn't properly defined for Next.js route handlers.
here is key changes I made to fix the type error:

1.Properly defined the RouteParams interface
2.Changed the function parameters to use the correct typing: { params }: RouteParams
3.Added error handling with try/catch
`4.Kept` the same core functionality but with proper TypeScript types
`import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma'; // Adjust this import based on your prisma client location

// Define the params interface
interface RouteParams {
  params: {
    id: string;
  };
}

// Export the DELETE handler with correct typing
export async function DELETE(
  req: NextRequest,
  { params }: RouteParams
) {
  try {
    const news = await prisma.news.findUnique({
      where: {
        id: parseInt(params.id)
      }
    });

    if (!news) {
      return NextResponse.json(
        { message: "Data Not Found" },
        { status: 404 }
      );
    }

    await prisma.news.delete({
      where: {
        id: parseInt(params.id)
      }
    });

    return NextResponse.json(
      { message: "Data Deleted" },
      { status: 200 }
    );
  } catch (error) {
    return NextResponse.json(
      { message: "Error processing request" },
      { status: 500 }
    );
  }
}`
